// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package emailclass

import (
	"context"

	"qinglv-backend/app/user/rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddBlackItemReq                 = user.AddBlackItemReq
	AddBlackItemResp                = user.AddBlackItemResp
	AddFollowingReq                 = user.AddFollowingReq
	AddFollowingResp                = user.AddFollowingResp
	AddNotificationReq              = user.AddNotificationReq
	BanUserReq                      = user.BanUserReq
	BanUserResp                     = user.BanUserResp
	BlackItem                       = user.BlackItem
	CheckBlackItemReq               = user.CheckBlackItemReq
	CheckBlackItemResp              = user.CheckBlackItemResp
	CheckEmailExistReq              = user.CheckEmailExistReq
	CheckEmailExistResp             = user.CheckEmailExistResp
	CheckFollowingReq               = user.CheckFollowingReq
	CheckFollowingResp              = user.CheckFollowingResp
	CheckNicknameExistReq           = user.CheckNicknameExistReq
	CheckNicknameExistResp          = user.CheckNicknameExistResp
	DeleteBlackItemReq              = user.DeleteBlackItemReq
	DeleteBlackItemResp             = user.DeleteBlackItemResp
	DeleteFollowingReq              = user.DeleteFollowingReq
	DeleteFollowingResp             = user.DeleteFollowingResp
	DeleteUserReq                   = user.DeleteUserReq
	DeleteUserResp                  = user.DeleteUserResp
	Empty                           = user.Empty
	FollowingItem                   = user.FollowingItem
	GenerateCaptchaResp             = user.GenerateCaptchaResp
	GetBlackListReq                 = user.GetBlackListReq
	GetBlackListResp                = user.GetBlackListResp
	GetFollowingDetailReq           = user.GetFollowingDetailReq
	GetFollowingDetailResp          = user.GetFollowingDetailResp
	GetFollowingListReq             = user.GetFollowingListReq
	GetFollowingListResp            = user.GetFollowingListResp
	GetNotificationListReq          = user.GetNotificationListReq
	GetNotificationListResp         = user.GetNotificationListResp
	GetRoleInfoReq                  = user.GetRoleInfoReq
	GetRoleInfoResp                 = user.GetRoleInfoResp
	GetTokenReq                     = user.GetTokenReq
	GetTokenResp                    = user.GetTokenResp
	GetUnreadsNotificationCountReq  = user.GetUnreadsNotificationCountReq
	GetUnreadsNotificationCountResp = user.GetUnreadsNotificationCountResp
	GetUserByIdReq                  = user.GetUserByIdReq
	GetUserByIdResp                 = user.GetUserByIdResp
	GetUserListReq                  = user.GetUserListReq
	GetUserListResp                 = user.GetUserListResp
	LoginReq                        = user.LoginReq
	LoginResp                       = user.LoginResp
	LogoutReq                       = user.LogoutReq
	LogoutResp                      = user.LogoutResp
	NotificationItem                = user.NotificationItem
	OkResp                          = user.OkResp
	RegisterReq                     = user.RegisterReq
	RegisterResp                    = user.RegisterResp
	RoleItem                        = user.RoleItem
	SetAllReadNotificationReq       = user.SetAllReadNotificationReq
	UpdateAvatarReq                 = user.UpdateAvatarReq
	UpdateAvatarResp                = user.UpdateAvatarResp
	UpdateEmailStatusReq            = user.UpdateEmailStatusReq
	UpdateEmailStatusResp           = user.UpdateEmailStatusResp
	UpdatePasswordReq               = user.UpdatePasswordReq
	UpdatePasswordResp              = user.UpdatePasswordResp
	UpdateProfileBgReq              = user.UpdateProfileBgReq
	UpdateProfileBgResp             = user.UpdateProfileBgResp
	UpdateUserReq                   = user.UpdateUserReq
	UpdateUserResp                  = user.UpdateUserResp
	UpdateUserScoreLevelReq         = user.UpdateUserScoreLevelReq
	UpdateUserScoreLevelResp        = user.UpdateUserScoreLevelResp
	UserItem                        = user.UserItem
	VerifyCaptchaReq                = user.VerifyCaptchaReq
	VerifyCaptchaResp               = user.VerifyCaptchaResp
	VerifyRegisterCodeReq           = user.VerifyRegisterCodeReq
	VerifyRegisterCodeResp          = user.VerifyRegisterCodeResp

	EmailClass interface {
		// group: email
		VerifyRegisterCode(ctx context.Context, in *VerifyRegisterCodeReq, opts ...grpc.CallOption) (*VerifyRegisterCodeResp, error)
	}

	defaultEmailClass struct {
		cli zrpc.Client
	}
)

func NewEmailClass(cli zrpc.Client) EmailClass {
	return &defaultEmailClass{
		cli: cli,
	}
}

// group: email
func (m *defaultEmailClass) VerifyRegisterCode(ctx context.Context, in *VerifyRegisterCodeReq, opts ...grpc.CallOption) (*VerifyRegisterCodeResp, error) {
	client := user.NewEmailClassClient(m.cli.Conn())
	return client.VerifyRegisterCode(ctx, in, opts...)
}
