// Code generated by goctl. DO NOT EDIT.
// Source: content.proto

package server

import (
	"context"

	"qinglv-backend/app/content/rpc/content"
	"qinglv-backend/app/content/rpc/internal/logic/tagclass"
	"qinglv-backend/app/content/rpc/internal/svc"
)

type TagClassServer struct {
	svcCtx *svc.ServiceContext
	content.UnimplementedTagClassServer
}

func NewTagClassServer(svcCtx *svc.ServiceContext) *TagClassServer {
	return &TagClassServer{
		svcCtx: svcCtx,
	}
}

func (s *TagClassServer) AddTag(ctx context.Context, in *content.AddTagReq) (*content.OkResp, error) {
	l := tagclasslogic.NewAddTagLogic(ctx, s.svcCtx)
	return l.AddTag(in)
}

func (s *TagClassServer) DeleteTag(ctx context.Context, in *content.DeleteTagReq) (*content.OkResp, error) {
	l := tagclasslogic.NewDeleteTagLogic(ctx, s.svcCtx)
	return l.DeleteTag(in)
}

func (s *TagClassServer) UpdateTag(ctx context.Context, in *content.UpdateTagReq) (*content.OkResp, error) {
	l := tagclasslogic.NewUpdateTagLogic(ctx, s.svcCtx)
	return l.UpdateTag(in)
}

func (s *TagClassServer) GetTagById(ctx context.Context, in *content.GetTagByIdReq) (*content.GetTagByIdResp, error) {
	l := tagclasslogic.NewGetTagByIdLogic(ctx, s.svcCtx)
	return l.GetTagById(in)
}

func (s *TagClassServer) GetTagByName(ctx context.Context, in *content.GetTagByNameReq) (*content.GetTagByNameResp, error) {
	l := tagclasslogic.NewGetTagByNameLogic(ctx, s.svcCtx)
	return l.GetTagByName(in)
}

func (s *TagClassServer) GetTagList(ctx context.Context, in *content.GetTagListReq) (*content.GetTagListResp, error) {
	l := tagclasslogic.NewGetTagListLogic(ctx, s.svcCtx)
	return l.GetTagList(in)
}
