// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"qinglv-backend/app/user/rpc/internal/logic/captchaclass"
	"qinglv-backend/app/user/rpc/internal/svc"
	"qinglv-backend/app/user/rpc/user"
)

type CaptchaClassServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedCaptchaClassServer
}

func NewCaptchaClassServer(svcCtx *svc.ServiceContext) *CaptchaClassServer {
	return &CaptchaClassServer{
		svcCtx: svcCtx,
	}
}

// group: captcha
func (s *CaptchaClassServer) GenerateCaptcha(ctx context.Context, in *user.Empty) (*user.GenerateCaptchaResp, error) {
	l := captchaclasslogic.NewGenerateCaptchaLogic(ctx, s.svcCtx)
	return l.GenerateCaptcha(in)
}

// group: captcha
func (s *CaptchaClassServer) VerifyCaptcha(ctx context.Context, in *user.VerifyCaptchaReq) (*user.VerifyCaptchaResp, error) {
	l := captchaclasslogic.NewVerifyCaptchaLogic(ctx, s.svcCtx)
	return l.VerifyCaptcha(in)
}
