// Code generated by goctl. DO NOT EDIT.
// Source: content.proto

package server

import (
	"context"

	"qinglv-backend/app/content/rpc/content"
	"qinglv-backend/app/content/rpc/internal/logic/draftclass"
	"qinglv-backend/app/content/rpc/internal/svc"
)

type DraftClassServer struct {
	svcCtx *svc.ServiceContext
	content.UnimplementedDraftClassServer
}

func NewDraftClassServer(svcCtx *svc.ServiceContext) *DraftClassServer {
	return &DraftClassServer{
		svcCtx: svcCtx,
	}
}

func (s *DraftClassServer) AddDraft(ctx context.Context, in *content.AddDraftReq) (*content.OkResp, error) {
	l := draftclasslogic.NewAddDraftLogic(ctx, s.svcCtx)
	return l.AddDraft(in)
}

func (s *DraftClassServer) UpdateDraft(ctx context.Context, in *content.UpdateDraftReq) (*content.OkResp, error) {
	l := draftclasslogic.NewUpdateDraftLogic(ctx, s.svcCtx)
	return l.UpdateDraft(in)
}

func (s *DraftClassServer) DeleteDraft(ctx context.Context, in *content.DeleteDraftReq) (*content.OkResp, error) {
	l := draftclasslogic.NewDeleteDraftLogic(ctx, s.svcCtx)
	return l.DeleteDraft(in)
}

func (s *DraftClassServer) GetDraftById(ctx context.Context, in *content.GetDraftByIdReq) (*content.GetDraftByIdResp, error) {
	l := draftclasslogic.NewGetDraftByIdLogic(ctx, s.svcCtx)
	return l.GetDraftById(in)
}

func (s *DraftClassServer) GetDraftList(ctx context.Context, in *content.GetDraftListReq) (*content.GetDraftListResp, error) {
	l := draftclasslogic.NewGetDraftListLogic(ctx, s.svcCtx)
	return l.GetDraftList(in)
}
