// Code generated by goctl. DO NOT EDIT.
// Source: content.proto

package postclass

import (
	"context"

	"qinglv-backend/app/content/rpc/content"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddArticleFeedReq           = content.AddArticleFeedReq
	AddArticleReq               = content.AddArticleReq
	AddCategoryReq              = content.AddCategoryReq
	AddMediaFileReq             = content.AddMediaFileReq
	AddPostContentReq           = content.AddPostContentReq
	AddPostFeedReq              = content.AddPostFeedReq
	AddPostReq                  = content.AddPostReq
	AddTagReq                   = content.AddTagReq
	AddTopicReq                 = content.AddTopicReq
	ArticleContentItem          = content.ArticleContentItem
	ArticleItem                 = content.ArticleItem
	CategoryItem                = content.CategoryItem
	DeleteArticleFeedByIdsReq   = content.DeleteArticleFeedByIdsReq
	DeleteArticleReq            = content.DeleteArticleReq
	DeleteCategoryReq           = content.DeleteCategoryReq
	DeleteMediaFileReq          = content.DeleteMediaFileReq
	DeletePostFeedByIdsReq      = content.DeletePostFeedByIdsReq
	DeletePostReq               = content.DeletePostReq
	DeleteTagReq                = content.DeleteTagReq
	DeleteTopicReq              = content.DeleteTopicReq
	GetArticleContentDetailReq  = content.GetArticleContentDetailReq
	GetArticleContentDetailResp = content.GetArticleContentDetailResp
	GetArticleContentListReq    = content.GetArticleContentListReq
	GetArticleContentListResp   = content.GetArticleContentListResp
	GetArticleDetailReq         = content.GetArticleDetailReq
	GetArticleDetailResp        = content.GetArticleDetailResp
	GetArticleListReq           = content.GetArticleListReq
	GetArticleListResp          = content.GetArticleListResp
	GetCategoryDetailReq        = content.GetCategoryDetailReq
	GetCategoryDetailResp       = content.GetCategoryDetailResp
	GetCategoryListReq          = content.GetCategoryListReq
	GetCategoryListResp         = content.GetCategoryListResp
	GetMediaFileByContentReq    = content.GetMediaFileByContentReq
	GetMediaFileByContentResp   = content.GetMediaFileByContentResp
	GetMediaFileListReq         = content.GetMediaFileListReq
	GetMediaFileListResp        = content.GetMediaFileListResp
	GetPostContentDetailReq     = content.GetPostContentDetailReq
	GetPostContentDetailResp    = content.GetPostContentDetailResp
	GetPostContentListReq       = content.GetPostContentListReq
	GetPostContentListResp      = content.GetPostContentListResp
	GetPostDetailReq            = content.GetPostDetailReq
	GetPostDetailResp           = content.GetPostDetailResp
	GetPostListReq              = content.GetPostListReq
	GetPostListResp             = content.GetPostListResp
	GetTagByIdReq               = content.GetTagByIdReq
	GetTagByIdResp              = content.GetTagByIdResp
	GetTagByNameReq             = content.GetTagByNameReq
	GetTagByNameResp            = content.GetTagByNameResp
	GetTagListReq               = content.GetTagListReq
	GetTagListResp              = content.GetTagListResp
	GetTopicByIdReq             = content.GetTopicByIdReq
	GetTopicByIdResp            = content.GetTopicByIdResp
	GetTopicByNameReq           = content.GetTopicByNameReq
	GetTopicByNameResp          = content.GetTopicByNameResp
	GetTopicListReq             = content.GetTopicListReq
	GetTopicListResp            = content.GetTopicListResp
	MediaFile                   = content.MediaFile
	OkResp                      = content.OkResp
	PostContentItem             = content.PostContentItem
	PostItem                    = content.PostItem
	ScanArticleByUserIdReq      = content.ScanArticleByUserIdReq
	ScanPostByUserReq           = content.ScanPostByUserReq
	TagItem                     = content.TagItem
	TopicItem                   = content.TopicItem
	UpdateArticleContentReq     = content.UpdateArticleContentReq
	UpdateArticleReq            = content.UpdateArticleReq
	UpdateCategoryReq           = content.UpdateCategoryReq
	UpdatePostReq               = content.UpdatePostReq
	UpdateTagReq                = content.UpdateTagReq
	UpdateTopicReq              = content.UpdateTopicReq

	PostClass interface {
		AddPost(ctx context.Context, in *AddPostReq, opts ...grpc.CallOption) (*OkResp, error)
		DeletePost(ctx context.Context, in *DeletePostReq, opts ...grpc.CallOption) (*OkResp, error)
		UpdatePost(ctx context.Context, in *UpdatePostReq, opts ...grpc.CallOption) (*OkResp, error)
		GetPostDetail(ctx context.Context, in *GetPostDetailReq, opts ...grpc.CallOption) (*GetPostDetailResp, error)
		GetPostList(ctx context.Context, in *GetPostListReq, opts ...grpc.CallOption) (*GetPostListResp, error)
		AddPostContent(ctx context.Context, in *AddPostContentReq, opts ...grpc.CallOption) (*OkResp, error)
		GetPostContentByPostId(ctx context.Context, in *GetPostContentDetailReq, opts ...grpc.CallOption) (*GetPostContentDetailResp, error)
		ScanPostByUser(ctx context.Context, in *ScanPostByUserReq, opts ...grpc.CallOption) (*OkResp, error)
		AddPostFeed(ctx context.Context, in *AddPostFeedReq, opts ...grpc.CallOption) (*OkResp, error)
		DeletePostFeedByIds(ctx context.Context, in *DeletePostFeedByIdsReq, opts ...grpc.CallOption) (*OkResp, error)
	}

	defaultPostClass struct {
		cli zrpc.Client
	}
)

func NewPostClass(cli zrpc.Client) PostClass {
	return &defaultPostClass{
		cli: cli,
	}
}

func (m *defaultPostClass) AddPost(ctx context.Context, in *AddPostReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := content.NewPostClassClient(m.cli.Conn())
	return client.AddPost(ctx, in, opts...)
}

func (m *defaultPostClass) DeletePost(ctx context.Context, in *DeletePostReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := content.NewPostClassClient(m.cli.Conn())
	return client.DeletePost(ctx, in, opts...)
}

func (m *defaultPostClass) UpdatePost(ctx context.Context, in *UpdatePostReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := content.NewPostClassClient(m.cli.Conn())
	return client.UpdatePost(ctx, in, opts...)
}

func (m *defaultPostClass) GetPostDetail(ctx context.Context, in *GetPostDetailReq, opts ...grpc.CallOption) (*GetPostDetailResp, error) {
	client := content.NewPostClassClient(m.cli.Conn())
	return client.GetPostDetail(ctx, in, opts...)
}

func (m *defaultPostClass) GetPostList(ctx context.Context, in *GetPostListReq, opts ...grpc.CallOption) (*GetPostListResp, error) {
	client := content.NewPostClassClient(m.cli.Conn())
	return client.GetPostList(ctx, in, opts...)
}

func (m *defaultPostClass) AddPostContent(ctx context.Context, in *AddPostContentReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := content.NewPostClassClient(m.cli.Conn())
	return client.AddPostContent(ctx, in, opts...)
}

func (m *defaultPostClass) GetPostContentByPostId(ctx context.Context, in *GetPostContentDetailReq, opts ...grpc.CallOption) (*GetPostContentDetailResp, error) {
	client := content.NewPostClassClient(m.cli.Conn())
	return client.GetPostContentByPostId(ctx, in, opts...)
}

func (m *defaultPostClass) ScanPostByUser(ctx context.Context, in *ScanPostByUserReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := content.NewPostClassClient(m.cli.Conn())
	return client.ScanPostByUser(ctx, in, opts...)
}

func (m *defaultPostClass) AddPostFeed(ctx context.Context, in *AddPostFeedReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := content.NewPostClassClient(m.cli.Conn())
	return client.AddPostFeed(ctx, in, opts...)
}

func (m *defaultPostClass) DeletePostFeedByIds(ctx context.Context, in *DeletePostFeedByIdsReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := content.NewPostClassClient(m.cli.Conn())
	return client.DeletePostFeedByIds(ctx, in, opts...)
}
