// Code generated by goctl. DO NOT EDIT.
package types

type AddArticleReq struct {
	CategoryId uint64   `json:"categoryId,string,optional"`
	Tag        []string `json:"tag,optional"`
	Title      string   `json:"title" validate:"max=40"`
	Desc       string   `json:"desc,optional" validate:"max=200"`
	Content    string   `json:"content"`
	CoverImage string   `json:"coverImage,optional"`
	Visibility int      `json:"visibility,optional"`
}

type AddCategoryReq struct {
	Name        string `json:"name",validate:"required,max=50"`
	Image       string `json:"image,optional",validate:"max=200"`
	Description string `json:"description,optional",validate:"max=200"`
}

type AddPostReq struct {
	CategoryId uint64   `json:"categoryId,string,optional"`
	Topics     []string `json:"topics,optional"`
	Content    string   `json:"content" validate:"max=800"`
	Images     []string `json:"images,optional"`
	Visibility int      `json:"visibility,optional"`
	IsTop      int      `json:"isTop,optional"`
}

type AddTagReq struct {
	Name        string `json:"name",validate:"max=40"`
	Bg          string `json:"bg,optional",validate:"120"`
	Description string `json:"description,optional",validate:"120"`
	Type        int    `json:"type,options=[1,2]"`
}

type AddTopicReq struct {
	Name        string `json:"name",validate:"max=40"`
	Bg          string `json:"bg,optional",validate:"200"`
	Description string `json:"description,optional",validate:"200"`
	Type        int    `json:"type,options=[1,2]"`
}

type ArticleCategory struct {
	Id          uint64 `json:"id,string"`
	Name        string `json:"name"`
	Image       string `json:"image"`
	Description string `json:"description"`
	QuoteCount  string `json:"quoteCount"`
}

type ArticleItem struct {
	Id              uint64          `json:"id,string"`
	Category        ArticleCategory `json:"category"`
	Tag             []string        `json:"tag"`
	Title           string          `json:"title"`
	Introduction    string          `json:"introduction"`
	Content         string          `json:"content"`
	CoverImage      string          `json:"coverImage"`
	Creator         ArticleUser     `json:"creator"`
	Status          int             `json:"status"`
	Visibility      int             `json:"visibility"`
	IsTop           int             `json:"isTop"`
	Score           uint64          `json:"score"`
	CommentCount    uint64          `json:"commentCount"`
	CollectionCount uint64          `json:"collectionCount"`
	LikeCount       uint64          `json:"likeCount"`
	DislikeCount    uint64          `json:"dislikeCount"`
	ShareCount      uint64          `json:"shareCount"`
	CreatedAt       uint64          `json:"createdAt"`
	UpdatedAt       uint64          `json:"updatedAt"`
}

type ArticleUser struct {
	Id          uint64 `json:"id"`
	IsFollowing bool   `json:"isFollowing"`
	Nickname    string `json:"nickname"`
	Motto       string `json:"motto"`
	Avatar      string `json:"avatar"`
	Profession  string `json:"profession"`
	Age         int    `json:"age,range=[0:120]"`
	Gender      int    `json:"gender,options=[1,2],default=1"`
	Level       int    `json:"level"`
	Score       int    `json:"score"`
}

type CategoryItem struct {
	Id          uint64       `json:"id,string"`
	Name        string       `json:"name"`
	Image       string       `json:"image"`
	Description string       `json:"description"`
	QuoteCount  uint64       `json:"quoteCount"`
	Creator     CategoryUser `json:"creator"`
	CreatedAt   uint64       `json:"createdAt"`
	UpdatedAt   uint64       `json:"updatedAt"`
}

type CategoryUser struct {
	Id         uint64 `json:"id"`
	Nickname   string `json:"nickname"`
	Motto      string `json:"motto"`
	Avatar     string `json:"avatar"`
	Profession string `json:"profession"`
	Age        int    `json:"age,range=[0:120]"`
	Gender     int    `json:"gender,options=[1,2],default=1"`
	Level      int    `json:"level"`
	Score      int    `json:"score"`
}

type DeleteArticleReq struct {
	Id uint64 `path:"id,string"`
}

type DeleteCategoryReq struct {
	Id uint64 `path:"id,string"`
}

type DeletePostReq struct {
	Id uint64 `path:"id,string"`
}

type DeleteTagReq struct {
	Id uint64 `path:"id,string"`
}

type DeleteTopicReq struct {
	Id uint64 `path:"id,string"`
}

type GetArticleByIdReq struct {
	Id uint64 `path:"id,string"`
}

type GetArticleByIdResp struct {
	Article ArticleItem `json:"article"`
}

type GetArticleListReq struct {
	Creator    string `form:"creator,optional"`
	Status     int    `form:"status,optional"`
	Visibility int    `form:"visibility,optional"`
	Sort       string `form:"sort,optional"`
	Score      uint64 `form:"score,optional"`
	Title      string `form:"title,optional"`
	PageNum    int32  `form:"pageNum" validate:"required,gt=0"`
	PageSize   int32  `form:"pageSize" validate:"required,gt=0"`
}

type GetArticleListResp struct {
	List  []ArticleItem `json:"list"`
	IsEnd bool          `json:"isEnd"`
	Total uint64        `json:"total"`
}

type GetCategoryByIdReq struct {
	Id uint64 `path:"id,string"`
}

type GetCategoryByIdResp struct {
	Category CategoryItem `json:"category"`
}

type GetCategoryListReq struct {
	Name       string `form:"name,optional"`
	Creator    string `form:"creator,optional"`
	QuoteCount uint64 `form:"quoteCount,optional"`
	PageNum    int32  `form:"pageNum" validate:"required,gt=0"`
	PageSize   int32  `form:"pageSize" validate:"required,gt=0"`
}

type GetCategoryListResp struct {
	List  []CategoryItem `json:"list"`
	IsEnd bool           `json:"isEnd"`
	Total uint64         `json:"total"`
}

type GetPostByIdReq struct {
	Id uint64 `path:"id,string"`
}

type GetPostByIdResp struct {
	Post PostItem `json:"post"`
}

type GetPostListReq struct {
	Creator    string `form:"creator,optional"`
	Status     int    `form:"status,optional"`
	Visibility int    `form:"visibility,optional"`
	Sort       string `form:"sort,optional"`
	Score      uint64 `form:"score,optional"`
	Keyword    string `form:"keyword,optional"`
	PageNum    int32  `form:"pageNum" validate:"required,gt=0"`
	PageSize   int32  `form:"pageSize" validate:"required,gt=0"`
}

type GetPostListResp struct {
	List  []PostItem `json:"list"`
	IsEnd bool       `json:"isEnd"`
	Total uint64     `json:"total"`
}

type GetTagByIdReq struct {
	Id uint64 `path:"id,string"`
}

type GetTagByIdResp struct {
	Tag TagItem `json:"tag"`
}

type GetTagByNameReq struct {
	Name string `form:"name"`
}

type GetTagByNameResp struct {
	Tag TagItem `json:"tag"`
}

type GetTagListReq struct {
	Name       string `form:"name,optional"`
	Creator    string `form:"creator,optional"`
	QuoteCount uint64 `form:"quoteCount,optional"`
	Type       int    `form:"type,options=[1,2],optional"`
	Sort       string `form:"sort,optional"`
	PageNum    int32  `form:"pageNum" validate:"required,gt=0"`
	PageSize   int32  `form:"pageSize" validate:"required,gt=0"`
}

type GetTagListResp struct {
	List  []TagItem `json:"list"`
	IsEnd bool      `json:"isEnd"`
	Total uint64    `json:"total"`
}

type GetTopicByIdReq struct {
	Id uint64 `path:"id,string"`
}

type GetTopicByIdResp struct {
	Topic TopicItem `json:"topic"`
}

type GetTopicByNameReq struct {
	Name string `form:"name"`
}

type GetTopicByNameResp struct {
	Topic TopicItem `json:"topic"`
}

type GetTopicListReq struct {
	Name       string `form:"name,optional"`
	Creator    string `form:"creator,optional"`
	QuoteCount uint64 `form:"quoteCount,optional"`
	Type       int    `form:"type,options=[1,2],optional"`
	Sort       string `form:"sort,optional"`
	PageNum    int32  `form:"pageNum" validate:"required,gt=0"`
	PageSize   int32  `form:"pageSize" validate:"required,gt=0"`
}

type GetTopicListResp struct {
	List  []TopicItem `json:"list"`
	IsEnd bool        `json:"isEnd"`
	Total uint64      `json:"total"`
}

type GetUserArticleListReq struct {
	CreatorId uint64 `form:"creatorId,string,optional"`
	Title     string `form:"keyword,optional"`
	Sort      string `form:"sort,optional"`
	PageNum   int32  `form:"pageNum" validate:"required,gt=0"`
	PageSize  int32  `form:"pageSize" validate:"required,gt=0"`
}

type GetUserArticleListResp struct {
	List  []ArticleItem `json:"list"`
	IsEnd bool          `json:"isEnd"`
	Total uint64        `json:"total"`
}

type GetUserPostListReq struct {
	UserId   uint64 `form:"userId,string,optional"`
	Keyword  string `form:"keyword,optional"`
	Sort     string `form:"sort,optional"`
	PageNum  int32  `form:"pageNum" validate:"required,gt=0"`
	PageSize int32  `form:"pageSize" validate:"required,gt=0"`
}

type GetUserPostListResp struct {
	List  []PostItem `json:"list"`
	IsEnd bool       `json:"isEnd"`
	Total uint64     `json:"total"`
}

type PostCategory struct {
	Id          uint64 `json:"id,string"`
	Name        string `json:"name"`
	Image       string `json:"image"`
	Description string `json:"description"`
	QuoteCount  string `json:"quoteCount"`
}

type PostItem struct {
	Id              uint64       `json:"id,string"`
	Category        PostCategory `json:"category"`
	Topic           []string     `json:"topic"`
	Content         string       `json:"content"`
	Images          []string     `json:"images"`
	Creator         PostUser     `json:"creator"`
	Status          int          `json:"status"`
	Visibility      int          `json:"visibility"`
	IsTop           int          `json:"isTop"`
	Score           uint64       `json:"score"`
	Location        string       `json:"location"`
	CommentCount    uint64       `json:"commentCount"`
	CollectionCount uint64       `json:"collectionCount"`
	LikeCount       uint64       `json:"likeCount"`
	DislikeCount    uint64       `json:"dislikeCount"`
	ShareCount      uint64       `json:"shareCount"`
	LastReplyTime   uint64       `json:"lastReplyTime"`
	CreatedAt       uint64       `json:"createdAt"`
	UpdatedAt       uint64       `json:"updatedAt"`
}

type PostUser struct {
	Id            uint64 `json:"id"`
	IsFollowing   bool   `json:"isFollowing"`
	RoleId        uint64 `json:"roleId"`
	Nickname      string `json:"nickname"`
	Email         string `json:"-"`
	WeChat        string `json:"-"`
	Motto         string `json:"motto"`
	Avatar        string `json:"avatar"`
	Profession    string `json:"profession"`
	ProfileBg     string `json:"profileBg"`
	Age           int    `json:"age,range=[0:120]"`
	Gender        int    `json:"gender,options=[1,2],default=1"`
	Location      string `json:"location"`
	Address       string `json:"address"`
	Status        int    `json:"status"`
	Level         int    `json:"level"`
	Score         int    `json:"score"`
	MailStatus    int    `json:"mailStatus"`
	LastLoginTime uint64 `json:"lastLoginTime"`
	CreatedAt     uint64 `json:"createdAt"`
	UpdatedAt     uint64 `json:"updatedAt"`
}

type RemoveImagesReq struct {
	Type   int      `json:"type,options=[1,2,3,4]"`
	Images []string `json:"images"`
}

type TagItem struct {
	Id          uint64  `json:"id,string"`
	Name        string  `json:"name"`
	Bg          string  `json:"bg"`
	Description string  `json:"description"`
	QuoteCount  uint64  `json:"quoteCount"`
	Creator     TagUser `json:"creator"`
	Type        int     `json:"type"`
	CreatedAt   uint64  `json:"createdAt"`
	UpdatedAt   uint64  `json:"updatedAt"`
}

type TagUser struct {
	Id         uint64 `json:"id"`
	Nickname   string `json:"nickname"`
	Motto      string `json:"motto"`
	Avatar     string `json:"avatar"`
	Profession string `json:"profession"`
	Age        int    `json:"age,range=[0:120]"`
	Gender     int    `json:"gender,options=[1,2],default=1"`
	Level      int    `json:"level"`
	Score      int    `json:"score"`
}

type TopicItem struct {
	Id          uint64    `json:"id,string"`
	Name        string    `json:"name"`
	Bg          string    `json:"bg"`
	Description string    `json:"description"`
	QuoteCount  uint64    `json:"quoteCount"`
	Creator     TopicUser `json:"creator"`
	Type        int       `json:"type"`
	CreatedAt   uint64    `json:"createdAt"`
	UpdatedAt   uint64    `json:"updatedAt"`
}

type TopicUser struct {
	Id         uint64 `json:"id"`
	Nickname   string `json:"nickname"`
	Motto      string `json:"motto"`
	Avatar     string `json:"avatar"`
	Profession string `json:"profession"`
	Age        int    `json:"age,range=[0:120]"`
	Gender     int    `json:"gender,options=[1,2],default=1"`
	Level      int    `json:"level"`
	Score      int    `json:"score"`
}

type UpdateArticleReq struct {
	Id         uint64   `json:"id,string"`
	CategoryId uint64   `json:"categoryId,string,optional"`
	Tag        []string `json:"tag,optional"`
	Title      string   `json:"title" validate:"max=40"`
	Desc       string   `json:"desc,optional" validate:"max=200"`
	Content    string   `json:"content"`
	CoverImage string   `json:"coverImage,optional"`
	Visibility int      `json:"visibility,optional"`
}

type UpdateCategoryReq struct {
	Id          uint64 `json:"id,string"`
	Image       string `json:"image,optional",validate:"max=200"`
	Description string `json:"description,optional",validate:"max=200"`
}

type UpdateTagReq struct {
	Id          uint64 `json:"id,string"`
	Bg          string `json:"bg,optional",validate:"120"`
	Description string `json:"description,optional",validate:"120"`
	QuoteCount  uint64 `json:"quoteCount",validate:"gt=0"`
	Type        int    `json:"type,options=[1,2]"`
}

type UpdateTopicReq struct {
	Id          uint64 `json:"id,string"`
	Bg          string `json:"bg,optional",validate:"200"`
	Description string `json:"description,optional",validate:"200"`
	QuoteCount  uint64 `json:"quoteCount",validate:"gt=0"`
	Type        int    `json:"type,options=[1,2]"`
}

type UploadImagesReq struct {
	Type int `path:"type,options=[1,2,3,4]"` // 1评论，2帖子，3文章，4个人图库
}

type UploadImagesResp struct {
	Images []string `json:"images"`
}
