// Code generated by goctl. DO NOT EDIT.
// Source: operation.proto

package operation_client

import (
	"context"

	"qinglv-backend/app/operation/rpc/operation"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddCollectionGroupReq      = operation.AddCollectionGroupReq
	AddCollectionReq           = operation.AddCollectionReq
	AddCommentThumbReq         = operation.AddCommentThumbReq
	AddPostShareReq            = operation.AddPostShareReq
	AddThumbReq                = operation.AddThumbReq
	ArticleCommentThumbItem    = operation.ArticleCommentThumbItem
	ArticleThumbItem           = operation.ArticleThumbItem
	CheckExistByNameReq        = operation.CheckExistByNameReq
	CheckExistByNameResp       = operation.CheckExistByNameResp
	CollectionGroupItem        = operation.CollectionGroupItem
	CollectionItem             = operation.CollectionItem
	DeleteCollectionGroupReq   = operation.DeleteCollectionGroupReq
	DeleteCollectionReq        = operation.DeleteCollectionReq
	GetCollectionByIdReq       = operation.GetCollectionByIdReq
	GetCollectionByIdResp      = operation.GetCollectionByIdResp
	GetCollectionGroupByIdReq  = operation.GetCollectionGroupByIdReq
	GetCollectionGroupByIdResp = operation.GetCollectionGroupByIdResp
	GetCollectionGroupListReq  = operation.GetCollectionGroupListReq
	GetCollectionGroupListResp = operation.GetCollectionGroupListResp
	GetCollectionListReq       = operation.GetCollectionListReq
	GetCollectionListResp      = operation.GetCollectionListResp
	GetCommentThumbDetailReq   = operation.GetCommentThumbDetailReq
	GetCommentThumbDetailResp  = operation.GetCommentThumbDetailResp
	GetThumbDetailReq          = operation.GetThumbDetailReq
	GetThumbDetailResp         = operation.GetThumbDetailResp
	OkResp                     = operation.OkResp
	PostCommentThumbItem       = operation.PostCommentThumbItem
	PostThumbItem              = operation.PostThumbItem
	UpdateCollectionGroupReq   = operation.UpdateCollectionGroupReq
	UpdateCommentThumbReq      = operation.UpdateCommentThumbReq
	UpdateThumbReq             = operation.UpdateThumbReq

	Operation interface {
		// group: CollectionGroup
		AddCollectionGroup(ctx context.Context, in *AddCollectionGroupReq, opts ...grpc.CallOption) (*OkResp, error)
		// group: CollectionGroup
		GetCollectionGroupList(ctx context.Context, in *GetCollectionGroupListReq, opts ...grpc.CallOption) (*GetCollectionGroupListResp, error)
		// group: CollectionGroup
		GetCollectionGroupById(ctx context.Context, in *GetCollectionGroupByIdReq, opts ...grpc.CallOption) (*GetCollectionGroupByIdResp, error)
		// group: CollectionGroup
		CheckExistByName(ctx context.Context, in *CheckExistByNameReq, opts ...grpc.CallOption) (*CheckExistByNameResp, error)
		// group: CollectionGroup
		UpdateCollectionGroup(ctx context.Context, in *UpdateCollectionGroupReq, opts ...grpc.CallOption) (*OkResp, error)
		// group: CollectionGroup
		DeleteCollectionGroup(ctx context.Context, in *DeleteCollectionGroupReq, opts ...grpc.CallOption) (*OkResp, error)
		// group: Collection
		AddCollection(ctx context.Context, in *AddCollectionReq, opts ...grpc.CallOption) (*OkResp, error)
		// group: Collection
		DeleteCollection(ctx context.Context, in *DeleteCollectionReq, opts ...grpc.CallOption) (*OkResp, error)
		// group: Collection
		GetCollectionList(ctx context.Context, in *GetCollectionListReq, opts ...grpc.CallOption) (*GetCollectionListResp, error)
		// group: Collection
		GetCollectionById(ctx context.Context, in *GetCollectionByIdReq, opts ...grpc.CallOption) (*GetCollectionByIdResp, error)
		// group: Share
		AddPostShare(ctx context.Context, in *AddPostShareReq, opts ...grpc.CallOption) (*OkResp, error)
		// group: Thumb
		AddThumb(ctx context.Context, in *AddThumbReq, opts ...grpc.CallOption) (*OkResp, error)
		// group: PostThumb
		UpdateThumb(ctx context.Context, in *UpdateThumbReq, opts ...grpc.CallOption) (*OkResp, error)
		// group: PostThumb
		GetThumbDetail(ctx context.Context, in *GetThumbDetailReq, opts ...grpc.CallOption) (*GetThumbDetailResp, error)
		// group: CommentThumb
		AddCommentThumb(ctx context.Context, in *AddCommentThumbReq, opts ...grpc.CallOption) (*OkResp, error)
		// group: PostCommentThumb
		UpdateCommentThumb(ctx context.Context, in *UpdateCommentThumbReq, opts ...grpc.CallOption) (*OkResp, error)
		// group: PostCommentThumb
		GetCommentThumbDetail(ctx context.Context, in *GetCommentThumbDetailReq, opts ...grpc.CallOption) (*GetCommentThumbDetailReq, error)
	}

	defaultOperation struct {
		cli zrpc.Client
	}
)

func NewOperation(cli zrpc.Client) Operation {
	return &defaultOperation{
		cli: cli,
	}
}

// group: CollectionGroup
func (m *defaultOperation) AddCollectionGroup(ctx context.Context, in *AddCollectionGroupReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := operation.NewOperationClient(m.cli.Conn())
	return client.AddCollectionGroup(ctx, in, opts...)
}

// group: CollectionGroup
func (m *defaultOperation) GetCollectionGroupList(ctx context.Context, in *GetCollectionGroupListReq, opts ...grpc.CallOption) (*GetCollectionGroupListResp, error) {
	client := operation.NewOperationClient(m.cli.Conn())
	return client.GetCollectionGroupList(ctx, in, opts...)
}

// group: CollectionGroup
func (m *defaultOperation) GetCollectionGroupById(ctx context.Context, in *GetCollectionGroupByIdReq, opts ...grpc.CallOption) (*GetCollectionGroupByIdResp, error) {
	client := operation.NewOperationClient(m.cli.Conn())
	return client.GetCollectionGroupById(ctx, in, opts...)
}

// group: CollectionGroup
func (m *defaultOperation) CheckExistByName(ctx context.Context, in *CheckExistByNameReq, opts ...grpc.CallOption) (*CheckExistByNameResp, error) {
	client := operation.NewOperationClient(m.cli.Conn())
	return client.CheckExistByName(ctx, in, opts...)
}

// group: CollectionGroup
func (m *defaultOperation) UpdateCollectionGroup(ctx context.Context, in *UpdateCollectionGroupReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := operation.NewOperationClient(m.cli.Conn())
	return client.UpdateCollectionGroup(ctx, in, opts...)
}

// group: CollectionGroup
func (m *defaultOperation) DeleteCollectionGroup(ctx context.Context, in *DeleteCollectionGroupReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := operation.NewOperationClient(m.cli.Conn())
	return client.DeleteCollectionGroup(ctx, in, opts...)
}

// group: Collection
func (m *defaultOperation) AddCollection(ctx context.Context, in *AddCollectionReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := operation.NewOperationClient(m.cli.Conn())
	return client.AddCollection(ctx, in, opts...)
}

// group: Collection
func (m *defaultOperation) DeleteCollection(ctx context.Context, in *DeleteCollectionReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := operation.NewOperationClient(m.cli.Conn())
	return client.DeleteCollection(ctx, in, opts...)
}

// group: Collection
func (m *defaultOperation) GetCollectionList(ctx context.Context, in *GetCollectionListReq, opts ...grpc.CallOption) (*GetCollectionListResp, error) {
	client := operation.NewOperationClient(m.cli.Conn())
	return client.GetCollectionList(ctx, in, opts...)
}

// group: Collection
func (m *defaultOperation) GetCollectionById(ctx context.Context, in *GetCollectionByIdReq, opts ...grpc.CallOption) (*GetCollectionByIdResp, error) {
	client := operation.NewOperationClient(m.cli.Conn())
	return client.GetCollectionById(ctx, in, opts...)
}

// group: Share
func (m *defaultOperation) AddPostShare(ctx context.Context, in *AddPostShareReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := operation.NewOperationClient(m.cli.Conn())
	return client.AddPostShare(ctx, in, opts...)
}

// group: Thumb
func (m *defaultOperation) AddThumb(ctx context.Context, in *AddThumbReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := operation.NewOperationClient(m.cli.Conn())
	return client.AddThumb(ctx, in, opts...)
}

// group: PostThumb
func (m *defaultOperation) UpdateThumb(ctx context.Context, in *UpdateThumbReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := operation.NewOperationClient(m.cli.Conn())
	return client.UpdateThumb(ctx, in, opts...)
}

// group: PostThumb
func (m *defaultOperation) GetThumbDetail(ctx context.Context, in *GetThumbDetailReq, opts ...grpc.CallOption) (*GetThumbDetailResp, error) {
	client := operation.NewOperationClient(m.cli.Conn())
	return client.GetThumbDetail(ctx, in, opts...)
}

// group: CommentThumb
func (m *defaultOperation) AddCommentThumb(ctx context.Context, in *AddCommentThumbReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := operation.NewOperationClient(m.cli.Conn())
	return client.AddCommentThumb(ctx, in, opts...)
}

// group: PostCommentThumb
func (m *defaultOperation) UpdateCommentThumb(ctx context.Context, in *UpdateCommentThumbReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := operation.NewOperationClient(m.cli.Conn())
	return client.UpdateCommentThumb(ctx, in, opts...)
}

// group: PostCommentThumb
func (m *defaultOperation) GetCommentThumbDetail(ctx context.Context, in *GetCommentThumbDetailReq, opts ...grpc.CallOption) (*GetCommentThumbDetailReq, error) {
	client := operation.NewOperationClient(m.cli.Conn())
	return client.GetCommentThumbDetail(ctx, in, opts...)
}
