// Code generated by goctl. DO NOT EDIT!

package draft

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"time"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"qinglv-backend/common/globalKey"
)

var (
	articleDraftFieldNames          = builder.RawFieldNames(&ArticleDraft{})
	articleDraftRows                = strings.Join(articleDraftFieldNames, ",")
	articleDraftRowsExpectAutoSet   = strings.Join(stringx.Remove(articleDraftFieldNames, "`created_at`", "`updated_at`"), ",")
	articleDraftRowsWithPlaceHolder = strings.Join(stringx.Remove(articleDraftFieldNames, "`id`", "`created_at`", "`updated_at`"), "=?,") + "=?"
)

type (
	articleDraftModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *ArticleDraft) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ArticleDraft, error)
		Update(ctx context.Context, session sqlx.Session, data *ArticleDraft) (sql.Result, error)
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *ArticleDraft) error
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		DeleteSoft(ctx context.Context, session sqlx.Session, data *ArticleDraft) error
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*ArticleDraft, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ArticleDraft, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ArticleDraft, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*ArticleDraft, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*ArticleDraft, error)
		Delete(ctx context.Context, session sqlx.Session, id uint64) error
	}

	defaultArticleDraftModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ArticleDraft struct {
		Id          uint64    `db:"id"`         // 主键id
		Title       string    `db:"title"`      // 文章标题
		Content     string    `db:"content"`    // 内容
		CreatedAt   time.Time `db:"created_at"` // 创建时间
		UpdatedAt   time.Time `db:"updated_at"` // 修改时间
		DeletedAt   time.Time `db:"deleted_at"` // 删除时间
		IsDel       int64     `db:"is_del"`
		Version     int64     `db:"version"`    // 版本号
		CreatorId   uint64    `db:"creator_id"` // 发布者
		CreatorName string    `db:"creator_name"`
	}
)

func newArticleDraftModel(conn sqlx.SqlConn) *defaultArticleDraftModel {
	return &defaultArticleDraftModel{
		conn:  conn,
		table: "`article_draft`",
	}
}

func (m *defaultArticleDraftModel) Insert(ctx context.Context, session sqlx.Session, data *ArticleDraft) (sql.Result, error) {
	data.DeletedAt = time.Unix(0, 0)
	data.IsDel = globalKey.DelStateNo

	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, articleDraftRowsExpectAutoSet)
	if session != nil {
		return session.ExecCtx(ctx, query, data.Id, data.Title, data.Content, data.DeletedAt, data.IsDel, data.Version, data.CreatorId, data.CreatorName)
	}
	return m.conn.ExecCtx(ctx, query, data.Id, data.Title, data.Content, data.DeletedAt, data.IsDel, data.Version, data.CreatorId, data.CreatorName)
}

func (m *defaultArticleDraftModel) FindOne(ctx context.Context, id uint64) (*ArticleDraft, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ?  and is_del = ? limit 1", articleDraftRows, m.table)
	var resp ArticleDraft
	err := m.conn.QueryRowCtx(ctx, &resp, query, id, globalKey.DelStateNo)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultArticleDraftModel) Update(ctx context.Context, session sqlx.Session, data *ArticleDraft) (sql.Result, error) {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, articleDraftRowsWithPlaceHolder)
	if session != nil {
		return session.ExecCtx(ctx, query, data.Title, data.Content, data.DeletedAt, data.IsDel, data.Version, data.CreatorId, data.CreatorName, data.Id)
	}
	return m.conn.ExecCtx(ctx, query, data.Title, data.Content, data.DeletedAt, data.IsDel, data.Version, data.CreatorId, data.CreatorName, data.Id)
}

func (m *defaultArticleDraftModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, data *ArticleDraft) error {

	oldVersion := data.Version
	data.Version += 1

	var sqlResult sql.Result
	var err error

	query := fmt.Sprintf("update %s set %s where `id` = ? and version = ? ", m.table, articleDraftRowsWithPlaceHolder)
	if session != nil {
		sqlResult, err = session.ExecCtx(ctx, query, data.Title, data.Content, data.DeletedAt, data.IsDel, data.Version, data.CreatorId, data.CreatorName, data.Id, oldVersion)
	} else {
		sqlResult, err = m.conn.ExecCtx(ctx, query, data.Title, data.Content, data.DeletedAt, data.IsDel, data.Version, data.CreatorId, data.CreatorName, data.Id, oldVersion)
	}

	if err != nil {
		return err
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return ErrNoRowsUpdate
	}

	return nil
}

func (m *defaultArticleDraftModel) DeleteSoft(ctx context.Context, session sqlx.Session, data *ArticleDraft) error {
	data.IsDel = globalKey.DelStateYes
	data.DeletedAt = time.Now()
	if err := m.UpdateWithVersion(ctx, session, data); err != nil {
		return errors.Wrapf(errors.New("delete soft failed "), "ArticleDraftModel delete err : %+v", err)
	}
	return nil
}

func (m *defaultArticleDraftModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.Where("is_del = ?", globalKey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultArticleDraftModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.Where("is_del = ?", globalKey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultArticleDraftModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*ArticleDraft, error) {

	builder = builder.Columns(articleDraftRows)

	if orderBy == "" {
		builder = builder.OrderBy("created_at DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.Where("is_del = ?", globalKey.DelStateNo).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ArticleDraft

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultArticleDraftModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ArticleDraft, error) {

	builder = builder.Columns(articleDraftRows)

	if orderBy == "" {
		builder = builder.OrderBy("created_at DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("is_del = ?", globalKey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ArticleDraft

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultArticleDraftModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ArticleDraft, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(articleDraftRows)

	if orderBy == "" {
		builder = builder.OrderBy("created_at DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("is_del = ?", globalKey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*ArticleDraft

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultArticleDraftModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*ArticleDraft, error) {

	builder = builder.Columns(articleDraftRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.Where("is_del = ?", globalKey.DelStateNo).OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ArticleDraft

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultArticleDraftModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*ArticleDraft, error) {

	builder = builder.Columns(articleDraftRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.Where("is_del = ?", globalKey.DelStateNo).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ArticleDraft

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultArticleDraftModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.conn.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultArticleDraftModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
func (m *defaultArticleDraftModel) Delete(ctx context.Context, session sqlx.Session, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	if session != nil {
		_, err := session.ExecCtx(ctx, query, id)
		return err
	}
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultArticleDraftModel) tableName() string {
	return m.table
}
