// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package user_client

import (
	"context"

	"qinglv-backend/app/user/rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetRoleInfoReq         = user.GetRoleInfoReq
	GetRoleInfoResp        = user.GetRoleInfoResp
	GetUserInfoEmailReq    = user.GetUserInfoEmailReq
	GetUserInfoNicknameReq = user.GetUserInfoNicknameReq
	GetUserInfoReq         = user.GetUserInfoReq
	GetUserInfoResp        = user.GetUserInfoResp
	GetUserListReq         = user.GetUserListReq
	GetUserListResp        = user.GetUserListResp
	LoginReq               = user.LoginReq
	LoginResp              = user.LoginResp
	RegisterReq            = user.RegisterReq
	RegisterResp           = user.RegisterResp
	RoleItem               = user.RoleItem
	UserItem               = user.UserItem

	User interface {
		// group: role
		GetRoleInfo(ctx context.Context, in *GetRoleInfoReq, opts ...grpc.CallOption) (*GetRoleInfoResp, error)
		// group: user
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
		// group: user
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		// group: user
		GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
		// group: user
		GetUserInfoByNickname(ctx context.Context, in *GetUserInfoNicknameReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
		// group: user
		GetUserInfoByEmail(ctx context.Context, in *GetUserInfoEmailReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
		GetUserList(ctx context.Context, in *GetUserListReq, opts ...grpc.CallOption) (*GetUserListResp, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

// group: role
func (m *defaultUser) GetRoleInfo(ctx context.Context, in *GetRoleInfoReq, opts ...grpc.CallOption) (*GetRoleInfoResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetRoleInfo(ctx, in, opts...)
}

// group: user
func (m *defaultUser) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

// group: user
func (m *defaultUser) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

// group: user
func (m *defaultUser) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

// group: user
func (m *defaultUser) GetUserInfoByNickname(ctx context.Context, in *GetUserInfoNicknameReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUserInfoByNickname(ctx, in, opts...)
}

// group: user
func (m *defaultUser) GetUserInfoByEmail(ctx context.Context, in *GetUserInfoEmailReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUserInfoByEmail(ctx, in, opts...)
}

func (m *defaultUser) GetUserList(ctx context.Context, in *GetUserListReq, opts ...grpc.CallOption) (*GetUserListResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUserList(ctx, in, opts...)
}
