// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"qinglv-backend/app/user/rpc/internal/logic/notificationclass"
	"qinglv-backend/app/user/rpc/internal/svc"
	"qinglv-backend/app/user/rpc/user"
)

type NotificationClassServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedNotificationClassServer
}

func NewNotificationClassServer(svcCtx *svc.ServiceContext) *NotificationClassServer {
	return &NotificationClassServer{
		svcCtx: svcCtx,
	}
}

func (s *NotificationClassServer) AddNotification(ctx context.Context, in *user.AddNotificationReq) (*user.OkResp, error) {
	l := notificationclasslogic.NewAddNotificationLogic(ctx, s.svcCtx)
	return l.AddNotification(in)
}

func (s *NotificationClassServer) SetAllReadNotification(ctx context.Context, in *user.SetAllReadNotificationReq) (*user.OkResp, error) {
	l := notificationclasslogic.NewSetAllReadNotificationLogic(ctx, s.svcCtx)
	return l.SetAllReadNotification(in)
}

func (s *NotificationClassServer) GetUnreadsNotificationCount(ctx context.Context, in *user.GetUnreadsNotificationCountReq) (*user.GetUnreadsNotificationCountResp, error) {
	l := notificationclasslogic.NewGetUnreadsNotificationCountLogic(ctx, s.svcCtx)
	return l.GetUnreadsNotificationCount(in)
}

func (s *NotificationClassServer) GetNotificationList(ctx context.Context, in *user.GetNotificationListReq) (*user.GetNotificationListResp, error) {
	l := notificationclasslogic.NewGetNotificationListLogic(ctx, s.svcCtx)
	return l.GetNotificationList(in)
}
