// Code generated by goctl. DO NOT EDIT.
// Source: content.proto

package tagclass

import (
	"context"

	"qinglv-backend/app/content/rpc/content"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddArticleReq               = content.AddArticleReq
	AddCategoryReq              = content.AddCategoryReq
	AddMediaFileReq             = content.AddMediaFileReq
	AddPostContentReq           = content.AddPostContentReq
	AddPostReq                  = content.AddPostReq
	AddTagReq                   = content.AddTagReq
	AddTopicReq                 = content.AddTopicReq
	ArticleContentItem          = content.ArticleContentItem
	ArticleItem                 = content.ArticleItem
	CategoryItem                = content.CategoryItem
	DeleteArticleReq            = content.DeleteArticleReq
	DeleteCategoryReq           = content.DeleteCategoryReq
	DeleteMediaFileReq          = content.DeleteMediaFileReq
	DeletePostReq               = content.DeletePostReq
	DeleteTagReq                = content.DeleteTagReq
	DeleteTopicReq              = content.DeleteTopicReq
	GetArticleContentDetailReq  = content.GetArticleContentDetailReq
	GetArticleContentDetailResp = content.GetArticleContentDetailResp
	GetArticleContentListReq    = content.GetArticleContentListReq
	GetArticleContentListResp   = content.GetArticleContentListResp
	GetArticleDetailReq         = content.GetArticleDetailReq
	GetArticleDetailResp        = content.GetArticleDetailResp
	GetArticleListReq           = content.GetArticleListReq
	GetArticleListResp          = content.GetArticleListResp
	GetCategoryDetailReq        = content.GetCategoryDetailReq
	GetCategoryDetailResp       = content.GetCategoryDetailResp
	GetCategoryListReq          = content.GetCategoryListReq
	GetCategoryListResp         = content.GetCategoryListResp
	GetMediaFileByContentReq    = content.GetMediaFileByContentReq
	GetMediaFileByContentResp   = content.GetMediaFileByContentResp
	GetMediaFileListReq         = content.GetMediaFileListReq
	GetMediaFileListResp        = content.GetMediaFileListResp
	GetPostContentDetailReq     = content.GetPostContentDetailReq
	GetPostContentDetailResp    = content.GetPostContentDetailResp
	GetPostContentListReq       = content.GetPostContentListReq
	GetPostContentListResp      = content.GetPostContentListResp
	GetPostDetailReq            = content.GetPostDetailReq
	GetPostDetailResp           = content.GetPostDetailResp
	GetPostListReq              = content.GetPostListReq
	GetPostListResp             = content.GetPostListResp
	GetTagByIdReq               = content.GetTagByIdReq
	GetTagByIdResp              = content.GetTagByIdResp
	GetTagByNameReq             = content.GetTagByNameReq
	GetTagByNameResp            = content.GetTagByNameResp
	GetTagListReq               = content.GetTagListReq
	GetTagListResp              = content.GetTagListResp
	GetTopicByIdReq             = content.GetTopicByIdReq
	GetTopicByIdResp            = content.GetTopicByIdResp
	GetTopicByNameReq           = content.GetTopicByNameReq
	GetTopicByNameResp          = content.GetTopicByNameResp
	GetTopicListReq             = content.GetTopicListReq
	GetTopicListResp            = content.GetTopicListResp
	MediaFile                   = content.MediaFile
	OkResp                      = content.OkResp
	PostContentItem             = content.PostContentItem
	PostItem                    = content.PostItem
	TagItem                     = content.TagItem
	TopicItem                   = content.TopicItem
	UpdateArticleContentReq     = content.UpdateArticleContentReq
	UpdateArticleReq            = content.UpdateArticleReq
	UpdateCategoryReq           = content.UpdateCategoryReq
	UpdatePostReq               = content.UpdatePostReq
	UpdateTagReq                = content.UpdateTagReq
	UpdateTopicReq              = content.UpdateTopicReq

	TagClass interface {
		AddTag(ctx context.Context, in *AddTagReq, opts ...grpc.CallOption) (*OkResp, error)
		DeleteTag(ctx context.Context, in *DeleteTagReq, opts ...grpc.CallOption) (*OkResp, error)
		UpdateTag(ctx context.Context, in *UpdateTagReq, opts ...grpc.CallOption) (*OkResp, error)
		GetTagById(ctx context.Context, in *GetTagByIdReq, opts ...grpc.CallOption) (*GetTagByIdResp, error)
		GetTagByName(ctx context.Context, in *GetTagByNameReq, opts ...grpc.CallOption) (*GetTagByNameResp, error)
		GetTagList(ctx context.Context, in *GetTagListReq, opts ...grpc.CallOption) (*GetTagListResp, error)
	}

	defaultTagClass struct {
		cli zrpc.Client
	}
)

func NewTagClass(cli zrpc.Client) TagClass {
	return &defaultTagClass{
		cli: cli,
	}
}

func (m *defaultTagClass) AddTag(ctx context.Context, in *AddTagReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := content.NewTagClassClient(m.cli.Conn())
	return client.AddTag(ctx, in, opts...)
}

func (m *defaultTagClass) DeleteTag(ctx context.Context, in *DeleteTagReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := content.NewTagClassClient(m.cli.Conn())
	return client.DeleteTag(ctx, in, opts...)
}

func (m *defaultTagClass) UpdateTag(ctx context.Context, in *UpdateTagReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := content.NewTagClassClient(m.cli.Conn())
	return client.UpdateTag(ctx, in, opts...)
}

func (m *defaultTagClass) GetTagById(ctx context.Context, in *GetTagByIdReq, opts ...grpc.CallOption) (*GetTagByIdResp, error) {
	client := content.NewTagClassClient(m.cli.Conn())
	return client.GetTagById(ctx, in, opts...)
}

func (m *defaultTagClass) GetTagByName(ctx context.Context, in *GetTagByNameReq, opts ...grpc.CallOption) (*GetTagByNameResp, error) {
	client := content.NewTagClassClient(m.cli.Conn())
	return client.GetTagByName(ctx, in, opts...)
}

func (m *defaultTagClass) GetTagList(ctx context.Context, in *GetTagListReq, opts ...grpc.CallOption) (*GetTagListResp, error) {
	client := content.NewTagClassClient(m.cli.Conn())
	return client.GetTagList(ctx, in, opts...)
}
