// Code generated by goctl. DO NOT EDIT.
// Source: content.proto

package categoryclass

import (
	"context"

	"qinglv-backend/app/content/rpc/content"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddArticleReq               = content.AddArticleReq
	AddCategoryReq              = content.AddCategoryReq
	AddMediaFileReq             = content.AddMediaFileReq
	AddPostContentReq           = content.AddPostContentReq
	AddPostReq                  = content.AddPostReq
	AddTagReq                   = content.AddTagReq
	AddTopicReq                 = content.AddTopicReq
	ArticleContentItem          = content.ArticleContentItem
	ArticleItem                 = content.ArticleItem
	CategoryItem                = content.CategoryItem
	DeleteArticleReq            = content.DeleteArticleReq
	DeleteCategoryReq           = content.DeleteCategoryReq
	DeleteMediaFileReq          = content.DeleteMediaFileReq
	DeletePostReq               = content.DeletePostReq
	DeleteTagReq                = content.DeleteTagReq
	DeleteTopicReq              = content.DeleteTopicReq
	GetArticleContentDetailReq  = content.GetArticleContentDetailReq
	GetArticleContentDetailResp = content.GetArticleContentDetailResp
	GetArticleContentListReq    = content.GetArticleContentListReq
	GetArticleContentListResp   = content.GetArticleContentListResp
	GetArticleDetailReq         = content.GetArticleDetailReq
	GetArticleDetailResp        = content.GetArticleDetailResp
	GetArticleListReq           = content.GetArticleListReq
	GetArticleListResp          = content.GetArticleListResp
	GetCategoryDetailReq        = content.GetCategoryDetailReq
	GetCategoryDetailResp       = content.GetCategoryDetailResp
	GetCategoryListReq          = content.GetCategoryListReq
	GetCategoryListResp         = content.GetCategoryListResp
	GetMediaFileByContentReq    = content.GetMediaFileByContentReq
	GetMediaFileByContentResp   = content.GetMediaFileByContentResp
	GetMediaFileListReq         = content.GetMediaFileListReq
	GetMediaFileListResp        = content.GetMediaFileListResp
	GetPostContentDetailReq     = content.GetPostContentDetailReq
	GetPostContentDetailResp    = content.GetPostContentDetailResp
	GetPostContentListReq       = content.GetPostContentListReq
	GetPostContentListResp      = content.GetPostContentListResp
	GetPostDetailReq            = content.GetPostDetailReq
	GetPostDetailResp           = content.GetPostDetailResp
	GetPostListReq              = content.GetPostListReq
	GetPostListResp             = content.GetPostListResp
	GetTagByIdReq               = content.GetTagByIdReq
	GetTagByIdResp              = content.GetTagByIdResp
	GetTagByNameReq             = content.GetTagByNameReq
	GetTagByNameResp            = content.GetTagByNameResp
	GetTagListReq               = content.GetTagListReq
	GetTagListResp              = content.GetTagListResp
	GetTopicByIdReq             = content.GetTopicByIdReq
	GetTopicByIdResp            = content.GetTopicByIdResp
	GetTopicByNameReq           = content.GetTopicByNameReq
	GetTopicByNameResp          = content.GetTopicByNameResp
	GetTopicListReq             = content.GetTopicListReq
	GetTopicListResp            = content.GetTopicListResp
	MediaFile                   = content.MediaFile
	OkResp                      = content.OkResp
	PostContentItem             = content.PostContentItem
	PostItem                    = content.PostItem
	TagItem                     = content.TagItem
	TopicItem                   = content.TopicItem
	UpdateArticleContentReq     = content.UpdateArticleContentReq
	UpdateArticleReq            = content.UpdateArticleReq
	UpdateCategoryReq           = content.UpdateCategoryReq
	UpdatePostReq               = content.UpdatePostReq
	UpdateTagReq                = content.UpdateTagReq
	UpdateTopicReq              = content.UpdateTopicReq

	CategoryClass interface {
		// group: category
		AddCategory(ctx context.Context, in *AddCategoryReq, opts ...grpc.CallOption) (*OkResp, error)
		// group: category
		DeleteCategory(ctx context.Context, in *DeleteCategoryReq, opts ...grpc.CallOption) (*OkResp, error)
		// group: category
		UpdateCategory(ctx context.Context, in *UpdateCategoryReq, opts ...grpc.CallOption) (*OkResp, error)
		// group: category
		GetCategoryDetail(ctx context.Context, in *GetCategoryDetailReq, opts ...grpc.CallOption) (*GetCategoryDetailResp, error)
		// group: category
		GetCategoryList(ctx context.Context, in *GetCategoryListReq, opts ...grpc.CallOption) (*GetCategoryListResp, error)
	}

	defaultCategoryClass struct {
		cli zrpc.Client
	}
)

func NewCategoryClass(cli zrpc.Client) CategoryClass {
	return &defaultCategoryClass{
		cli: cli,
	}
}

// group: category
func (m *defaultCategoryClass) AddCategory(ctx context.Context, in *AddCategoryReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := content.NewCategoryClassClient(m.cli.Conn())
	return client.AddCategory(ctx, in, opts...)
}

// group: category
func (m *defaultCategoryClass) DeleteCategory(ctx context.Context, in *DeleteCategoryReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := content.NewCategoryClassClient(m.cli.Conn())
	return client.DeleteCategory(ctx, in, opts...)
}

// group: category
func (m *defaultCategoryClass) UpdateCategory(ctx context.Context, in *UpdateCategoryReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := content.NewCategoryClassClient(m.cli.Conn())
	return client.UpdateCategory(ctx, in, opts...)
}

// group: category
func (m *defaultCategoryClass) GetCategoryDetail(ctx context.Context, in *GetCategoryDetailReq, opts ...grpc.CallOption) (*GetCategoryDetailResp, error) {
	client := content.NewCategoryClassClient(m.cli.Conn())
	return client.GetCategoryDetail(ctx, in, opts...)
}

// group: category
func (m *defaultCategoryClass) GetCategoryList(ctx context.Context, in *GetCategoryListReq, opts ...grpc.CallOption) (*GetCategoryListResp, error) {
	client := content.NewCategoryClassClient(m.cli.Conn())
	return client.GetCategoryList(ctx, in, opts...)
}
