// Code generated by goctl. DO NOT EDIT!

package comment

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"time"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"qinglv-backend/common/globalKey"
)

var (
	articleCommentReplyFieldNames          = builder.RawFieldNames(&ArticleCommentReply{})
	articleCommentReplyRows                = strings.Join(articleCommentReplyFieldNames, ",")
	articleCommentReplyRowsExpectAutoSet   = strings.Join(stringx.Remove(articleCommentReplyFieldNames, "`created_at`", "`updated_at`"), ",")
	articleCommentReplyRowsWithPlaceHolder = strings.Join(stringx.Remove(articleCommentReplyFieldNames, "`id`", "`created_at`", "`updated_at`"), "=?,") + "=?"

	cacheQOperationArticleCommentReplyIdPrefix = "cache:qOperation:articleCommentReply:id:"
)

type (
	articleCommentReplyModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *ArticleCommentReply) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ArticleCommentReply, error)
		Update(ctx context.Context, session sqlx.Session, data *ArticleCommentReply) (sql.Result, error)
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *ArticleCommentReply) error
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		DeleteSoft(ctx context.Context, session sqlx.Session, data *ArticleCommentReply) error
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*ArticleCommentReply, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ArticleCommentReply, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ArticleCommentReply, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*ArticleCommentReply, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*ArticleCommentReply, error)
		Delete(ctx context.Context, session sqlx.Session, id uint64) error
	}

	defaultArticleCommentReplyModel struct {
		sqlc.CachedConn
		table string
	}

	ArticleCommentReply struct {
		Id           uint64    `db:"id"`
		ArticleId    uint64    `db:"article_id"`
		CreatorId    uint64    `db:"creator_id"`
		CreatorName  string    `db:"creator_name"`
		CommentId    uint64    `db:"comment_id"`    // 回复评论id
		AtUserId     uint64    `db:"at_user_id"`    // 回复id
		AtUserName   string    `db:"at_user_name"`  // 回复昵称
		Content      string    `db:"content"`       // 评论内容
		Visibility   int64     `db:"visibility"`    // 是否显示：1显示2隐藏
		LikeCount    uint64    `db:"like_count"`    // 点赞数
		DislikeCount uint64    `db:"dislike_count"` // 点踩数
		Score        uint64    `db:"score"`         // 热度分数:一个点赞一分,一个点踩扣2分
		Location     string    `db:"location"`      // ip城市
		CreatedAt    time.Time `db:"created_at"`    // 创建时间
		UpdatedAt    time.Time `db:"updated_at"`    // 修改时间
		DeletedAt    time.Time `db:"deleted_at"`    // 删除时间
		IsDel        int64     `db:"is_del"`
		Version      int64     `db:"version"` // 版本号
	}
)

func newArticleCommentReplyModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultArticleCommentReplyModel {
	return &defaultArticleCommentReplyModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`article_comment_reply`",
	}
}

func (m *defaultArticleCommentReplyModel) Insert(ctx context.Context, session sqlx.Session, data *ArticleCommentReply) (sql.Result, error) {
	data.DeletedAt = time.Unix(0, 0)
	data.IsDel = globalKey.DelStateNo
	qOperationArticleCommentReplyIdKey := fmt.Sprintf("%s%v", cacheQOperationArticleCommentReplyIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, articleCommentReplyRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.Id, data.ArticleId, data.CreatorId, data.CreatorName, data.CommentId, data.AtUserId, data.AtUserName, data.Content, data.Visibility, data.LikeCount, data.DislikeCount, data.Score, data.Location, data.DeletedAt, data.IsDel, data.Version)
		}
		return conn.ExecCtx(ctx, query, data.Id, data.ArticleId, data.CreatorId, data.CreatorName, data.CommentId, data.AtUserId, data.AtUserName, data.Content, data.Visibility, data.LikeCount, data.DislikeCount, data.Score, data.Location, data.DeletedAt, data.IsDel, data.Version)
	}, qOperationArticleCommentReplyIdKey)
}

func (m *defaultArticleCommentReplyModel) FindOne(ctx context.Context, id uint64) (*ArticleCommentReply, error) {
	qOperationArticleCommentReplyIdKey := fmt.Sprintf("%s%v", cacheQOperationArticleCommentReplyIdPrefix, id)
	var resp ArticleCommentReply
	err := m.QueryRowCtx(ctx, &resp, qOperationArticleCommentReplyIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? and is_del = ? limit 1", articleCommentReplyRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id, globalKey.DelStateNo)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultArticleCommentReplyModel) Update(ctx context.Context, session sqlx.Session, data *ArticleCommentReply) (sql.Result, error) {
	qOperationArticleCommentReplyIdKey := fmt.Sprintf("%s%v", cacheQOperationArticleCommentReplyIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, articleCommentReplyRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.ArticleId, data.CreatorId, data.CreatorName, data.CommentId, data.AtUserId, data.AtUserName, data.Content, data.Visibility, data.LikeCount, data.DislikeCount, data.Score, data.Location, data.DeletedAt, data.IsDel, data.Version, data.Id)
		}
		return conn.ExecCtx(ctx, query, data.ArticleId, data.CreatorId, data.CreatorName, data.CommentId, data.AtUserId, data.AtUserName, data.Content, data.Visibility, data.LikeCount, data.DislikeCount, data.Score, data.Location, data.DeletedAt, data.IsDel, data.Version, data.Id)
	}, qOperationArticleCommentReplyIdKey)
}

func (m *defaultArticleCommentReplyModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, data *ArticleCommentReply) error {

	oldVersion := data.Version
	data.Version += 1

	var sqlResult sql.Result
	var err error

	qOperationArticleCommentReplyIdKey := fmt.Sprintf("%s%v", cacheQOperationArticleCommentReplyIdPrefix, data.Id)
	sqlResult, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ? and version = ? ", m.table, articleCommentReplyRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.ArticleId, data.CreatorId, data.CreatorName, data.CommentId, data.AtUserId, data.AtUserName, data.Content, data.Visibility, data.LikeCount, data.DislikeCount, data.Score, data.Location, data.DeletedAt, data.IsDel, data.Version, data.Id, oldVersion)
		}
		return conn.ExecCtx(ctx, query, data.ArticleId, data.CreatorId, data.CreatorName, data.CommentId, data.AtUserId, data.AtUserName, data.Content, data.Visibility, data.LikeCount, data.DislikeCount, data.Score, data.Location, data.DeletedAt, data.IsDel, data.Version, data.Id, oldVersion)
	}, qOperationArticleCommentReplyIdKey)
	if err != nil {
		return err
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return ErrNoRowsUpdate
	}

	return nil
}

func (m *defaultArticleCommentReplyModel) DeleteSoft(ctx context.Context, session sqlx.Session, data *ArticleCommentReply) error {
	data.IsDel = globalKey.DelStateYes
	data.DeletedAt = time.Now()
	if err := m.UpdateWithVersion(ctx, session, data); err != nil {
		return errors.Wrapf(errors.New("delete soft failed "), "ArticleCommentReplyModel delete err : %+v", err)
	}
	return nil
}

func (m *defaultArticleCommentReplyModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.Where("is_del = ?", globalKey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultArticleCommentReplyModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.Where("is_del = ?", globalKey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultArticleCommentReplyModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*ArticleCommentReply, error) {

	builder = builder.Columns(articleCommentReplyRows)

	if orderBy == "" {
		builder = builder.OrderBy("created_at DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.Where("is_del = ?", globalKey.DelStateNo).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ArticleCommentReply
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultArticleCommentReplyModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ArticleCommentReply, error) {

	builder = builder.Columns(articleCommentReplyRows)

	if orderBy == "" {
		builder = builder.OrderBy("created_at DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("is_del = ?", globalKey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ArticleCommentReply
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultArticleCommentReplyModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ArticleCommentReply, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(articleCommentReplyRows)

	if orderBy == "" {
		builder = builder.OrderBy("created_at DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("is_del = ?", globalKey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*ArticleCommentReply
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultArticleCommentReplyModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*ArticleCommentReply, error) {

	builder = builder.Columns(articleCommentReplyRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.Where("is_del = ?", globalKey.DelStateNo).OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ArticleCommentReply
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultArticleCommentReplyModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*ArticleCommentReply, error) {

	builder = builder.Columns(articleCommentReplyRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.Where("is_del = ?", globalKey.DelStateNo).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ArticleCommentReply
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultArticleCommentReplyModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultArticleCommentReplyModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
func (m *defaultArticleCommentReplyModel) Delete(ctx context.Context, session sqlx.Session, id uint64) error {
	qOperationArticleCommentReplyIdKey := fmt.Sprintf("%s%v", cacheQOperationArticleCommentReplyIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, qOperationArticleCommentReplyIdKey)
	return err
}
func (m *defaultArticleCommentReplyModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheQOperationArticleCommentReplyIdPrefix, primary)
}
func (m *defaultArticleCommentReplyModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? and is_del = ? limit 1", articleCommentReplyRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary, globalKey.DelStateNo)
}

func (m *defaultArticleCommentReplyModel) tableName() string {
	return m.table
}
