// Code generated by goctl. DO NOT EDIT!

package notification

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"time"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"qinglv-backend/common/globalKey"
)

var (
	followNotifyFieldNames          = builder.RawFieldNames(&FollowNotify{})
	followNotifyRows                = strings.Join(followNotifyFieldNames, ",")
	followNotifyRowsExpectAutoSet   = strings.Join(stringx.Remove(followNotifyFieldNames, "`created_at`", "`updated_at`"), ",")
	followNotifyRowsWithPlaceHolder = strings.Join(stringx.Remove(followNotifyFieldNames, "`id`", "`created_at`", "`updated_at`"), "=?,") + "=?"
)

type (
	followNotifyModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *FollowNotify) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*FollowNotify, error)
		Update(ctx context.Context, session sqlx.Session, data *FollowNotify) (sql.Result, error)
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *FollowNotify) error
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		DeleteSoft(ctx context.Context, session sqlx.Session, data *FollowNotify) error
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*FollowNotify, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*FollowNotify, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*FollowNotify, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*FollowNotify, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*FollowNotify, error)
		Delete(ctx context.Context, session sqlx.Session, id uint64) error
	}

	defaultFollowNotifyModel struct {
		conn  sqlx.SqlConn
		table string
	}

	FollowNotify struct {
		Id             uint64    `db:"id"`               // 消息通知Id
		SenderUserId   uint64    `db:"sender_user_id"`   // 发送方用户id
		ReceiverUserId uint64    `db:"receiver_user_id"` // 接收方用户id
		IsRead         uint64    `db:"is_read"`          // 是否已读：0否，1是
		CreatedAt      time.Time `db:"created_at"`       // 创建时间
		UpdatedAt      time.Time `db:"updated_at"`       // 修改时间
		DeletedAt      time.Time `db:"deleted_at"`       // 删除时间
		IsDel          int64     `db:"is_del"`
		Version        int64     `db:"version"` // 版本号
	}
)

func newFollowNotifyModel(conn sqlx.SqlConn) *defaultFollowNotifyModel {
	return &defaultFollowNotifyModel{
		conn:  conn,
		table: "`follow_notify`",
	}
}

func (m *defaultFollowNotifyModel) Insert(ctx context.Context, session sqlx.Session, data *FollowNotify) (sql.Result, error) {
	data.DeletedAt = time.Unix(0, 0)
	data.IsDel = globalKey.DelStateNo

	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, followNotifyRowsExpectAutoSet)
	if session != nil {
		return session.ExecCtx(ctx, query, data.Id, data.SenderUserId, data.ReceiverUserId, data.IsRead, data.DeletedAt, data.IsDel, data.Version)
	}
	return m.conn.ExecCtx(ctx, query, data.Id, data.SenderUserId, data.ReceiverUserId, data.IsRead, data.DeletedAt, data.IsDel, data.Version)
}

func (m *defaultFollowNotifyModel) FindOne(ctx context.Context, id uint64) (*FollowNotify, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ?  and is_del = ? limit 1", followNotifyRows, m.table)
	var resp FollowNotify
	err := m.conn.QueryRowCtx(ctx, &resp, query, id, globalKey.DelStateNo)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFollowNotifyModel) Update(ctx context.Context, session sqlx.Session, data *FollowNotify) (sql.Result, error) {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, followNotifyRowsWithPlaceHolder)
	if session != nil {
		return session.ExecCtx(ctx, query, data.SenderUserId, data.ReceiverUserId, data.IsRead, data.DeletedAt, data.IsDel, data.Version, data.Id)
	}
	return m.conn.ExecCtx(ctx, query, data.SenderUserId, data.ReceiverUserId, data.IsRead, data.DeletedAt, data.IsDel, data.Version, data.Id)
}

func (m *defaultFollowNotifyModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, data *FollowNotify) error {

	oldVersion := data.Version
	data.Version += 1

	var sqlResult sql.Result
	var err error

	query := fmt.Sprintf("update %s set %s where `id` = ? and version = ? ", m.table, followNotifyRowsWithPlaceHolder)
	if session != nil {
		sqlResult, err = session.ExecCtx(ctx, query, data.SenderUserId, data.ReceiverUserId, data.IsRead, data.DeletedAt, data.IsDel, data.Version, data.Id, oldVersion)
	} else {
		sqlResult, err = m.conn.ExecCtx(ctx, query, data.SenderUserId, data.ReceiverUserId, data.IsRead, data.DeletedAt, data.IsDel, data.Version, data.Id, oldVersion)
	}

	if err != nil {
		return err
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return ErrNoRowsUpdate
	}

	return nil
}

func (m *defaultFollowNotifyModel) DeleteSoft(ctx context.Context, session sqlx.Session, data *FollowNotify) error {
	data.IsDel = globalKey.DelStateYes
	data.DeletedAt = time.Now()
	if err := m.UpdateWithVersion(ctx, session, data); err != nil {
		return errors.Wrapf(errors.New("delete soft failed "), "FollowNotifyModel delete err : %+v", err)
	}
	return nil
}

func (m *defaultFollowNotifyModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.Where("is_del = ?", globalKey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultFollowNotifyModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.Where("is_del = ?", globalKey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultFollowNotifyModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*FollowNotify, error) {

	builder = builder.Columns(followNotifyRows)

	if orderBy == "" {
		builder = builder.OrderBy("created_at DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.Where("is_del = ?", globalKey.DelStateNo).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*FollowNotify

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultFollowNotifyModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*FollowNotify, error) {

	builder = builder.Columns(followNotifyRows)

	if orderBy == "" {
		builder = builder.OrderBy("created_at DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("is_del = ?", globalKey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*FollowNotify

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultFollowNotifyModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*FollowNotify, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(followNotifyRows)

	if orderBy == "" {
		builder = builder.OrderBy("created_at DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("is_del = ?", globalKey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*FollowNotify

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultFollowNotifyModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*FollowNotify, error) {

	builder = builder.Columns(followNotifyRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.Where("is_del = ?", globalKey.DelStateNo).OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*FollowNotify

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultFollowNotifyModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*FollowNotify, error) {

	builder = builder.Columns(followNotifyRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.Where("is_del = ?", globalKey.DelStateNo).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*FollowNotify

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultFollowNotifyModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.conn.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultFollowNotifyModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
func (m *defaultFollowNotifyModel) Delete(ctx context.Context, session sqlx.Session, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	if session != nil {
		_, err := session.ExecCtx(ctx, query, id)
		return err
	}
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultFollowNotifyModel) tableName() string {
	return m.table
}
