// Code generated by goctl. DO NOT EDIT!

package post

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"time"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"qinglv-backend/common/globalKey"
)

var (
	postFeedFieldNames          = builder.RawFieldNames(&PostFeed{})
	postFeedRows                = strings.Join(postFeedFieldNames, ",")
	postFeedRowsExpectAutoSet   = strings.Join(stringx.Remove(postFeedFieldNames, "`created_at`", "`updated_at`"), ",")
	postFeedRowsWithPlaceHolder = strings.Join(stringx.Remove(postFeedFieldNames, "`id`", "`created_at`", "`updated_at`"), "=?,") + "=?"

	cacheQContentPostFeedIdPrefix           = "cache:qContent:postFeed:id:"
	cacheQContentPostFeedPostIdUserIdPrefix = "cache:qContent:postFeed:postId:userId:"
)

type (
	postFeedModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *PostFeed) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*PostFeed, error)
		FindOneByPostIdUserId(ctx context.Context, postId uint64, userId uint64) (*PostFeed, error)
		Update(ctx context.Context, session sqlx.Session, data *PostFeed) (sql.Result, error)
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *PostFeed) error
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		DeleteSoft(ctx context.Context, session sqlx.Session, data *PostFeed) error
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*PostFeed, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*PostFeed, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*PostFeed, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*PostFeed, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*PostFeed, error)
		Delete(ctx context.Context, session sqlx.Session, id uint64) error
	}

	defaultPostFeedModel struct {
		sqlc.CachedConn
		table string
	}

	PostFeed struct {
		Id        uint64    `db:"id"`         // 主键id
		UserId    uint64    `db:"user_id"`    // 用户id
		AuthorId  uint64    `db:"author_id"`  // 作者id
		PostId    uint64    `db:"post_id"`    // 帖子id
		CreatedAt time.Time `db:"created_at"` // 创建时间
		UpdatedAt time.Time `db:"updated_at"` // 修改时间
		DeletedAt time.Time `db:"deleted_at"` // 删除时间
		IsDel     int64     `db:"is_del"`
		Version   int64     `db:"version"` // 版本号
	}
)

func newPostFeedModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultPostFeedModel {
	return &defaultPostFeedModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`post_feed`",
	}
}

func (m *defaultPostFeedModel) Insert(ctx context.Context, session sqlx.Session, data *PostFeed) (sql.Result, error) {
	data.DeletedAt = time.Unix(0, 0)
	data.IsDel = globalKey.DelStateNo
	qContentPostFeedIdKey := fmt.Sprintf("%s%v", cacheQContentPostFeedIdPrefix, data.Id)
	qContentPostFeedPostIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheQContentPostFeedPostIdUserIdPrefix, data.PostId, data.UserId)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, postFeedRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.Id, data.UserId, data.AuthorId, data.PostId, data.DeletedAt, data.IsDel, data.Version)
		}
		return conn.ExecCtx(ctx, query, data.Id, data.UserId, data.AuthorId, data.PostId, data.DeletedAt, data.IsDel, data.Version)
	}, qContentPostFeedIdKey, qContentPostFeedPostIdUserIdKey)
}

func (m *defaultPostFeedModel) FindOne(ctx context.Context, id uint64) (*PostFeed, error) {
	qContentPostFeedIdKey := fmt.Sprintf("%s%v", cacheQContentPostFeedIdPrefix, id)
	var resp PostFeed
	err := m.QueryRowCtx(ctx, &resp, qContentPostFeedIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? and is_del = ? limit 1", postFeedRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id, globalKey.DelStateNo)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPostFeedModel) FindOneByPostIdUserId(ctx context.Context, postId uint64, userId uint64) (*PostFeed, error) {
	qContentPostFeedPostIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheQContentPostFeedPostIdUserIdPrefix, postId, userId)
	var resp PostFeed
	err := m.QueryRowIndexCtx(ctx, &resp, qContentPostFeedPostIdUserIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `post_id` = ? and `user_id` = ? and is_del = ? limit 1", postFeedRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, postId, userId, globalKey.DelStateNo); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPostFeedModel) Update(ctx context.Context, session sqlx.Session, newData *PostFeed) (sql.Result, error) {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return nil, err
	}
	qContentPostFeedIdKey := fmt.Sprintf("%s%v", cacheQContentPostFeedIdPrefix, data.Id)
	qContentPostFeedPostIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheQContentPostFeedPostIdUserIdPrefix, data.PostId, data.UserId)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, postFeedRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, newData.UserId, newData.AuthorId, newData.PostId, newData.DeletedAt, newData.IsDel, newData.Version, newData.Id)
		}
		return conn.ExecCtx(ctx, query, newData.UserId, newData.AuthorId, newData.PostId, newData.DeletedAt, newData.IsDel, newData.Version, newData.Id)
	}, qContentPostFeedIdKey, qContentPostFeedPostIdUserIdKey)
}

func (m *defaultPostFeedModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, newData *PostFeed) error {

	oldVersion := newData.Version
	newData.Version += 1

	var sqlResult sql.Result
	var err error

	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}
	qContentPostFeedIdKey := fmt.Sprintf("%s%v", cacheQContentPostFeedIdPrefix, data.Id)
	qContentPostFeedPostIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheQContentPostFeedPostIdUserIdPrefix, data.PostId, data.UserId)
	sqlResult, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ? and version = ? ", m.table, postFeedRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, newData.UserId, newData.AuthorId, newData.PostId, newData.DeletedAt, newData.IsDel, newData.Version, newData.Id, oldVersion)
		}
		return conn.ExecCtx(ctx, query, newData.UserId, newData.AuthorId, newData.PostId, newData.DeletedAt, newData.IsDel, newData.Version, newData.Id, oldVersion)
	}, qContentPostFeedIdKey, qContentPostFeedPostIdUserIdKey)
	if err != nil {
		return err
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return ErrNoRowsUpdate
	}

	return nil
}

func (m *defaultPostFeedModel) DeleteSoft(ctx context.Context, session sqlx.Session, data *PostFeed) error {
	data.IsDel = globalKey.DelStateYes
	data.DeletedAt = time.Now()
	if err := m.UpdateWithVersion(ctx, session, data); err != nil {
		return errors.Wrapf(errors.New("delete soft failed "), "PostFeedModel delete err : %+v", err)
	}
	return nil
}

func (m *defaultPostFeedModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.Where("is_del = ?", globalKey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultPostFeedModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.Where("is_del = ?", globalKey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultPostFeedModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*PostFeed, error) {

	builder = builder.Columns(postFeedRows)

	if orderBy == "" {
		builder = builder.OrderBy("created_at DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.Where("is_del = ?", globalKey.DelStateNo).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*PostFeed
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultPostFeedModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*PostFeed, error) {

	builder = builder.Columns(postFeedRows)

	if orderBy == "" {
		builder = builder.OrderBy("created_at DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("is_del = ?", globalKey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*PostFeed
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultPostFeedModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*PostFeed, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(postFeedRows)

	if orderBy == "" {
		builder = builder.OrderBy("created_at DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("is_del = ?", globalKey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*PostFeed
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultPostFeedModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*PostFeed, error) {

	builder = builder.Columns(postFeedRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.Where("is_del = ?", globalKey.DelStateNo).OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*PostFeed
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultPostFeedModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*PostFeed, error) {

	builder = builder.Columns(postFeedRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.Where("is_del = ?", globalKey.DelStateNo).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*PostFeed
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultPostFeedModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultPostFeedModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
func (m *defaultPostFeedModel) Delete(ctx context.Context, session sqlx.Session, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	qContentPostFeedIdKey := fmt.Sprintf("%s%v", cacheQContentPostFeedIdPrefix, id)
	qContentPostFeedPostIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheQContentPostFeedPostIdUserIdPrefix, data.PostId, data.UserId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, qContentPostFeedIdKey, qContentPostFeedPostIdUserIdKey)
	return err
}
func (m *defaultPostFeedModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheQContentPostFeedIdPrefix, primary)
}
func (m *defaultPostFeedModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? and is_del = ? limit 1", postFeedRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary, globalKey.DelStateNo)
}

func (m *defaultPostFeedModel) tableName() string {
	return m.table
}
