syntax = "proto3";

package content;
option go_package="./content";

message OkResp {
    string pong = 1;
}

//==========================Topic==========================
message TopicItem {
    uint64 id  = 1;
    uint64 creatorId = 2;
   	string name = 3; 
	string bg = 4;          
	string description = 5;
    uint64 quoteCount = 6; 
    uint64 createdAt = 7;
    uint64 updatedAt = 8;
    int32 type = 9;
    double score = 10;
}
message AddTopicReq {
    uint64 id  = 1;
    uint64 creatorId = 2;
   	string name = 3; 
	string bg = 4;          
	string description = 5;
    uint64 quoteCount = 6;
    int32 type = 7;
    double score = 8;
}
message DeleteTopicReq {
    uint64 id = 1;
}
message UpdateTopicReq {
    uint64 id  = 1;
   	string name = 3; 
	string bg = 4;          
	string description = 5;
    uint64 quoteCount = 6;
    int32 type = 7;
    double score = 8;
}
message GetTopicByIdReq {
    uint64 id = 1;
}
message GetTopicByIdResp {
    TopicItem topic  = 1;
}
message GetTopicByNameReq {
    string name = 1;
}
message GetTopicByNameResp {
    TopicItem topic  = 1;
}
message GetTopicListReq {
    string name = 1;
    uint64 creatorId = 2;
    uint64 quoteCount = 3;
    uint64 pageNum = 4;
    uint64 pageSize = 5;
    int32 type = 6;
    string sort = 7;
}
message GetTopicListResp {
    repeated TopicItem data = 1;
    uint64 total = 2;
}
service TopicClass {
    // group: topic
    rpc AddTopic(AddTopicReq) returns(OkResp);
    // group: topic
    rpc DeleteTopic(DeleteTopicReq) returns(OkResp);
    // group: topic
    rpc UpdateTopic(UpdateTopicReq) returns(OkResp);
    // group: topic
    rpc GetTopicById(GetTopicByIdReq) returns(GetTopicByIdResp);
    // group: topic
    rpc GetTopicByName(GetTopicByNameReq) returns(GetTopicByNameResp);
    // group: topic
    rpc GetTopicList(GetTopicListReq) returns(GetTopicListResp);
}


//==========================Category==========================
message CategoryItem {
    uint64 id  = 1;
    uint64 creatorId = 2;
   	string name = 3; 
	string image = 4;          
	string description = 5;
    uint64 quoteCount = 6; 
    uint64 createdAt = 7;
    uint64 updatedAt = 8;
}
message AddCategoryReq {
    uint64 id  = 1;
    uint64 creatorId = 2;
   	string name = 3; 
	string image = 4;          
	string description = 5;
    uint64 quoteCount = 6;
}
message DeleteCategoryReq {
    uint64 id = 1;
}
message UpdateCategoryReq {
    uint64 id  = 1;
   	string name = 3; 
	string image = 4;          
	string description = 5;
    uint64 quoteCount = 6;
}
message GetCategoryDetailReq {
    uint64 id = 1;
}
message GetCategoryDetailResp {
    CategoryItem category  = 1;
}
message GetCategoryListReq {
    string name = 1;
    uint64 creatorId = 2;
    uint64 quoteCount = 3;
    uint64 pageNum = 4;
    uint64 pageSize = 5;
}
message GetCategoryListResp {
    repeated CategoryItem data = 1;
    uint64 total = 2;
}
service CategoryClass {
    // group: category
    rpc AddCategory(AddCategoryReq) returns(OkResp);
    // group: category
    rpc DeleteCategory(DeleteCategoryReq) returns(OkResp);
    // group: category
    rpc UpdateCategory(UpdateCategoryReq) returns(OkResp);
    // group: category
    rpc GetCategoryDetail(GetCategoryDetailReq) returns(GetCategoryDetailResp);
    // group: category
    rpc GetCategoryList(GetCategoryListReq) returns(GetCategoryListResp);
}

//==========================Post==========================
message PostItem {
    uint64 id  = 1;
    uint64 creatorId = 2;
    int32 status = 3;
    int32 visibility = 4;
    int32 isTop = 5;
    double score = 6;
    string location = 7;
    uint64 commentCount = 8;    
    uint64 collectionCount = 9;    
    uint64 likeCount = 10;    
    uint64 dislikeCount = 11;    
    uint64 shareCount = 12;    
    uint64 lastReplyTime = 13;
    uint64 createdAt = 14;
    uint64 updatedAt = 15;
}
message AddPostReq {
    uint64 id  = 1;
    uint64 creatorId = 2;
   	int32 status = 3; 
	int32 visibility = 4;          
	int32 isTop = 5;
    string location = 6;
}
message DeletePostReq {
    uint64 id = 1;
    uint64 postContentId = 2;
}
message UpdatePostReq {
    uint64 id  = 1;
    uint64 creatorId = 2;
   	int32 status = 3; 
	int32 visibility = 4;          
	int32 isTop = 5;
    string location = 6;
    double score = 7;
    uint64 commentCount = 8;    
    uint64 collectionCount = 9;    
    uint64 likeCount = 10;    
    uint64 dislikeCount = 11;    
    uint64 shareCount = 12;    
}
message GetPostDetailReq {
    uint64 id = 1;
}
message GetPostDetailResp {
    PostItem post  = 1;
}
message GetPostListReq {
    int32 status = 1;
    repeated int32 visibility = 2;
    int32 isTop = 3;
    double score = 4;
    string location = 5;
    string keyword = 6; 
    uint64 creatorId = 7;
    uint64 pageNum = 8;
    uint64 pageSize = 9;
    string sort = 10;
}
message GetPostListResp {
    repeated PostItem data = 1;
    uint64 total = 2;
}
service PostClass {
    rpc AddPost(AddPostReq) returns(OkResp);
    rpc DeletePost(DeletePostReq) returns(OkResp);
    rpc UpdatePost(UpdatePostReq) returns(OkResp);
    rpc GetPostDetail(GetPostDetailReq) returns(GetPostDetailResp);
    rpc GetPostList(GetPostListReq) returns(GetPostListResp);
    rpc AddPostContent(AddPostContentReq) returns(OkResp);
    rpc GetPostContentByPostId(GetPostContentDetailReq) returns(GetPostContentDetailResp);
}


//==========================PostContent==========================
message PostContentItem {
    uint64 id = 1;
    uint64 postId = 2;
    uint64 categoryId = 3;
    string topics = 4;
   	string content = 5; 
	repeated string images = 6;  
    uint64 creatorId = 7;
    uint64 createdAt = 8;
    uint64 updatedAt = 9;
}
message AddPostContentReq {
    uint64 id  = 1;
    uint64 creatorId = 2;
   	uint64 postId = 3; 
	uint64 categoryId = 4;          
	string topics = 5;
    string content = 6;
    repeated string images = 7;
}

message GetPostContentDetailReq {
    uint64 id = 1;
}
message GetPostContentDetailResp {
    PostContentItem postContent  = 1;
}
message GetPostContentListReq {
    string content = 1; 
    uint64 creatorId = 2;
    uint64 categoryId = 3;
    uint64 pageNum = 4;
    uint64 pageSize = 5;
}
message GetPostContentListResp {
    repeated PostContentItem data = 1;
    uint64 total = 2;
}

//==========================MediaFile==========================

message MediaFile {
    uint64 id = 1;
    uint64 creatorId = 2;
    uint64 fileSize = 3;
    int32 mediaType = 4;
    int32 bizType = 5;
    string content = 6;
    uint64 createdAt = 7;
    uint64 updatedAt = 8;
}
message AddMediaFileReq {
    uint64 id = 1;
    uint64 creatorId = 2;
    uint64 fileSize = 3;
    int32 mediaType = 4;
    int32 bizType = 5;
    string content = 6;
}
message DeleteMediaFileReq{
    uint64 id = 1;
}
message GetMediaFileByContentReq{
    string content = 1;
}
message GetMediaFileByContentResp {
    MediaFile file = 1;
}
message GetMediaFileListReq {
    string content = 1;
    uint64 creatorId = 3;
}
message GetMediaFileListResp {
    repeated MediaFile Data = 1;
    uint64 total = 2;
}

service MediaFileClass {
    // group: mediaFile
    rpc AddMediaFile(AddMediaFileReq) returns(OkResp);
    // group: mediaFile
    rpc DeleteMediaFile(DeleteMediaFileReq) returns(OkResp);
    // group: mediaFile
    rpc GetMediaFileByContent(GetMediaFileByContentReq) returns(GetMediaFileByContentResp);
    // group: mediaFile
    rpc GetMediaFileList(GetMediaFileListReq) returns(GetMediaFileListResp);
}

//==========================Tag==========================
message TagItem {
    uint64 id  = 1;
    uint64 creatorId = 2;
   	string name = 3; 
	string image = 4;          
	string description = 5;
    uint64 quoteCount = 6; 
    uint64 createdAt = 7;
    uint64 updatedAt = 8;
    int32 type = 9;
    string creatorName = 10;
}
message AddTagReq {
    uint64 id  = 1;
    uint64 creatorId = 2;
   	string name = 3; 
	string image = 4;          
	string description = 5;
    uint64 quoteCount = 6;
    int32 type = 7;
    string creatorName = 8;
}
message DeleteTagReq {
    uint64 id = 1;
}
message UpdateTagReq {
    uint64 id  = 1;
	string image = 2;          
	string description = 3;
    uint64 quoteCount = 4;
}
message GetTagByIdReq {
    uint64 id = 1;
}
message GetTagByIdResp {
    TagItem tag  = 1;
}
message GetTagByNameReq {
    string name = 1;
}
message GetTagByNameResp {
    TagItem tag  = 1;
}
message GetTagListReq {
    string name = 1;
    string creatorName = 2;
    uint64 quoteCount = 3;
    uint64 pageNum = 4;
    uint64 pageSize = 5;
    int32 type = 6;
    string sort = 7;
}
message GetTagListResp {
    repeated TagItem data = 1;
    uint64 total = 2;
}
service TagClass {
    rpc AddTag(AddTagReq) returns(OkResp);
    rpc DeleteTag(DeleteTagReq) returns(OkResp);
    rpc UpdateTag(UpdateTagReq) returns(OkResp);
    rpc GetTagById(GetTagByIdReq) returns(GetTagByIdResp);
    rpc GetTagByName(GetTagByNameReq) returns(GetTagByNameResp);
    rpc GetTagList(GetTagListReq) returns(GetTagListResp);
}

//==========================Article==========================
message ArticleItem {
    uint64 id  = 1;
    uint64 creatorId = 2;
    int32 status = 3;
    int32 visibility = 4;
    int32 isTop = 5;
    double score = 6;
    uint64 commentCount = 7;    
    uint64 collectionCount = 8;    
    uint64 likeCount = 9;    
    uint64 dislikeCount = 10;    
    uint64 shareCount = 11;    
    uint64 lastReplyTime = 12;
    uint64 createdAt = 13;
    uint64 updatedAt = 14;
    string creatorName = 15;
}
message AddArticleReq {
    uint64 id  = 1;
    uint64 creatorId = 2;
   	int32 status = 3; 
	int32 visibility = 4;          
	int32 isTop = 5;

    uint64 articleContentId  = 6;
    string title = 7;
    string introduction = 8;
    string coverImage = 9;
    string content = 10;
	uint64 categoryId = 11;
    string tags = 12;  
    string creatorName = 13;
}
message DeleteArticleReq {
    uint64 id = 1;
    uint64 ArticleContentId = 2;
}
message UpdateArticleReq {
    uint64 id  = 1;
    uint64 creatorId = 2;
   	int32 status = 3; 
	int32 visibility = 4;          
	int32 isTop = 5;
    double score = 6;
    uint64 commentCount = 7;    
    uint64 collectionCount = 8;    
    uint64 likeCount = 9;    
    uint64 dislikeCount = 10;    
    uint64 shareCount = 11;    
}
message GetArticleDetailReq {
    uint64 id = 1;
}
message GetArticleDetailResp {
    ArticleItem Article  = 1;
}
message GetArticleListReq {
    int32 status = 1;
    repeated int32 visibility = 2;
    int32 isTop = 3;
    double score = 4;
    uint64 creatorId = 5;
    string keyword = 6; 
    string creatorName = 7;
    uint64 pageNum = 8;
    uint64 pageSize = 9;
    string sort = 10;
}
message GetArticleListResp {
    repeated ArticleItem data = 1;
    uint64 total = 2;
}

message ArticleContentItem {
    uint64 id = 1;
    uint64 articleId = 2;
    uint64 categoryId = 3;
    string tags = 4;
    string title = 5;
    string introduction = 6;
    string coverImage = 7;
   	string content = 8; 
    uint64 creatorId = 9;
    uint64 createdAt = 10;
    uint64 updatedAt = 11;
    string creatorName = 12;
}
message UpdateArticleContentReq {
    uint64 id  = 1;
    string title = 2;
    string introduction = 3;
    string coverImage = 4;
    string content = 5;
    uint64 creatorId = 6;
   	uint64 articleId = 7; 
	uint64 categoryId = 8;
    string tags = 9;          
}

message GetArticleContentDetailReq {
    uint64 id = 1;
}
message GetArticleContentDetailResp {
    ArticleContentItem articleContent  = 1;
}
message GetArticleContentListReq {
    string content = 1; 
    uint64 creatorId = 2;
    uint64 categoryId = 3;
    uint64 pageNum = 4;
    uint64 pageSize = 5;
}
message GetArticleContentListResp {
    repeated ArticleContentItem data = 1;
    uint64 total = 2;
}
service ArticleClass {
    rpc AddArticle(AddArticleReq) returns(OkResp);
    rpc DeleteArticle(DeleteArticleReq) returns(OkResp);
    rpc UpdateArticle(UpdateArticleReq) returns(OkResp);
    rpc GetArticleDetail(GetArticleDetailReq) returns(GetArticleDetailResp);
    rpc GetArticleList(GetArticleListReq) returns(GetArticleListResp);
    rpc UpdateArticleContent(UpdateArticleContentReq) returns(OkResp);
    rpc GetArticleContentByArticleId(GetArticleContentDetailReq) returns(GetArticleContentDetailResp);
}