// Code generated by goctl. DO NOT EDIT.
// Source: content.proto

package mediafileclass

import (
	"context"

	"qinglv-backend/app/content/rpc/content"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddArticleFeedReq           = content.AddArticleFeedReq
	AddArticleReq               = content.AddArticleReq
	AddCategoryReq              = content.AddCategoryReq
	AddMediaFileReq             = content.AddMediaFileReq
	AddPostContentReq           = content.AddPostContentReq
	AddPostFeedReq              = content.AddPostFeedReq
	AddPostReq                  = content.AddPostReq
	AddTagReq                   = content.AddTagReq
	AddTopicReq                 = content.AddTopicReq
	ArticleContentItem          = content.ArticleContentItem
	ArticleFeedItem             = content.ArticleFeedItem
	ArticleItem                 = content.ArticleItem
	CategoryItem                = content.CategoryItem
	DeleteArticleFeedByIdsReq   = content.DeleteArticleFeedByIdsReq
	DeleteArticleReq            = content.DeleteArticleReq
	DeleteCategoryReq           = content.DeleteCategoryReq
	DeleteMediaFileReq          = content.DeleteMediaFileReq
	DeletePostFeedByIdsReq      = content.DeletePostFeedByIdsReq
	DeletePostReq               = content.DeletePostReq
	DeleteTagReq                = content.DeleteTagReq
	DeleteTopicReq              = content.DeleteTopicReq
	GetArticleContentDetailReq  = content.GetArticleContentDetailReq
	GetArticleContentDetailResp = content.GetArticleContentDetailResp
	GetArticleContentListReq    = content.GetArticleContentListReq
	GetArticleContentListResp   = content.GetArticleContentListResp
	GetArticleDetailReq         = content.GetArticleDetailReq
	GetArticleDetailResp        = content.GetArticleDetailResp
	GetArticleFeedListReq       = content.GetArticleFeedListReq
	GetArticleFeedListResp      = content.GetArticleFeedListResp
	GetArticleListReq           = content.GetArticleListReq
	GetArticleListResp          = content.GetArticleListResp
	GetCategoryDetailReq        = content.GetCategoryDetailReq
	GetCategoryDetailResp       = content.GetCategoryDetailResp
	GetCategoryListReq          = content.GetCategoryListReq
	GetCategoryListResp         = content.GetCategoryListResp
	GetMediaFileByContentReq    = content.GetMediaFileByContentReq
	GetMediaFileByContentResp   = content.GetMediaFileByContentResp
	GetMediaFileListReq         = content.GetMediaFileListReq
	GetMediaFileListResp        = content.GetMediaFileListResp
	GetPostContentDetailReq     = content.GetPostContentDetailReq
	GetPostContentDetailResp    = content.GetPostContentDetailResp
	GetPostContentListReq       = content.GetPostContentListReq
	GetPostContentListResp      = content.GetPostContentListResp
	GetPostDetailReq            = content.GetPostDetailReq
	GetPostDetailResp           = content.GetPostDetailResp
	GetPostFeedListReq          = content.GetPostFeedListReq
	GetPostFeedListResp         = content.GetPostFeedListResp
	GetPostListReq              = content.GetPostListReq
	GetPostListResp             = content.GetPostListResp
	GetTagByIdReq               = content.GetTagByIdReq
	GetTagByIdResp              = content.GetTagByIdResp
	GetTagByNameReq             = content.GetTagByNameReq
	GetTagByNameResp            = content.GetTagByNameResp
	GetTagListReq               = content.GetTagListReq
	GetTagListResp              = content.GetTagListResp
	GetTopicByIdReq             = content.GetTopicByIdReq
	GetTopicByIdResp            = content.GetTopicByIdResp
	GetTopicByNameReq           = content.GetTopicByNameReq
	GetTopicByNameResp          = content.GetTopicByNameResp
	GetTopicListReq             = content.GetTopicListReq
	GetTopicListResp            = content.GetTopicListResp
	MediaFile                   = content.MediaFile
	OkResp                      = content.OkResp
	PostContentItem             = content.PostContentItem
	PostFeedItem                = content.PostFeedItem
	PostItem                    = content.PostItem
	ScanArticleByUserIdReq      = content.ScanArticleByUserIdReq
	ScanPostByUserReq           = content.ScanPostByUserReq
	TagItem                     = content.TagItem
	TopicItem                   = content.TopicItem
	UpdateArticleContentReq     = content.UpdateArticleContentReq
	UpdateArticleReq            = content.UpdateArticleReq
	UpdateCategoryReq           = content.UpdateCategoryReq
	UpdatePostReq               = content.UpdatePostReq
	UpdateTagReq                = content.UpdateTagReq
	UpdateTopicReq              = content.UpdateTopicReq

	MediaFileClass interface {
		AddMediaFile(ctx context.Context, in *AddMediaFileReq, opts ...grpc.CallOption) (*OkResp, error)
		DeleteMediaFile(ctx context.Context, in *DeleteMediaFileReq, opts ...grpc.CallOption) (*OkResp, error)
		GetMediaFileByContent(ctx context.Context, in *GetMediaFileByContentReq, opts ...grpc.CallOption) (*GetMediaFileByContentResp, error)
		GetMediaFileList(ctx context.Context, in *GetMediaFileListReq, opts ...grpc.CallOption) (*GetMediaFileListResp, error)
	}

	defaultMediaFileClass struct {
		cli zrpc.Client
	}
)

func NewMediaFileClass(cli zrpc.Client) MediaFileClass {
	return &defaultMediaFileClass{
		cli: cli,
	}
}

func (m *defaultMediaFileClass) AddMediaFile(ctx context.Context, in *AddMediaFileReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := content.NewMediaFileClassClient(m.cli.Conn())
	return client.AddMediaFile(ctx, in, opts...)
}

func (m *defaultMediaFileClass) DeleteMediaFile(ctx context.Context, in *DeleteMediaFileReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := content.NewMediaFileClassClient(m.cli.Conn())
	return client.DeleteMediaFile(ctx, in, opts...)
}

func (m *defaultMediaFileClass) GetMediaFileByContent(ctx context.Context, in *GetMediaFileByContentReq, opts ...grpc.CallOption) (*GetMediaFileByContentResp, error) {
	client := content.NewMediaFileClassClient(m.cli.Conn())
	return client.GetMediaFileByContent(ctx, in, opts...)
}

func (m *defaultMediaFileClass) GetMediaFileList(ctx context.Context, in *GetMediaFileListReq, opts ...grpc.CallOption) (*GetMediaFileListResp, error) {
	client := content.NewMediaFileClassClient(m.cli.Conn())
	return client.GetMediaFileList(ctx, in, opts...)
}
