// Code generated by goctl. DO NOT EDIT!

package collection_group

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"time"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"qinglv-backend/common/globalKey"
)

var (
	collectionGroupFieldNames          = builder.RawFieldNames(&CollectionGroup{})
	collectionGroupRows                = strings.Join(collectionGroupFieldNames, ",")
	collectionGroupRowsExpectAutoSet   = strings.Join(stringx.Remove(collectionGroupFieldNames, "`created_at`", "`updated_at`"), ",")
	collectionGroupRowsWithPlaceHolder = strings.Join(stringx.Remove(collectionGroupFieldNames, "`id`", "`created_at`", "`updated_at`"), "=?,") + "=?"

	cacheQOperationCollectionGroupIdPrefix = "cache:qOperation:collectionGroup:id:"
)

type (
	collectionGroupModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *CollectionGroup) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*CollectionGroup, error)
		Update(ctx context.Context, session sqlx.Session, data *CollectionGroup) (sql.Result, error)
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *CollectionGroup) error
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		DeleteSoft(ctx context.Context, session sqlx.Session, data *CollectionGroup) error
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*CollectionGroup, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*CollectionGroup, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*CollectionGroup, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*CollectionGroup, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*CollectionGroup, error)
		Delete(ctx context.Context, session sqlx.Session, id uint64) error
	}

	defaultCollectionGroupModel struct {
		sqlc.CachedConn
		table string
	}

	CollectionGroup struct {
		Id         uint64    `db:"id"`
		Name       string    `db:"name"`       // 收藏分组名称
		BizType    uint64    `db:"biz_type"`   // 1帖子，2文章，3视频
		Count      uint64    `db:"count"`      // 数量
		Visibility uint64    `db:"visibility"` // 是否公开: 1是，2否
		CreatorId  uint64    `db:"creator_id"` // 创建人
		CreatedAt  time.Time `db:"created_at"` // 创建时间
		UpdatedAt  time.Time `db:"updated_at"` // 修改时间
		DeletedAt  time.Time `db:"deleted_at"` // 删除时间
		IsDel      int64     `db:"is_del"`
		Version    int64     `db:"version"` // 版本号
	}
)

func newCollectionGroupModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultCollectionGroupModel {
	return &defaultCollectionGroupModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`collection_group`",
	}
}

func (m *defaultCollectionGroupModel) Insert(ctx context.Context, session sqlx.Session, data *CollectionGroup) (sql.Result, error) {
	data.DeletedAt = time.Unix(0, 0)
	data.IsDel = globalKey.DelStateNo
	qOperationCollectionGroupIdKey := fmt.Sprintf("%s%v", cacheQOperationCollectionGroupIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, collectionGroupRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.Id, data.Name, data.BizType, data.Count, data.Visibility, data.CreatorId, data.DeletedAt, data.IsDel, data.Version)
		}
		return conn.ExecCtx(ctx, query, data.Id, data.Name, data.BizType, data.Count, data.Visibility, data.CreatorId, data.DeletedAt, data.IsDel, data.Version)
	}, qOperationCollectionGroupIdKey)
}

func (m *defaultCollectionGroupModel) FindOne(ctx context.Context, id uint64) (*CollectionGroup, error) {
	qOperationCollectionGroupIdKey := fmt.Sprintf("%s%v", cacheQOperationCollectionGroupIdPrefix, id)
	var resp CollectionGroup
	err := m.QueryRowCtx(ctx, &resp, qOperationCollectionGroupIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? and is_del = ? limit 1", collectionGroupRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id, globalKey.DelStateNo)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCollectionGroupModel) Update(ctx context.Context, session sqlx.Session, data *CollectionGroup) (sql.Result, error) {
	qOperationCollectionGroupIdKey := fmt.Sprintf("%s%v", cacheQOperationCollectionGroupIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, collectionGroupRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.Name, data.BizType, data.Count, data.Visibility, data.CreatorId, data.DeletedAt, data.IsDel, data.Version, data.Id)
		}
		return conn.ExecCtx(ctx, query, data.Name, data.BizType, data.Count, data.Visibility, data.CreatorId, data.DeletedAt, data.IsDel, data.Version, data.Id)
	}, qOperationCollectionGroupIdKey)
}

func (m *defaultCollectionGroupModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, data *CollectionGroup) error {

	oldVersion := data.Version
	data.Version += 1

	var sqlResult sql.Result
	var err error

	qOperationCollectionGroupIdKey := fmt.Sprintf("%s%v", cacheQOperationCollectionGroupIdPrefix, data.Id)
	sqlResult, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ? and version = ? ", m.table, collectionGroupRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.Name, data.BizType, data.Count, data.Visibility, data.CreatorId, data.DeletedAt, data.IsDel, data.Version, data.Id, oldVersion)
		}
		return conn.ExecCtx(ctx, query, data.Name, data.BizType, data.Count, data.Visibility, data.CreatorId, data.DeletedAt, data.IsDel, data.Version, data.Id, oldVersion)
	}, qOperationCollectionGroupIdKey)
	if err != nil {
		return err
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return ErrNoRowsUpdate
	}

	return nil
}

func (m *defaultCollectionGroupModel) DeleteSoft(ctx context.Context, session sqlx.Session, data *CollectionGroup) error {
	data.IsDel = globalKey.DelStateYes
	data.DeletedAt = time.Now()
	if err := m.UpdateWithVersion(ctx, session, data); err != nil {
		return errors.Wrapf(errors.New("delete soft failed "), "CollectionGroupModel delete err : %+v", err)
	}
	return nil
}

func (m *defaultCollectionGroupModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.Where("is_del = ?", globalKey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultCollectionGroupModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.Where("is_del = ?", globalKey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultCollectionGroupModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*CollectionGroup, error) {

	builder = builder.Columns(collectionGroupRows)

	if orderBy == "" {
		builder = builder.OrderBy("created_at DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.Where("is_del = ?", globalKey.DelStateNo).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*CollectionGroup
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultCollectionGroupModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*CollectionGroup, error) {

	builder = builder.Columns(collectionGroupRows)

	if orderBy == "" {
		builder = builder.OrderBy("created_at DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("is_del = ?", globalKey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*CollectionGroup
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultCollectionGroupModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*CollectionGroup, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(collectionGroupRows)

	if orderBy == "" {
		builder = builder.OrderBy("created_at DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("is_del = ?", globalKey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*CollectionGroup
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultCollectionGroupModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*CollectionGroup, error) {

	builder = builder.Columns(collectionGroupRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.Where("is_del = ?", globalKey.DelStateNo).OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*CollectionGroup
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultCollectionGroupModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*CollectionGroup, error) {

	builder = builder.Columns(collectionGroupRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.Where("is_del = ?", globalKey.DelStateNo).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*CollectionGroup
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultCollectionGroupModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultCollectionGroupModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
func (m *defaultCollectionGroupModel) Delete(ctx context.Context, session sqlx.Session, id uint64) error {
	qOperationCollectionGroupIdKey := fmt.Sprintf("%s%v", cacheQOperationCollectionGroupIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, qOperationCollectionGroupIdKey)
	return err
}
func (m *defaultCollectionGroupModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheQOperationCollectionGroupIdPrefix, primary)
}
func (m *defaultCollectionGroupModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? and is_del = ? limit 1", collectionGroupRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary, globalKey.DelStateNo)
}

func (m *defaultCollectionGroupModel) tableName() string {
	return m.table
}
