// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	roleLogic "qinglv-backend/app/user/rpc/internal/logic/role"
	userLogic "qinglv-backend/app/user/rpc/internal/logic/user"
	emailLogic "qinglv-backend/app/user/rpc/internal/logic/email"
	"qinglv-backend/app/user/rpc/internal/svc"
	"qinglv-backend/app/user/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

// group: role
func (s *UserServer) GetRoleInfo(ctx context.Context, in *user.GetRoleInfoReq) (*user.GetRoleInfoResp, error) {
	l := roleLogic.NewGetRoleInfoLogic(ctx, s.svcCtx)
	return l.GetRoleInfo(in)
}

// group: user
func (s *UserServer) Register(ctx context.Context, in *user.RegisterReq) (*user.RegisterResp, error) {
	l := userLogic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

// group: user
func (s *UserServer) Login(ctx context.Context, in *user.LoginReq) (*user.LoginResp, error) {
	l := userLogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

// group: user
func (s *UserServer) GetUserInfoByParams(ctx context.Context, in *user.GetUserInfoByParamsReq) (*user.GetUserInfoByParamsResp, error) {
	l := userLogic.NewGetUserInfoByParamsLogic(ctx, s.svcCtx)
	return l.GetUserInfoByParams(in)
}

// group: user
func (s *UserServer) GetUserList(ctx context.Context, in *user.GetUserListReq) (*user.GetUserListResp, error) {
	l := userLogic.NewGetUserListLogic(ctx, s.svcCtx)
	return l.GetUserList(in)
}

// group: email
func (s *UserServer) VerifyRegisterCode(ctx context.Context, in *user.VerifyRegisterCodeReq) (*user.VerifyRegisterCodeResp, error) {
	l := emailLogic.NewVerifyRegisterCodeLogic(ctx, s.svcCtx)
	return l.VerifyRegisterCode(in)
}

// group: email
func (s *UserServer) UpdateEmailStatus(ctx context.Context, in *user.UpdateEmailStatusReq) (*user.UpdateEmailStatusResp, error) {
	l := userLogic.NewUpdateEmailStatusLogic(ctx, s.svcCtx)
	return l.UpdateEmailStatus(in)
}
