// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	userLogic "qinglv-backend/app/user/rpc/internal/logic/user"
	roleLogic "qinglv-backend/app/user/rpc/internal/logic/role"
	"qinglv-backend/app/user/rpc/internal/svc"
	"qinglv-backend/app/user/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

// group: role
func (s *UserServer) GetRoleInfo(ctx context.Context, in *user.GetRoleInfoReq) (*user.GetRoleInfoResp, error) {
	l := roleLogic.NewGetRoleInfoLogic(ctx, s.svcCtx)
	return l.GetRoleInfo(in)
}

// group: user
func (s *UserServer) Register(ctx context.Context, in *user.RegisterReq) (*user.RegisterResp, error) {
	l := userLogic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

// group: user
func (s *UserServer) Login(ctx context.Context, in *user.LoginReq) (*user.LoginResp, error) {
	l := userLogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

// group: user
func (s *UserServer) GetUserInfo(ctx context.Context, in *user.GetUserInfoReq) (*user.GetUserInfoResp, error) {
	l := userLogic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

// group: user
func (s *UserServer) GetUserInfoByNickname(ctx context.Context, in *user.GetUserInfoNicknameReq) (*user.GetUserInfoResp, error) {
	l := userLogic.NewGetUserInfoByNicknameLogic(ctx, s.svcCtx)
	return l.GetUserInfoByNickname(in)
}

// group: user
func (s *UserServer) GetUserInfoByEmail(ctx context.Context, in *user.GetUserInfoEmailReq) (*user.GetUserInfoResp, error) {
	l := userLogic.NewGetUserInfoByEmailLogic(ctx, s.svcCtx)
	return l.GetUserInfoByEmail(in)
}

func (s *UserServer) GetUserList(ctx context.Context, in *user.GetUserListReq) (*user.GetUserListResp, error) {
	l := userLogic.NewGetUserListLogic(ctx, s.svcCtx)
	return l.GetUserList(in)
}
