// Code generated by goctl. DO NOT EDIT.
// Source: content.proto

package articleclass

import (
	"context"

	"qinglv-backend/app/content/rpc/content"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddArticleFeedReq           = content.AddArticleFeedReq
	AddArticleReq               = content.AddArticleReq
	AddCategoryReq              = content.AddCategoryReq
	AddMediaFileReq             = content.AddMediaFileReq
	AddPostContentReq           = content.AddPostContentReq
	AddPostFeedReq              = content.AddPostFeedReq
	AddPostReq                  = content.AddPostReq
	AddTagReq                   = content.AddTagReq
	AddTopicReq                 = content.AddTopicReq
	ArticleContentItem          = content.ArticleContentItem
	ArticleFeedItem             = content.ArticleFeedItem
	ArticleItem                 = content.ArticleItem
	CategoryItem                = content.CategoryItem
	DeleteArticleFeedByIdsReq   = content.DeleteArticleFeedByIdsReq
	DeleteArticleReq            = content.DeleteArticleReq
	DeleteCategoryReq           = content.DeleteCategoryReq
	DeleteMediaFileReq          = content.DeleteMediaFileReq
	DeletePostFeedByIdsReq      = content.DeletePostFeedByIdsReq
	DeletePostReq               = content.DeletePostReq
	DeleteTagReq                = content.DeleteTagReq
	DeleteTopicReq              = content.DeleteTopicReq
	GetArticleContentDetailReq  = content.GetArticleContentDetailReq
	GetArticleContentDetailResp = content.GetArticleContentDetailResp
	GetArticleContentListReq    = content.GetArticleContentListReq
	GetArticleContentListResp   = content.GetArticleContentListResp
	GetArticleDetailReq         = content.GetArticleDetailReq
	GetArticleDetailResp        = content.GetArticleDetailResp
	GetArticleFeedListReq       = content.GetArticleFeedListReq
	GetArticleFeedListResp      = content.GetArticleFeedListResp
	GetArticleListReq           = content.GetArticleListReq
	GetArticleListResp          = content.GetArticleListResp
	GetCategoryDetailReq        = content.GetCategoryDetailReq
	GetCategoryDetailResp       = content.GetCategoryDetailResp
	GetCategoryListReq          = content.GetCategoryListReq
	GetCategoryListResp         = content.GetCategoryListResp
	GetMediaFileByContentReq    = content.GetMediaFileByContentReq
	GetMediaFileByContentResp   = content.GetMediaFileByContentResp
	GetMediaFileListReq         = content.GetMediaFileListReq
	GetMediaFileListResp        = content.GetMediaFileListResp
	GetPostContentDetailReq     = content.GetPostContentDetailReq
	GetPostContentDetailResp    = content.GetPostContentDetailResp
	GetPostContentListReq       = content.GetPostContentListReq
	GetPostContentListResp      = content.GetPostContentListResp
	GetPostDetailReq            = content.GetPostDetailReq
	GetPostDetailResp           = content.GetPostDetailResp
	GetPostFeedListReq          = content.GetPostFeedListReq
	GetPostFeedListResp         = content.GetPostFeedListResp
	GetPostListReq              = content.GetPostListReq
	GetPostListResp             = content.GetPostListResp
	GetTagByIdReq               = content.GetTagByIdReq
	GetTagByIdResp              = content.GetTagByIdResp
	GetTagByNameReq             = content.GetTagByNameReq
	GetTagByNameResp            = content.GetTagByNameResp
	GetTagListReq               = content.GetTagListReq
	GetTagListResp              = content.GetTagListResp
	GetTopicByIdReq             = content.GetTopicByIdReq
	GetTopicByIdResp            = content.GetTopicByIdResp
	GetTopicByNameReq           = content.GetTopicByNameReq
	GetTopicByNameResp          = content.GetTopicByNameResp
	GetTopicListReq             = content.GetTopicListReq
	GetTopicListResp            = content.GetTopicListResp
	MediaFile                   = content.MediaFile
	OkResp                      = content.OkResp
	PostContentItem             = content.PostContentItem
	PostFeedItem                = content.PostFeedItem
	PostItem                    = content.PostItem
	ScanArticleByUserIdReq      = content.ScanArticleByUserIdReq
	ScanPostByUserReq           = content.ScanPostByUserReq
	TagItem                     = content.TagItem
	TopicItem                   = content.TopicItem
	UpdateArticleContentReq     = content.UpdateArticleContentReq
	UpdateArticleReq            = content.UpdateArticleReq
	UpdateCategoryReq           = content.UpdateCategoryReq
	UpdatePostReq               = content.UpdatePostReq
	UpdateTagReq                = content.UpdateTagReq
	UpdateTopicReq              = content.UpdateTopicReq

	ArticleClass interface {
		AddArticle(ctx context.Context, in *AddArticleReq, opts ...grpc.CallOption) (*OkResp, error)
		DeleteArticle(ctx context.Context, in *DeleteArticleReq, opts ...grpc.CallOption) (*OkResp, error)
		UpdateArticle(ctx context.Context, in *UpdateArticleReq, opts ...grpc.CallOption) (*OkResp, error)
		GetArticleDetail(ctx context.Context, in *GetArticleDetailReq, opts ...grpc.CallOption) (*GetArticleDetailResp, error)
		GetArticleList(ctx context.Context, in *GetArticleListReq, opts ...grpc.CallOption) (*GetArticleListResp, error)
		UpdateArticleContent(ctx context.Context, in *UpdateArticleContentReq, opts ...grpc.CallOption) (*OkResp, error)
		GetArticleContentByArticleId(ctx context.Context, in *GetArticleContentDetailReq, opts ...grpc.CallOption) (*GetArticleContentDetailResp, error)
		ScanArticleByUserId(ctx context.Context, in *ScanArticleByUserIdReq, opts ...grpc.CallOption) (*OkResp, error)
		AddArticleFeed(ctx context.Context, in *AddArticleFeedReq, opts ...grpc.CallOption) (*OkResp, error)
		DeleteArticleFeedByIds(ctx context.Context, in *DeleteArticleFeedByIdsReq, opts ...grpc.CallOption) (*OkResp, error)
		GetArticleFeedList(ctx context.Context, in *GetArticleFeedListReq, opts ...grpc.CallOption) (*GetArticleFeedListResp, error)
	}

	defaultArticleClass struct {
		cli zrpc.Client
	}
)

func NewArticleClass(cli zrpc.Client) ArticleClass {
	return &defaultArticleClass{
		cli: cli,
	}
}

func (m *defaultArticleClass) AddArticle(ctx context.Context, in *AddArticleReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := content.NewArticleClassClient(m.cli.Conn())
	return client.AddArticle(ctx, in, opts...)
}

func (m *defaultArticleClass) DeleteArticle(ctx context.Context, in *DeleteArticleReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := content.NewArticleClassClient(m.cli.Conn())
	return client.DeleteArticle(ctx, in, opts...)
}

func (m *defaultArticleClass) UpdateArticle(ctx context.Context, in *UpdateArticleReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := content.NewArticleClassClient(m.cli.Conn())
	return client.UpdateArticle(ctx, in, opts...)
}

func (m *defaultArticleClass) GetArticleDetail(ctx context.Context, in *GetArticleDetailReq, opts ...grpc.CallOption) (*GetArticleDetailResp, error) {
	client := content.NewArticleClassClient(m.cli.Conn())
	return client.GetArticleDetail(ctx, in, opts...)
}

func (m *defaultArticleClass) GetArticleList(ctx context.Context, in *GetArticleListReq, opts ...grpc.CallOption) (*GetArticleListResp, error) {
	client := content.NewArticleClassClient(m.cli.Conn())
	return client.GetArticleList(ctx, in, opts...)
}

func (m *defaultArticleClass) UpdateArticleContent(ctx context.Context, in *UpdateArticleContentReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := content.NewArticleClassClient(m.cli.Conn())
	return client.UpdateArticleContent(ctx, in, opts...)
}

func (m *defaultArticleClass) GetArticleContentByArticleId(ctx context.Context, in *GetArticleContentDetailReq, opts ...grpc.CallOption) (*GetArticleContentDetailResp, error) {
	client := content.NewArticleClassClient(m.cli.Conn())
	return client.GetArticleContentByArticleId(ctx, in, opts...)
}

func (m *defaultArticleClass) ScanArticleByUserId(ctx context.Context, in *ScanArticleByUserIdReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := content.NewArticleClassClient(m.cli.Conn())
	return client.ScanArticleByUserId(ctx, in, opts...)
}

func (m *defaultArticleClass) AddArticleFeed(ctx context.Context, in *AddArticleFeedReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := content.NewArticleClassClient(m.cli.Conn())
	return client.AddArticleFeed(ctx, in, opts...)
}

func (m *defaultArticleClass) DeleteArticleFeedByIds(ctx context.Context, in *DeleteArticleFeedByIdsReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := content.NewArticleClassClient(m.cli.Conn())
	return client.DeleteArticleFeedByIds(ctx, in, opts...)
}

func (m *defaultArticleClass) GetArticleFeedList(ctx context.Context, in *GetArticleFeedListReq, opts ...grpc.CallOption) (*GetArticleFeedListResp, error) {
	client := content.NewArticleClassClient(m.cli.Conn())
	return client.GetArticleFeedList(ctx, in, opts...)
}
