// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package followingclass

import (
	"context"

	"qinglv-backend/app/user/rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddBlackItemReq          = user.AddBlackItemReq
	AddBlackItemResp         = user.AddBlackItemResp
	AddFollowingReq          = user.AddFollowingReq
	AddFollowingResp         = user.AddFollowingResp
	BanUserReq               = user.BanUserReq
	BanUserResp              = user.BanUserResp
	BlackItem                = user.BlackItem
	CheckBlackItemReq        = user.CheckBlackItemReq
	CheckBlackItemResp       = user.CheckBlackItemResp
	CheckEmailExistReq       = user.CheckEmailExistReq
	CheckEmailExistResp      = user.CheckEmailExistResp
	CheckFollowingReq        = user.CheckFollowingReq
	CheckFollowingResp       = user.CheckFollowingResp
	CheckNicknameExistReq    = user.CheckNicknameExistReq
	CheckNicknameExistResp   = user.CheckNicknameExistResp
	DeleteBlackItemReq       = user.DeleteBlackItemReq
	DeleteBlackItemResp      = user.DeleteBlackItemResp
	DeleteFollowingReq       = user.DeleteFollowingReq
	DeleteFollowingResp      = user.DeleteFollowingResp
	DeleteUserReq            = user.DeleteUserReq
	DeleteUserResp           = user.DeleteUserResp
	Empty                    = user.Empty
	FollowingItem            = user.FollowingItem
	GenerateCaptchaResp      = user.GenerateCaptchaResp
	GetBlackListReq          = user.GetBlackListReq
	GetBlackListResp         = user.GetBlackListResp
	GetFollowingListReq      = user.GetFollowingListReq
	GetFollowingListResp     = user.GetFollowingListResp
	GetRoleInfoReq           = user.GetRoleInfoReq
	GetRoleInfoResp          = user.GetRoleInfoResp
	GetTokenReq              = user.GetTokenReq
	GetTokenResp             = user.GetTokenResp
	GetUserByIdReq           = user.GetUserByIdReq
	GetUserByIdResp          = user.GetUserByIdResp
	GetUserListReq           = user.GetUserListReq
	GetUserListResp          = user.GetUserListResp
	LoginReq                 = user.LoginReq
	LoginResp                = user.LoginResp
	LogoutReq                = user.LogoutReq
	LogoutResp               = user.LogoutResp
	RegisterReq              = user.RegisterReq
	RegisterResp             = user.RegisterResp
	RoleItem                 = user.RoleItem
	UpdateAvatarReq          = user.UpdateAvatarReq
	UpdateAvatarResp         = user.UpdateAvatarResp
	UpdateEmailStatusReq     = user.UpdateEmailStatusReq
	UpdateEmailStatusResp    = user.UpdateEmailStatusResp
	UpdatePasswordReq        = user.UpdatePasswordReq
	UpdatePasswordResp       = user.UpdatePasswordResp
	UpdateProfileBgReq       = user.UpdateProfileBgReq
	UpdateProfileBgResp      = user.UpdateProfileBgResp
	UpdateUserReq            = user.UpdateUserReq
	UpdateUserResp           = user.UpdateUserResp
	UpdateUserScoreLevelReq  = user.UpdateUserScoreLevelReq
	UpdateUserScoreLevelResp = user.UpdateUserScoreLevelResp
	UserItem                 = user.UserItem
	VerifyCaptchaReq         = user.VerifyCaptchaReq
	VerifyCaptchaResp        = user.VerifyCaptchaResp
	VerifyRegisterCodeReq    = user.VerifyRegisterCodeReq
	VerifyRegisterCodeResp   = user.VerifyRegisterCodeResp

	FollowingClass interface {
		// group: following
		AddFollowing(ctx context.Context, in *AddFollowingReq, opts ...grpc.CallOption) (*AddFollowingResp, error)
		// group: following
		DeleteFollowing(ctx context.Context, in *DeleteFollowingReq, opts ...grpc.CallOption) (*DeleteFollowingResp, error)
		// group: following
		GetFollowingList(ctx context.Context, in *GetFollowingListReq, opts ...grpc.CallOption) (*GetFollowingListResp, error)
		// group: following
		CheckFollowing(ctx context.Context, in *CheckFollowingReq, opts ...grpc.CallOption) (*CheckFollowingResp, error)
	}

	defaultFollowingClass struct {
		cli zrpc.Client
	}
)

func NewFollowingClass(cli zrpc.Client) FollowingClass {
	return &defaultFollowingClass{
		cli: cli,
	}
}

// group: following
func (m *defaultFollowingClass) AddFollowing(ctx context.Context, in *AddFollowingReq, opts ...grpc.CallOption) (*AddFollowingResp, error) {
	client := user.NewFollowingClassClient(m.cli.Conn())
	return client.AddFollowing(ctx, in, opts...)
}

// group: following
func (m *defaultFollowingClass) DeleteFollowing(ctx context.Context, in *DeleteFollowingReq, opts ...grpc.CallOption) (*DeleteFollowingResp, error) {
	client := user.NewFollowingClassClient(m.cli.Conn())
	return client.DeleteFollowing(ctx, in, opts...)
}

// group: following
func (m *defaultFollowingClass) GetFollowingList(ctx context.Context, in *GetFollowingListReq, opts ...grpc.CallOption) (*GetFollowingListResp, error) {
	client := user.NewFollowingClassClient(m.cli.Conn())
	return client.GetFollowingList(ctx, in, opts...)
}

// group: following
func (m *defaultFollowingClass) CheckFollowing(ctx context.Context, in *CheckFollowingReq, opts ...grpc.CallOption) (*CheckFollowingResp, error) {
	client := user.NewFollowingClassClient(m.cli.Conn())
	return client.CheckFollowing(ctx, in, opts...)
}
