// Code generated by goctl. DO NOT EDIT.
// Source: operation.proto

package commentclass

import (
	"context"

	"qinglv-backend/app/operation/rpc/operation"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddCollectionGroupReq      = operation.AddCollectionGroupReq
	AddCollectionReq           = operation.AddCollectionReq
	AddCommentReplyReq         = operation.AddCommentReplyReq
	AddCommentReq              = operation.AddCommentReq
	AddCommentThumbReq         = operation.AddCommentThumbReq
	AddPostShareReq            = operation.AddPostShareReq
	AddThumbReq                = operation.AddThumbReq
	ArticleCommentItem         = operation.ArticleCommentItem
	ArticleCommentReplyItem    = operation.ArticleCommentReplyItem
	ArticleCommentReplyResp    = operation.ArticleCommentReplyResp
	ArticleCommentResp         = operation.ArticleCommentResp
	ArticleCommentThumbItem    = operation.ArticleCommentThumbItem
	ArticleThumbItem           = operation.ArticleThumbItem
	CheckExistByNameReq        = operation.CheckExistByNameReq
	CheckExistByNameResp       = operation.CheckExistByNameResp
	CollectionGroupItem        = operation.CollectionGroupItem
	CollectionItem             = operation.CollectionItem
	DeleteCollectionGroupReq   = operation.DeleteCollectionGroupReq
	DeleteCollectionReq        = operation.DeleteCollectionReq
	DeleteCommentReplyReq      = operation.DeleteCommentReplyReq
	DeleteCommentReq           = operation.DeleteCommentReq
	GetCollectionByIdReq       = operation.GetCollectionByIdReq
	GetCollectionByIdResp      = operation.GetCollectionByIdResp
	GetCollectionGroupByIdReq  = operation.GetCollectionGroupByIdReq
	GetCollectionGroupByIdResp = operation.GetCollectionGroupByIdResp
	GetCollectionGroupListReq  = operation.GetCollectionGroupListReq
	GetCollectionGroupListResp = operation.GetCollectionGroupListResp
	GetCollectionListReq       = operation.GetCollectionListReq
	GetCollectionListResp      = operation.GetCollectionListResp
	GetCommentListReq          = operation.GetCommentListReq
	GetCommentListResp         = operation.GetCommentListResp
	GetCommentReplyListReq     = operation.GetCommentReplyListReq
	GetCommentReplyListResp    = operation.GetCommentReplyListResp
	GetCommentThumbDetailReq   = operation.GetCommentThumbDetailReq
	GetCommentThumbDetailResp  = operation.GetCommentThumbDetailResp
	GetThumbDetailReq          = operation.GetThumbDetailReq
	GetThumbDetailResp         = operation.GetThumbDetailResp
	OkResp                     = operation.OkResp
	PostCommentItem            = operation.PostCommentItem
	PostCommentReplyItem       = operation.PostCommentReplyItem
	PostCommentReplyResp       = operation.PostCommentReplyResp
	PostCommentResp            = operation.PostCommentResp
	PostCommentThumbItem       = operation.PostCommentThumbItem
	PostThumbItem              = operation.PostThumbItem
	UpdateCollectionGroupReq   = operation.UpdateCollectionGroupReq
	UpdateCommentThumbReq      = operation.UpdateCommentThumbReq
	UpdateThumbReq             = operation.UpdateThumbReq

	CommentClass interface {
		// group: Comment
		AddComment(ctx context.Context, in *AddCommentReq, opts ...grpc.CallOption) (*OkResp, error)
		// group: Comment
		DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*OkResp, error)
		// group: Comment
		AddCommentReply(ctx context.Context, in *AddCommentReplyReq, opts ...grpc.CallOption) (*OkResp, error)
		// group: Comment
		DeleteCommentReply(ctx context.Context, in *DeleteCommentReplyReq, opts ...grpc.CallOption) (*OkResp, error)
		// group: Comment
		GetCommentList(ctx context.Context, in *GetCommentListReq, opts ...grpc.CallOption) (*GetCommentListResp, error)
		// group: Comment
		GetCommentReplyList(ctx context.Context, in *GetCommentReplyListReq, opts ...grpc.CallOption) (*GetCommentReplyListResp, error)
	}

	defaultCommentClass struct {
		cli zrpc.Client
	}
)

func NewCommentClass(cli zrpc.Client) CommentClass {
	return &defaultCommentClass{
		cli: cli,
	}
}

// group: Comment
func (m *defaultCommentClass) AddComment(ctx context.Context, in *AddCommentReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := operation.NewCommentClassClient(m.cli.Conn())
	return client.AddComment(ctx, in, opts...)
}

// group: Comment
func (m *defaultCommentClass) DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := operation.NewCommentClassClient(m.cli.Conn())
	return client.DeleteComment(ctx, in, opts...)
}

// group: Comment
func (m *defaultCommentClass) AddCommentReply(ctx context.Context, in *AddCommentReplyReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := operation.NewCommentClassClient(m.cli.Conn())
	return client.AddCommentReply(ctx, in, opts...)
}

// group: Comment
func (m *defaultCommentClass) DeleteCommentReply(ctx context.Context, in *DeleteCommentReplyReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := operation.NewCommentClassClient(m.cli.Conn())
	return client.DeleteCommentReply(ctx, in, opts...)
}

// group: Comment
func (m *defaultCommentClass) GetCommentList(ctx context.Context, in *GetCommentListReq, opts ...grpc.CallOption) (*GetCommentListResp, error) {
	client := operation.NewCommentClassClient(m.cli.Conn())
	return client.GetCommentList(ctx, in, opts...)
}

// group: Comment
func (m *defaultCommentClass) GetCommentReplyList(ctx context.Context, in *GetCommentReplyListReq, opts ...grpc.CallOption) (*GetCommentReplyListResp, error) {
	client := operation.NewCommentClassClient(m.cli.Conn())
	return client.GetCommentReplyList(ctx, in, opts...)
}
