// Code generated by goctl. DO NOT EDIT.
// Source: content.proto

package draftclass

import (
	"context"

	"qinglv-backend/app/content/rpc/content"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddArticleFeedReq           = content.AddArticleFeedReq
	AddArticleReq               = content.AddArticleReq
	AddCategoryReq              = content.AddCategoryReq
	AddDraftReq                 = content.AddDraftReq
	AddMediaFileReq             = content.AddMediaFileReq
	AddPostContentReq           = content.AddPostContentReq
	AddPostFeedReq              = content.AddPostFeedReq
	AddPostReq                  = content.AddPostReq
	AddTagReq                   = content.AddTagReq
	AddTopicReq                 = content.AddTopicReq
	ArticleContentItem          = content.ArticleContentItem
	ArticleFeedItem             = content.ArticleFeedItem
	ArticleItem                 = content.ArticleItem
	CategoryItem                = content.CategoryItem
	DeleteArticleFeedByIdsReq   = content.DeleteArticleFeedByIdsReq
	DeleteArticleReq            = content.DeleteArticleReq
	DeleteCategoryReq           = content.DeleteCategoryReq
	DeleteDraftReq              = content.DeleteDraftReq
	DeleteMediaFileReq          = content.DeleteMediaFileReq
	DeletePostFeedByIdsReq      = content.DeletePostFeedByIdsReq
	DeletePostReq               = content.DeletePostReq
	DeleteTagReq                = content.DeleteTagReq
	DeleteTopicReq              = content.DeleteTopicReq
	DraftItem                   = content.DraftItem
	GetArticleContentDetailReq  = content.GetArticleContentDetailReq
	GetArticleContentDetailResp = content.GetArticleContentDetailResp
	GetArticleContentListReq    = content.GetArticleContentListReq
	GetArticleContentListResp   = content.GetArticleContentListResp
	GetArticleDetailReq         = content.GetArticleDetailReq
	GetArticleDetailResp        = content.GetArticleDetailResp
	GetArticleFeedListReq       = content.GetArticleFeedListReq
	GetArticleFeedListResp      = content.GetArticleFeedListResp
	GetArticleListReq           = content.GetArticleListReq
	GetArticleListResp          = content.GetArticleListResp
	GetCategoryDetailReq        = content.GetCategoryDetailReq
	GetCategoryDetailResp       = content.GetCategoryDetailResp
	GetCategoryListReq          = content.GetCategoryListReq
	GetCategoryListResp         = content.GetCategoryListResp
	GetDraftByIdReq             = content.GetDraftByIdReq
	GetDraftByIdResp            = content.GetDraftByIdResp
	GetDraftListReq             = content.GetDraftListReq
	GetDraftListResp            = content.GetDraftListResp
	GetMediaFileByContentReq    = content.GetMediaFileByContentReq
	GetMediaFileByContentResp   = content.GetMediaFileByContentResp
	GetMediaFileListReq         = content.GetMediaFileListReq
	GetMediaFileListResp        = content.GetMediaFileListResp
	GetPostContentDetailReq     = content.GetPostContentDetailReq
	GetPostContentDetailResp    = content.GetPostContentDetailResp
	GetPostContentListReq       = content.GetPostContentListReq
	GetPostContentListResp      = content.GetPostContentListResp
	GetPostDetailReq            = content.GetPostDetailReq
	GetPostDetailResp           = content.GetPostDetailResp
	GetPostFeedListReq          = content.GetPostFeedListReq
	GetPostFeedListResp         = content.GetPostFeedListResp
	GetPostListReq              = content.GetPostListReq
	GetPostListResp             = content.GetPostListResp
	GetTagByIdReq               = content.GetTagByIdReq
	GetTagByIdResp              = content.GetTagByIdResp
	GetTagByNameReq             = content.GetTagByNameReq
	GetTagByNameResp            = content.GetTagByNameResp
	GetTagListReq               = content.GetTagListReq
	GetTagListResp              = content.GetTagListResp
	GetTopicByIdReq             = content.GetTopicByIdReq
	GetTopicByIdResp            = content.GetTopicByIdResp
	GetTopicByNameReq           = content.GetTopicByNameReq
	GetTopicByNameResp          = content.GetTopicByNameResp
	GetTopicListReq             = content.GetTopicListReq
	GetTopicListResp            = content.GetTopicListResp
	MediaFile                   = content.MediaFile
	OkResp                      = content.OkResp
	PostContentItem             = content.PostContentItem
	PostFeedItem                = content.PostFeedItem
	PostItem                    = content.PostItem
	ScanArticleByUserIdReq      = content.ScanArticleByUserIdReq
	ScanPostByUserReq           = content.ScanPostByUserReq
	TagItem                     = content.TagItem
	TopicItem                   = content.TopicItem
	UpdateArticleContentReq     = content.UpdateArticleContentReq
	UpdateArticleReq            = content.UpdateArticleReq
	UpdateCategoryReq           = content.UpdateCategoryReq
	UpdateDraftReq              = content.UpdateDraftReq
	UpdatePostReq               = content.UpdatePostReq
	UpdateTagReq                = content.UpdateTagReq
	UpdateTopicReq              = content.UpdateTopicReq

	DraftClass interface {
		AddDraft(ctx context.Context, in *AddDraftReq, opts ...grpc.CallOption) (*OkResp, error)
		UpdateDraft(ctx context.Context, in *UpdateDraftReq, opts ...grpc.CallOption) (*OkResp, error)
		DeleteDraft(ctx context.Context, in *DeleteDraftReq, opts ...grpc.CallOption) (*OkResp, error)
		GetDraftById(ctx context.Context, in *GetDraftByIdReq, opts ...grpc.CallOption) (*GetDraftByIdResp, error)
		GetDraftList(ctx context.Context, in *GetDraftListReq, opts ...grpc.CallOption) (*GetDraftListResp, error)
	}

	defaultDraftClass struct {
		cli zrpc.Client
	}
)

func NewDraftClass(cli zrpc.Client) DraftClass {
	return &defaultDraftClass{
		cli: cli,
	}
}

func (m *defaultDraftClass) AddDraft(ctx context.Context, in *AddDraftReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := content.NewDraftClassClient(m.cli.Conn())
	return client.AddDraft(ctx, in, opts...)
}

func (m *defaultDraftClass) UpdateDraft(ctx context.Context, in *UpdateDraftReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := content.NewDraftClassClient(m.cli.Conn())
	return client.UpdateDraft(ctx, in, opts...)
}

func (m *defaultDraftClass) DeleteDraft(ctx context.Context, in *DeleteDraftReq, opts ...grpc.CallOption) (*OkResp, error) {
	client := content.NewDraftClassClient(m.cli.Conn())
	return client.DeleteDraft(ctx, in, opts...)
}

func (m *defaultDraftClass) GetDraftById(ctx context.Context, in *GetDraftByIdReq, opts ...grpc.CallOption) (*GetDraftByIdResp, error) {
	client := content.NewDraftClassClient(m.cli.Conn())
	return client.GetDraftById(ctx, in, opts...)
}

func (m *defaultDraftClass) GetDraftList(ctx context.Context, in *GetDraftListReq, opts ...grpc.CallOption) (*GetDraftListResp, error) {
	client := content.NewDraftClassClient(m.cli.Conn())
	return client.GetDraftList(ctx, in, opts...)
}
