// Code generated by goctl. DO NOT EDIT.
// Source: content.proto

package server

import (
	"context"

	"qinglv-backend/app/content/rpc/content"
	"qinglv-backend/app/content/rpc/internal/logic/mediafileclass"
	"qinglv-backend/app/content/rpc/internal/svc"
)

type MediaFileClassServer struct {
	svcCtx *svc.ServiceContext
	content.UnimplementedMediaFileClassServer
}

func NewMediaFileClassServer(svcCtx *svc.ServiceContext) *MediaFileClassServer {
	return &MediaFileClassServer{
		svcCtx: svcCtx,
	}
}

func (s *MediaFileClassServer) AddMediaFile(ctx context.Context, in *content.AddMediaFileReq) (*content.OkResp, error) {
	l := mediafileclasslogic.NewAddMediaFileLogic(ctx, s.svcCtx)
	return l.AddMediaFile(in)
}

func (s *MediaFileClassServer) DeleteMediaFile(ctx context.Context, in *content.DeleteMediaFileReq) (*content.OkResp, error) {
	l := mediafileclasslogic.NewDeleteMediaFileLogic(ctx, s.svcCtx)
	return l.DeleteMediaFile(in)
}

func (s *MediaFileClassServer) GetMediaFileByContent(ctx context.Context, in *content.GetMediaFileByContentReq) (*content.GetMediaFileByContentResp, error) {
	l := mediafileclasslogic.NewGetMediaFileByContentLogic(ctx, s.svcCtx)
	return l.GetMediaFileByContent(in)
}

func (s *MediaFileClassServer) GetMediaFileList(ctx context.Context, in *content.GetMediaFileListReq) (*content.GetMediaFileListResp, error) {
	l := mediafileclasslogic.NewGetMediaFileListLogic(ctx, s.svcCtx)
	return l.GetMediaFileList(in)
}
