// Code generated by goctl. DO NOT EDIT.
package types

type AddBlackItemReq struct {
	UserId uint64 `json:"userId,string"`
}

type AddFollowerReq struct {
	UserId uint64 `json:"userId,string"`
}

type AddFollowingReq struct {
	UserId uint64 `json:"userId,string"`
}

type AvatarReq struct {
	Avatar string `json:"avatar"`
}

type BanUserReq struct {
	Id uint64 `path:"id,string"`
}

type BlackItem struct {
	Id        uint64 `json:"id,string"`
	UserId    uint64 `json:"userId,string"`
	BlackId   uint64 `json:"blackId,string"`
	CreatedAt uint64 `json:"createdAt"`
	UpdatedAt uint64 `json:"updatedAt"`
}

type BlacklistReq struct {
	UserId   uint64 `form:"userId,string,optional"`
	BlackIId uint64 `form:"BlackId,string,optional"`
	PageNum  int    `json:"pageNum" validate:"required,gt=0"`
	PageSize int    `json:"pageSize" validate:"required,gt=0"`
}

type BlacklistResp struct {
	List  []BlackItem `json:"list"`
	IsEnd bool        `json:"isEnd"`
	Total bool        `json:"total"`
}

type DelBlackItemReq struct {
	UserId uint64 `json:"userId,string"`
}

type DelFollowerReq struct {
	UserId uint64 `json:"userId,string"`
}

type DelFollowingReq struct {
	UserId uint64 `json:"userId,string"`
}

type DelUserReq struct {
	Id uint64 `path:"id,string"`
}

type Follower struct {
	Id         uint64 `json:"id,string"`
	UserId     uint64 `json:"userId,string"`
	FollowerId uint64 `json:"followerId,string"`
	CreatedAt  uint64 `json:"createdAt"`
	UpdatedAt  uint64 `json:"updatedAt"`
}

type FollowerListReq struct {
	UserId     uint64 `form:"userId,string,optional"`
	FollowerId uint64 `form:"followerId,string,optional"`
	PageNum    int    `json:"pageNum" validate:"required,gt=0"`
	PageSize   int    `json:"pageSize" validate:"required,gt=0"`
}

type FollowerListResp struct {
	List  []Follower `json:"list"`
	IsEnd bool       `json:"isEnd"`
	Total bool       `json:"total"`
}

type Following struct {
	Id          uint64 `json:"id,string"`
	UserId      uint64 `json:"userId,string"`
	FollowingId uint64 `json:"followingId,string"`
	CreatedAt   uint64 `json:"createdAt"`
	UpdatedAt   uint64 `json:"updatedAt"`
}

type FollowingListReq struct {
	UserId   uint64 `form:"userId,string,optional"`
	FollowId uint64 `form:"followId,string,optional"`
	PageNum  int    `json:"pageNum" validate:"required,gt=0"`
	PageSize int    `json:"pageSize" validate:"required,gt=0"`
}

type FollowingListResp struct {
	List  []Following `json:"list"`
	IsEnd bool        `json:"isEnd"`
	Total bool        `json:"total"`
}

type LoginCaptchaResp struct {
	CaptchaCode string `json:"captchaCode"`
	CaptchaImg  string `json:"captchaImg"`
}

type LoginReq struct {
	Email        string `json:"email" validate:"required,email,max=50"`
	Password     string `json:"password" validate:"required,min=6,max=50"`
	CaptchaCode  string `json:"captchaCode"`
	CaptchaValue string `json:"captchaValue"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	RefreshAfter uint64 `json:"refreshAfter"`
	ExpireAt     uint64 `json:"refreshAt"`
}

type PasswordReq struct {
	OldPassword string `json:"oldPassword" validate:"required,min=6,max=24"`
	NewPassword string `json:"newPassword" validate:"required,min=6,max=24"`
	RePassword  string `json:"rePassword" validate:"required,min=6,max=24,eqfield=NewPassword"`
}

type RegisterReq struct {
	RoleId     uint64 `json:"roleId,string"`
	Nickname   string `json:"nickname" validate:"required,max=50"`
	Email      string `json:"email" validate:"required,email,max=50"`
	Password   string `json:"password" validate:"required,min=6,max=50"`
	RePassword string `json:"rePassword" validate:"required,min=6,max=50,eqfield=Password"`
}

type Role struct {
	ID        uint64 `json:"id,string"`
	Name      string `json:"name"`
	CreatedAt uint64 `json:"createdAt"`
	UpdatedAt uint64 `json:"updatedAt"`
}

type RoleListReq struct {
	Name     string `form:"name,optional"`
	PageNum  int    `form:"pageNum"`
	PageSize int    `form:"pageSize"`
}

type RoleListResp struct {
	List  []Role `json:"list"`
	IsEnd bool   `json:"isEnd"`
	Total bool   `json:"total"`
}

type RoleReq struct {
	Name string `json:"name" validate:"required,max=50"`
}

type UpdateProfileReq struct {
	ProfileBg string `json:"profileBg"`
}

type UpdateUserReq struct {
	UserId   uint64 `json:"userId,string"`
	Nickname string `json:"nickname,optional" validate:"max=50"`
	Email    string `json:"email,optional" validate:"email,max=50"`
	Age      int    `json:"age,range=[0:120],optional"`
	Gender   int    `json:"gender,options=[1,2],default=1,optional"`
	Phone    string `json:"phone,optional"`
	Motto    string `json:"motto,optional", validate:"max=200"`
	Address  string `json:"address,optional", validate:"max=200"`
	Location string `json:"location,optional", validate:"max=200"`
}

type User struct {
	Id            uint64 `json:"id"`
	Role          Role   `json:"role"`
	RoleId        uint64 `json:"roleId"`
	Nickname      string `json:"nickname"`
	Email         string `json:"email"`
	WeChat        string `json:"weChat"`
	Motto         string `json:"motto"`
	Avatar        string `json:"avatar"`
	ProfileBg     string `json:"profileBg"`
	Age           int    `json:"age,range=[0:120]"`
	Gender        int    `json:"gender,options=[1,2],default=1"`
	Location      string `json:"location"`
	Status        int    `json:"status"`
	Level         int    `json:"level"`
	Score         int    `json:"score"`
	MailStatus    int    `json:"mailStatus"`
	LastLoginTime uint64 `json:"lastLoginTime"`
	CreatedAt     uint64 `json:"createdAt"`
	UpdatedAt     uint64 `json:"updatedAt"`
}

type UserListReq struct {
	Nickname   string `form:"nickname,optional"`
	Email      string `form:"email,optional"`
	Phone      string `form:"phone,optional"`
	WeChat     string `form:"weChat,optional"`
	Status     int    `form:"status,optional"`
	MailStatus int    `form:"mailStatus,optional"`
	Sort       string `form:"sort,optional"`
	PageNum    int    `form:"pageNum" validate:"required,gt=0"`
	PageSize   int    `form:"pageSize" validate:"required,gt=0"`
}

type UserListResp struct {
	List  []User `json:"list"`
	IsEnd bool   `json:"isEnd"`
	Total uint64 `json:"total"`
}

type UserReq struct {
	Nickname string `json:"nickname" validate:"max=50"`
	RoldId   uint64 `json:"roleId,string"`
	Motto    string `json:"motto" validate:"max=200"`
	Age      int    `json:"age,range=[0:120]" validate:"number,gt=0,lt=130"`
	Gender   int    `json:"gender,options=[0,1],default=0" validate:"oneof=0,1"`
	Location string `json:"location" validate:"max=200"`
	Status   int    `json:"status,options=[0,1,2]" validate:"oneof=0,1,2"`
	Level    int    `json:"level" validate:"number,gte=0,lte=10"`
	Score    int    `json:"score" validate:"number,gte=0"`
}

type VerifyEmailReq struct {
	Code string `form:"code"`
}

type VerifyEmailResp struct {
	VerifyResult bool `json:"verifyResult"`
}

type GetUserByIdReq struct {
	Id uint64 `path:"id,string"`
}
