// Code generated by goctl. DO NOT EDIT.
package types

type Role struct {
	ID        int64  `json:"id"`
	UserId    int64  `json:"userId"`
	Name      string `json:"name"`
	CreatedAt int64  `json:"createdAt"`
	UpdatedAt int64  `json:"updatedAt"`
}

type RoleReq struct {
	Name string `json:"name"`
}

type Resp struct {
	Role Role `json:"role"`
}

type RoleListReq struct {
	UserId   int64  `json:"userId"`
	Name     string `json:"name"`
	PageNum  int    `json:"pageNum"`
	PageSize int    `json:"pageSize"`
}

type RoleListResp struct {
	List  []Role `json:"list"`
	IsEnd bool   `json:"isEnd"`
	Total bool   `json:"total"`
}

type EmailReq struct {
	Email string `json:"email"`
}

type PhoneReq struct {
	Phone string `json:"phone"`
}

type RegisterReq struct {
	Nickname   string `json:"nickname"`
	Email      string `json:"email"`
	Password   string `json:"password"`
	RePassword string `json:"rePassword"`
}

type RegisterResp struct {
	Id int64 `json:"id"`
}

type LoginReq struct {
	Email      string `json:"email"`
	Password   string `json:"password"`
	CaptchId   string `json:"captchId"`
	CaptchCode string `json:"captchCode"`
	VerifyCode string `json:"VerifyCode"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refressToken"`
	ExpireAt     int64  `json:"refreshAt"`
}

type PasswordReq struct {
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
	RePassword  string `json:"rePassword"`
}

type User struct {
	Id        int64  `json:"id"`
	Role      Role   `json:"role"`
	RoleId    int64  `json:"roleId"`
	Nickname  string `json:"nickname"`
	Email     string `json:"email"`
	WeChat    string `json:"weChat"`
	Motto     string `json:"motto"`
	Avatar    string `json:"avatar"`
	ProfileBg string `json:"profileBg"`
	Age       int    `json:"age,range=[0:120]"`
	Gender    int    `json:"gender,options=[0,1],default=0"`
	Location  string `json:"location"`
	Status    int    `json:"status"`
	Level     int    `json:"level"`
	Score     int    `json:"score"`
	CreatedAt int64  `json:"createdAt"`
	UpdatedAt int64  `json:"updatedAt"`
}

type UserListReq struct {
	Account  string `json:"account"`
	Nickname string `json:"nickname"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	WeChat   string `json:"weChat"`
	PageNum  int    `json:"pageNum"`
	PageSize int    `json:"pageSize"`
}

type UserListResp struct {
	List  []User `json:"list"`
	IsEnd bool   `json:"isEnd"`
	Total bool   `json:"total"`
}

type UserReq struct {
	Account  string `json:"account"`
	Nickname string `json:"nickname"`
	RoldId   int64  `json:"roleId"`
	Motto    string `json:"motto"`
	Age      int    `json:"age,range=[0:120]"`
	Gender   int    `json:"gender,options=[0,1],default=0"`
	Location string `json:"location"`
	Status   int    `json:"status"`
	Level    int    `json:"level"`
	Score    int    `json:"score"`
}

type UserResp struct {
	User User `json:"user"`
}

type Following struct {
	Id          int64 `json:"id"`
	UserId      int64 `json:"userId"`
	FollowingId int64 `json:"followingId"`
	CreatedAt   int64 `json:"createdAt"`
	UpdatedAt   int64 `json:"updatedAt"`
}

type AddFollowingReq struct {
	UserId int64 `json:"userId"`
}

type DelFollowingReq struct {
	UserId int64 `json:"userId"`
}

type FollowingListReq struct {
	UserId   int64 `json:"userId"`
	FollowId int64 `json:"followId"`
	PageNum  int   `json:"pageNum"`
	PageSize int   `json:"pageSize"`
}

type FollowingListResp struct {
	List  []Following `json:"list"`
	IsEnd bool        `json:"isEnd"`
	Total bool        `json:"total"`
}

type Follower struct {
	Id         int64 `json:"id"`
	UserId     int64 `json:"userId"`
	FollowerId int64 `json:"followerId"`
	CreatedAt  int64 `json:"createdAt"`
	UpdatedAt  int64 `json:"updatedAt"`
}

type AddFollowerReq struct {
	UserId int64 `json:"userId"`
}

type DelFollowerReq struct {
	UserId int64 `json:"userId"`
}

type FollowerListReq struct {
	UserId     int64 `json:"userId"`
	FollowerId int64 `json:"followerId"`
	PageNum    int   `json:"pageNum"`
	PageSize   int   `json:"pageSize"`
}

type FollowerListResp struct {
	List  []Follower `json:"list"`
	IsEnd bool       `json:"isEnd"`
	Total bool       `json:"total"`
}
