syntax = "proto3";

package user;
option go_package="./user";

message Empty{}

message VerifyRegisterCodeReq {
    string code = 1;
}

message VerifyRegisterCodeResp {
    string codeContent = 1;
}


message RoleItem {
    uint64 id = 1;
    string name = 2;
    uint64 createdAt = 3;
    uint64 updatedAt = 4;
}

message GetRoleInfoReq {
    uint64 id = 1;
}

message GetRoleInfoResp {
    RoleItem Role = 1;
}


message UserItem {
  uint64 id = 1;
  uint64 roleId = 2;
  string nickname = 3;
  string email = 4;
  string phone = 5;
  string weChat = 6;
  string motto = 7;
  string avatar = 8;
  string profileBg = 9;
  int32 age = 10;
  int32 gender = 11;
  int32 status = 12;
  string location = 13;
  int32 level = 14;
  int32 score = 15;
  uint64 createdAt = 16;
  uint64 updatedAt = 17;
  uint64 lastLoginTime = 18;
  int32 authType = 19;
  int32 mailStatus = 20;
  string password = 21;
  string address = 22;
}

message RegisterReq {
  uint64 id = 1;
  uint64 roleId = 2;
  string nickname = 3;
  string email = 4;
  string password = 5;
  string phone = 6;
  int32 authType = 7;
}

message RegisterResp {
  UserItem user = 1;
}

message LoginReq {
  string email = 1;
  string phone = 2;
  string nickname = 3;
  string password = 4;
}

message LoginResp {
  string accessToken = 1;
  string refreshToken = 2;
  int64 expireAt = 3;
}

message CheckNicknameExistReq{
  string nickname = 1;
}

message CheckEmailExistReq {
  string email = 1;
}

message CheckEmailExistResp {
  bool isExist = 1;
  UserItem user = 2;
}

message CheckNicknameExistResp {
  bool isExist = 1;
  UserItem user = 2;
}

message GetUserByIdReq {
  uint64 userId = 1;
}
message GetUserByIdResp {
  UserItem user = 1;
}


message GetUserListReq {
  int32 pageNum = 1;
  int32 pageSize = 2;
  string nickname = 3;
  string email = 4;
  int32 status = 5;
  string sort = 6;
  string weChat = 7;
  string phone = 8;
  int32 mailStatus = 9;
}

message GetUserListResp {
  uint64 total = 1;
  repeated UserItem data = 2;
}


message DeleteUserReq{
  uint64 userId = 1;
}
message DeleteUserResp {
  string pong = 1;
}
message BanUserReq {
  uint64 userId = 1;
}
message BanUserResp {
  string pong = 1;
}

message UpdateUserReq{
  uint64 userId = 1;
  string nickname = 2;
  string email = 3;
  string phone = 4;
  string motto = 5;
  string address = 6;
  string location = 7;
  int32 age = 8;
  int32 gender = 9;
  string profession = 10;
  int32 mailStatus = 11;
}

message UpdateUserResp {
  string pong = 1;
}




message UpdateEmailStatusReq {
  uint64 userId = 1;
  int32 mailStatus = 2;
}
message UpdateEmailStatusResp {
  string pong = 1;
}
message GenerateCaptchaResp{
  string key = 1;
  string base64Img = 2;
}
message VerifyCaptchaReq {
  string key = 1;
  string captcha = 2;
}
message VerifyCaptchaResp {
  bool isCorrect = 1;
}

message UpdatePasswordReq {
  uint64 userId = 1;
  string oldPassword = 2;
  string newPassword = 3;
}

message UpdatePasswordResp {
  string pong = 1;
}

message UpdateAvatarReq {
  string avatar = 1;
  uint64 userId = 2;
}
message UpdateAvatarResp {
  string pong = 1;
}

message UpdateProfileBgReq {
  string profileBg = 1;
  uint64 userId = 2;
}
message UpdateProfileBgResp {
  string pong = 1;
}

// =================Following=================

message FollowingItem {
  uint64 id = 1;
  uint64 userId = 2;
  uint64 followingId = 3;
  uint64 createdAt = 4;
  uint64 updatedAt = 5;
}

message AddFollowingReq {
  uint64 id = 1;
  uint64 userId = 2;
  uint64 followingId = 3;
}
message AddFollowingResp {
  string pong = 1;
}

message DeleteFollowingReq {
  uint64 id = 1;
}
message DeleteFollowingResp {
  string pong = 1;
}

message GetFollowingListReq {
  uint64 userId = 1;
  uint64 followingId = 2;
  int32 pageNum = 3;
  int32 pageSize = 4;
}
message GetFollowingListResp {
  uint64 total = 1;
  repeated FollowingItem data = 2;
}

// =================Follower=================

message FollowerItem {
  uint64 id = 1;
  uint64 userId = 2;
  uint64 followerId = 3;
  uint64 createdAt = 4;
  uint64 updatedAt = 5;
}

message AddFollowerReq {
  uint64 id = 1;
  uint64 userId = 2;
  uint64 followerId = 3;
}
message AddFollowerResp {
  string pong = 1;
}

message DeleteFollowerReq {
  uint64 id = 1;
}
message DeleteFollowerResp {
  string pong = 1;
}

message GetFollowerListReq {
  uint64 userId = 1;
  uint64 followerId = 2;
  int32 pageNum = 3;
  int32 pageSize = 4;
}
message GetFollowerListResp {
  uint64 total = 1;
  repeated FollowerItem data = 2;
}

// =================BlackItem=================

message BlackItem {
  uint64 id = 1;
  uint64 userId = 2;
  uint64 blackItemId = 3;
  uint64 createdAt = 4;
  uint64 updatedAt = 5;
}

message AddBlackItemReq {
  uint64 id = 1;
  uint64 userId = 2;
  uint64 blackItemId = 3;
}
message AddBlackItemResp {
  string pong = 1;
}

message DeleteBlackItemReq {
  uint64 id = 1;
}
message DeleteBlackItemResp {
  string pong = 1;
}

message GetBlackListReq {
  uint64 userId = 1;
  uint64 blackItemId = 2;
  int32 pageNum = 3;
  int32 pageSize = 4;
}
message GetBlackListResp {
  uint64 total = 1;
  repeated BlackItem data = 2;
}

service User {
  // group: role
  rpc GetRoleInfo(GetRoleInfoReq) returns(GetRoleInfoResp);
  // group: user
  rpc Register(RegisterReq) returns(RegisterResp);
  // group: user
  rpc Login(LoginReq) returns(LoginResp);
  // group: user
  rpc CheckNicknameExist(CheckNicknameExistReq) returns(CheckNicknameExistResp);
  // group: user
  rpc CheckEmailExist(CheckEmailExistReq) returns(CheckEmailExistResp);
  // group: user
  rpc GetUserById(GetUserByIdReq) returns(GetUserByIdResp);
  // group: user
  rpc GetUserList(GetUserListReq) returns(GetUserListResp);
  // group: user
  rpc DeleteUser(DeleteUserReq) returns(DeleteUserResp);
  // group: user
  rpc BanUser(BanUserReq) returns(BanUserResp);
  // group: user
  rpc UpdateUser(UpdateUserReq) returns(UpdateUserResp);
  // group: user
  rpc UpdatePassword(UpdatePasswordReq) returns(UpdatePasswordResp);
  // group: user
  rpc UpdateEmailStatus(UpdateEmailStatusReq) returns(UpdateEmailStatusResp);
  // group: user
  rpc UpdateAvatar(UpdateAvatarReq) returns(UpdateAvatarResp);
  // group: user
  rpc UpdateProfileBg(UpdateProfileBgReq) returns(UpdateProfileBgResp);

  // group: email
  rpc VerifyRegisterCode(VerifyRegisterCodeReq) returns(VerifyRegisterCodeResp);

  // group: captcha
  rpc GenerateCaptcha(Empty) returns(GenerateCaptchaResp);
  // group: captcha
  rpc VerifyCaptcha(VerifyCaptchaReq) returns(VerifyCaptchaResp);

  // group: following
  rpc AddFollowing(AddFollowingReq) returns(AddFollowingResp);
  // group: following
  rpc DeleteFollowing(DeleteFollowingReq) returns(DeleteFollowingResp);
  // group: following
  rpc GetFollowingList(GetFollowingListReq) returns(GetFollowingListResp);

  // group: follower
  rpc AddFollower(AddFollowerReq) returns(AddFollowerResp);
  // group: follower
  rpc DeleteFollower(DeleteFollowerReq) returns(DeleteFollowerResp);
  // group: follower
  rpc GetFollowerList(GetFollowerListReq) returns(GetFollowerListResp);

  // group: blacklist
  rpc AddBlackItem(AddBlackItemReq) returns(AddBlackItemResp);
  // group: blacklist
  rpc DeleteBlackItem(DeleteBlackItemReq) returns(DeleteBlackItemResp);
  // group: blacklist
  rpc GetBlackList(GetBlackListReq) returns(GetBlackListResp);

}

