syntax = "proto3";

package user;
option go_package="./user";

message Empty{}

message OkResp{
  string pong = 1;
}

//===========================Email============================
message VerifyRegisterCodeReq {
    string code = 1;
}
message VerifyForgotEemailCodeReq{
  string code = 1;
}
message VerifyRegisterCodeResp {
    string codeContent = 1;
}
service EmailClass {
  rpc VerifyRegisterCode(VerifyRegisterCodeReq) returns(VerifyRegisterCodeResp);
  rpc VerifyForgotEemailCode(VerifyForgotEemailCodeReq) returns(VerifyRegisterCodeResp);
}

//===========================Captcha============================
message GenerateCaptchaResp{
  string key = 1;
  string base64Img = 2;
}
message VerifyCaptchaReq {
  string key = 1;
  string captcha = 2;
}
message VerifyCaptchaResp {
  bool isCorrect = 1;
}
service CaptchaClass {
  // group: captcha
  rpc GenerateCaptcha(Empty) returns(GenerateCaptchaResp);
  // group: captcha
  rpc VerifyCaptcha(VerifyCaptchaReq) returns(VerifyCaptchaResp);
}


//===========================Role============================
message RoleItem {
    uint64 id = 1;
    string name = 2;
    uint64 createdAt = 3;
    uint64 updatedAt = 4;
}
message GetRoleInfoReq {
    uint64 id = 1;
}
message GetRoleInfoResp {
    RoleItem Role = 1;
}
service RoleClass {
  // group: role
  rpc GetRoleInfo(GetRoleInfoReq) returns(GetRoleInfoResp);
}

//===========================User============================
message UserItem {
  uint64 id = 1;
  uint64 roleId = 2;
  string nickname = 3;
  string email = 4;
  string phone = 5;
  string weChat = 6;
  string motto = 7;
  string avatar = 8;
  string profileBg = 9;
  string birthday = 10;
  int32 gender = 11;
  int32 status = 12;
  string location = 13;
  int32 level = 14;
  int32 score = 15;
  uint64 createdAt = 16;
  uint64 updatedAt = 17;
  uint64 lastLoginTime = 18;
  int32 authType = 19;
  int32 mailStatus = 20;
  string password = 21;
  string address = 22;
  string profession = 23;
}

message RegisterReq {
  uint64 id = 1;
  uint64 roleId = 2;
  string nickname = 3;
  string email = 4;
  string password = 5;
  string phone = 6;
  int32 authType = 7;
}

message RegisterResp {
  UserItem user = 1;
}

message ForgotPasswordReq{
  string email = 1;
  uint64 userId = 2;
}

message LoginReq {
  string token = 1;
  string tokenKey = 2;
  uint64 expireAt = 3;
}

message LoginResp {
  string pong = 1;
}
message LogoutReq {
  string tokenKey = 1;
}
message LogoutResp {
  string pong = 1;
}
message GetTokenReq{
  string tokenKey = 1;
}
message GetTokenResp {
  string token = 1;
}

message CheckNicknameExistReq{
  string nickname = 1;
}

message CheckEmailExistReq {
  string email = 1;
}

message CheckEmailExistResp {
  bool isExist = 1;
  UserItem user = 2;
}

message CheckNicknameExistResp {
  bool isExist = 1;
  UserItem user = 2;
}

message GetUserByIdReq {
  uint64 userId = 1;
}
message GetUserByIdResp {
  UserItem user = 1;
}

message GetUserListReq {
  int32 pageNum = 1;
  int32 pageSize = 2;
  string nickname = 3;
  string email = 4;
  int32 status = 5;
  string sort = 6;
  string weChat = 7;
  string phone = 8;
  int32 mailStatus = 9;
}

message GetUserListResp {
  uint64 total = 1;
  repeated UserItem data = 2;
}

message DeleteUserReq{
  uint64 userId = 1;
}
message DeleteUserResp {
  string pong = 1;
}
message BanUserReq {
  uint64 userId = 1;
}
message BanUserResp {
  string pong = 1;
}

message UpdateUserReq{
  uint64 userId = 1;
  string nickname = 2;
  string email = 3;
  string phone = 4;
  string motto = 5;
  string address = 6;
  string location = 7;
  string birthday = 8;
  int32 gender = 9;
  string profession = 10;
  int32 mailStatus = 11;
}

message UpdateUserResp {
  string pong = 1;
}

message UpdateUserScoreLevelReq {
  uint64 Id = 1;
  int32 score = 2;
  string op = 3; // "add" || "sub"
}

message UpdateUserScoreLevelResp {
  string pong = 1;
}

message UpdateEmailStatusReq {
  uint64 userId = 1;
  int32 mailStatus = 2;
}
message UpdateEmailStatusResp {
  string pong = 1;
}

message UpdatePasswordReq {
  uint64 userId = 1;
  string oldPassword = 2;
  string newPassword = 3;
}

message UpdatePasswordResp {
  string pong = 1;
}

message UpdateAvatarReq {
  string avatar = 1;
  uint64 userId = 2;
}
message UpdateAvatarResp {
  string pong = 1;
}

message UpdateProfileBgReq {
  string profileBg = 1;
  uint64 userId = 2;
}
message UpdateProfileBgResp {
  string pong = 1;
}
service UserClass {
  rpc Register(RegisterReq) returns(RegisterResp);
  rpc Login(LoginReq) returns(LoginResp);
  rpc Logout(LogoutReq) returns(LogoutResp);
  rpc GetToken(GetTokenReq) returns(GetTokenResp);
  rpc CheckNicknameExist(CheckNicknameExistReq) returns(CheckNicknameExistResp);
  rpc CheckEmailExist(CheckEmailExistReq) returns(CheckEmailExistResp);
  rpc GetUserById(GetUserByIdReq) returns(GetUserByIdResp);
  rpc GetUserList(GetUserListReq) returns(GetUserListResp);
  rpc DeleteUser(DeleteUserReq) returns(DeleteUserResp);
  rpc BanUser(BanUserReq) returns(BanUserResp);
  rpc UpdateUser(UpdateUserReq) returns(UpdateUserResp);
  rpc UpdatePassword(UpdatePasswordReq) returns(UpdatePasswordResp);
  rpc UpdateEmailStatus(UpdateEmailStatusReq) returns(UpdateEmailStatusResp);
  rpc UpdateUserScoreLevel(UpdateUserScoreLevelReq) returns(UpdateUserScoreLevelResp);
  rpc UpdateAvatar(UpdateAvatarReq) returns(UpdateAvatarResp);
  rpc UpdateProfileBg(UpdateProfileBgReq) returns(UpdateProfileBgResp);
  rpc ForgotPassword(ForgotPasswordReq) returns(OkResp);
}

// =================Following=================
message FollowingItem {
  uint64 id = 1;
  uint64 userId = 2;
  uint64 followingId = 3;
  uint64 createdAt = 4;
  uint64 updatedAt = 5;
}

message AddFollowingReq {
  uint64 id = 1;
  uint64 userId = 2;
  uint64 followingId = 3;
}
message AddFollowingResp {
  string pong = 1;
}

message DeleteFollowingReq {
  uint64 id = 1;
}
message DeleteFollowingResp {
  string pong = 1;
}

message GetFollowingListReq {
  uint64 userId = 1;
  uint64 followingId = 2;
  int32 pageNum = 3;
  int32 pageSize = 4;
}
message GetFollowingListResp {
  uint64 total = 1;
  repeated FollowingItem data = 2;
}
message GetFollowingDetailReq {
  uint64 id = 1;
}
message GetFollowingDetailResp {
  FollowingItem data = 1;
}
message CheckFollowingReq {
  uint64 userId = 1;
  uint64 followingId = 2;
}
message CheckFollowingResp {
  bool isFollowing = 1;
}

service FollowingClass {
  rpc AddFollowing(AddFollowingReq) returns(AddFollowingResp);
  rpc DeleteFollowing(DeleteFollowingReq) returns(DeleteFollowingResp);
  rpc GetFollowingList(GetFollowingListReq) returns(GetFollowingListResp);
  rpc GetFollowingDetail(GetFollowingDetailReq) returns(GetFollowingDetailResp);
  rpc CheckFollowing(CheckFollowingReq) returns(CheckFollowingResp);
}

// =================BlackItem=================
message BlackItem {
  uint64 id = 1;
  uint64 userId = 2;
  uint64 blackItemId = 3;
  uint64 createdAt = 4;
  uint64 updatedAt = 5;
}

message AddBlackItemReq {
  uint64 id = 1;
  uint64 userId = 2;
  uint64 blackItemId = 3;
}
message AddBlackItemResp {
  string pong = 1;
}

message DeleteBlackItemReq {
  uint64 id = 1;
}
message DeleteBlackItemResp {
  string pong = 1;
}

message GetBlackListReq {
  uint64 userId = 1;
  uint64 blackItemId = 2;
  int32 pageNum = 3;
  int32 pageSize = 4;
}
message GetBlackListResp {
  uint64 total = 1;
  repeated BlackItem data = 2;
}
message CheckBlackItemReq {
  uint64 userId = 1;
  uint64 blackItemId = 2;
}
message CheckBlackItemResp {
  bool isBlackItem = 1;
}
service BlacklistClass {
  rpc AddBlackItem(AddBlackItemReq) returns(AddBlackItemResp);
  rpc DeleteBlackItem(DeleteBlackItemReq) returns(DeleteBlackItemResp);
  rpc GetBlackList(GetBlackListReq) returns(GetBlackListResp);
  rpc CheckBlackItem(CheckBlackItemReq) returns(CheckBlackItemResp);
}

// =================Notification=================
message NotificationItem {
  uint64 Id = 1;
  uint64 senderUserId = 2;
  uint64 receiverUserId = 3;
  uint64 commentId = 4;
  string commentContent = 5;
  uint64 replyId = 6;
  string replyContent = 7;
  string message = 8;
  uint64 targetId = 9;
  string targetTitle = 10;
  int32 bizType = 11;
  int32 isRead = 12;
  int32 actionType = 13;
  uint64 CreatedAt = 14;
  uint64 UpdatedAt = 15;
}

message AddNotificationReq {
  uint64 Id = 1;
  uint64 senderUserId = 2;
  uint64 receiverUserId = 3;
  uint64 commentId = 4;
  string commentContent = 5;
  uint64 replyId = 6;
  string replyContent = 7;
  string message = 8;
  uint64 targetId = 9;
  string targetTitle = 10;
  int32 bizType = 11; // 1表示动态，2表示文章,3表示其它
  int32 isRead = 12;
  int32 type = 13; // 1表示评论通知，2表示点赞和收藏通知，3表示新增粉丝通知，4表示系统通知
  int32 actionType = 14; // 1点赞，2收藏，3分享
}
message SetAllReadNotificationReq {
  int32 type = 1;  
  uint64 receiverUserId = 2;
}
message GetUnreadsNotificationCountReq{
  uint64 receiverUserId = 1;
}
message GetUnreadsNotificationCountResp{
  uint64 commentCount = 1;
  uint64 followCount = 2;
  uint64 likeCount = 3;
  uint64 osCount = 4;
  uint64 total = 5;
}
message GetNotificationListReq {
  int32 type = 1;
  uint64 receiverUserId = 2;
  int64 pageNum = 3;
  int64 pageSize = 4;
}
message GetNotificationListResp {
  repeated NotificationItem data = 1;
  uint64 total = 2;
}

service NotificationClass {
  rpc AddNotification(AddNotificationReq) returns(OkResp);
  rpc SetAllReadNotification(SetAllReadNotificationReq) returns(OkResp);
  rpc GetUnreadsNotificationCount(GetUnreadsNotificationCountReq) returns(GetUnreadsNotificationCountResp);
  rpc GetNotificationList(GetNotificationListReq) returns(GetNotificationListResp);
}
