// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	article "qinglv-backend/app/content/api/internal/handler/article"
	category "qinglv-backend/app/content/api/internal/handler/category"
	draft "qinglv-backend/app/content/api/internal/handler/draft"
	post "qinglv-backend/app/content/api/internal/handler/post"
	tag "qinglv-backend/app/content/api/internal/handler/tag"
	topic "qinglv-backend/app/content/api/internal/handler/topic"
	upload "qinglv-backend/app/content/api/internal/handler/upload"
	"qinglv-backend/app/content/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/article",
				Handler: article.GetArticleListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/article/:id",
				Handler: article.GetArticleByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/article",
				Handler: article.GetUserArticleListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/content/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authority},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/article",
					Handler: article.AddArticleHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/article",
					Handler: article.UpdateArticleHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/article/:id",
					Handler: article.DeleteArticleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/article/following",
					Handler: article.GetFollowingArticleListHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JWTAuth.AccessSecret),
		rest.WithPrefix("/content/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/category",
				Handler: category.GetCategoryListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/category/:id",
				Handler: category.GetCategoryByIdHandler(serverCtx),
			},
		},
		rest.WithPrefix("/content/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authority},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/category",
					Handler: category.AddCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/category/:id",
					Handler: category.DeleteCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/category/:id",
					Handler: category.UpdateCategoryHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JWTAuth.AccessSecret),
		rest.WithPrefix("/content/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authority},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/draft",
					Handler: draft.AddDraftHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/draft",
					Handler: draft.UpdateDraftHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/draft",
					Handler: draft.GetDraftListHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/draft/:id",
					Handler: draft.DeleteDraftHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/draft/:id",
					Handler: draft.GetDrafByIdHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JWTAuth.AccessSecret),
		rest.WithPrefix("/content/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/post",
				Handler: post.GetPostListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/post/:id",
				Handler: post.GetPostByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/post",
				Handler: post.GetUserPostListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/content/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authority},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/post",
					Handler: post.AddPostHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/post/:id",
					Handler: post.DeletePostHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/post/following",
					Handler: post.GetFollowingPostListHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JWTAuth.AccessSecret),
		rest.WithPrefix("/content/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/tag",
				Handler: tag.GetTagListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tag/:id",
				Handler: tag.GetTagByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tag/name",
				Handler: tag.GetTagByNameHandler(serverCtx),
			},
		},
		rest.WithPrefix("/content/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authority},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/tag",
					Handler: tag.AddTagHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/tag/:id",
					Handler: tag.DeleteTagHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/tag/:id",
					Handler: tag.UpdateTagHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JWTAuth.AccessSecret),
		rest.WithPrefix("/content/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/topic",
				Handler: topic.GetTopicListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/topic/:id",
				Handler: topic.GetTopicByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/topic/name",
				Handler: topic.GetTopicByNameHandler(serverCtx),
			},
		},
		rest.WithPrefix("/content/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authority},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/topic",
					Handler: topic.AddTopicHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/topic/:id",
					Handler: topic.DeleteTopicHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/topic/:id",
					Handler: topic.UpdateTopicHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JWTAuth.AccessSecret),
		rest.WithPrefix("/content/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authority},
			[]rest.Route{
				{
					Method:  http.MethodDelete,
					Path:    "/image/remove",
					Handler: upload.RemoveImagesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/image/upload/:type",
					Handler: upload.UploadImagesHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JWTAuth.AccessSecret),
		rest.WithPrefix("/content/v1"),
	)
}
