// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	category "qinglv-backend/app/content/api/internal/handler/category"
	post "qinglv-backend/app/content/api/internal/handler/post"
	topic "qinglv-backend/app/content/api/internal/handler/topic"
	"qinglv-backend/app/content/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/category",
				Handler: category.GetCategoryListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/category/:id",
				Handler: category.GetCategoryByIdHandler(serverCtx),
			},
		},
		rest.WithPrefix("/content/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/category",
				Handler: category.AddCategoryHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/category/:id",
				Handler: category.DeleteCategoryHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/category/:id",
				Handler: category.UpdateCategoryHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JWTAuth.AccessSecret),
		rest.WithPrefix("/content/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/post",
				Handler: post.GetPostListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/post/:id",
				Handler: post.GetPostByIdHandler(serverCtx),
			},
		},
		rest.WithPrefix("/content/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/post",
				Handler: post.AddPostHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/post/:id",
				Handler: post.DeletePostHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/post/user/:id",
				Handler: post.GetUserPostListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JWTAuth.AccessSecret),
		rest.WithPrefix("/content/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/topic",
				Handler: topic.GetTopicListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/topic/:id",
				Handler: topic.GetTopicByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/topic/name",
				Handler: topic.GetTopicByNameHandler(serverCtx),
			},
		},
		rest.WithPrefix("/content/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/topic",
				Handler: topic.AddTopicHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/topic/:id",
				Handler: topic.DeleteTopicHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/topic/:id",
				Handler: topic.UpdateTopicHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JWTAuth.AccessSecret),
		rest.WithPrefix("/content/v1"),
	)
}
