syntax = "proto3";

package operation;
option go_package="./operation";

message OkResp {
    string pong = 1;
}

//==========================CollectionGroup==========================
message CollectionGroupItem {
    uint64 id = 1;
    uint64 creatorId = 2;
    string name = 3;
    int32 bizType = 4;
    int32 visibility = 5;
    uint64 createdAt = 6;
    uint64 updatedAt = 7;
}
message AddCollectionGroupReq {
    uint64 id = 1;
    uint64 creatorId = 2;
    string name = 3;
    int32 bizType = 4;
    int32 visibility = 5;
}
message GetCollectionGroupListReq{
    string name = 1;
    int32 bizType = 2;
    int32 visibility = 3;
    uint64 creatorId = 4;
    int32 pageNum  = 5;
    int32 pageSize = 6;
}
message GetCollectionGroupListResp{
    repeated CollectionGroupItem Data = 1;
    uint64 total = 2;
}
message GetCollectionGroupByIdReq {
    uint64 id = 1;
}
message GetCollectionGroupByIdResp {
    CollectionGroupItem collectionGroup = 1;
}
message CheckExistByNameReq{
    uint64 creatorId = 1;
    string name = 2;
    int32 bizType = 3;
}
message CheckExistByNameResp{
    repeated CollectionGroupItem Data = 1;
    uint64 total = 2;
}
message UpdateCollectionGroupReq{
    uint64 id = 1;
    uint64 creatorId = 2;
    string name = 3;
    int32 bizType = 4;
    int32 visibility = 5;
    uint64 createdAt = 6;
    uint64 updatedAt = 7;
}
message DeleteCollectionGroupReq {
    uint64 id = 1;
}

//==========================CollectionGroup==========================

message CollectionItem {
    uint64 id = 1;
    uint64 groupId = 2;
    uint64 targetId = 3;
    uint64 creatorId = 4;
    uint64 createdAt = 5;
    uint64 updatedAt = 6;
}
message AddCollectionReq {
    uint64 id = 1;
    uint64 groupId = 2;
    uint64 targetId = 3;
    uint64 creatorId = 4;
}
message DeleteCollectionReq{
    uint64 id = 1;
}
message GetCollectionListReq{
    uint64 groupId = 1;
    uint64 CreatorId = 2;
    uint64 pageNum = 3;
    uint64 pageSize = 4;
}
message GetCollectionListResp{
    repeated CollectionItem data = 1;
    uint64 total = 2;
}
message GetCollectionByIdReq{
    uint64 id = 1;
}
message GetCollectionByIdResp{
    CollectionItem collection = 1;
}

//==========================Share==========================

message AddPostShareReq {
    uint64 id = 1;
    uint64 creatorId = 2;
    uint64 postId = 3;
    int32 type = 4;
}

//==========================Thumb==========================

message PostThumbItem {
    uint64 id = 1;
    uint64 creatorId = 2;
    uint64 postId = 3;
    int32 like = 4;
    int32 dislike = 5; 
    uint64 createdAt = 6;
    uint64 updatedAt = 7;
}
message AddPostThumbReq{
    uint64 id = 1;
    uint64 creatorId = 2;
    uint64 postId = 3;
    int32 like = 4;
    int32 dislike = 5;
}
message UpdatePostThumbReq{
    uint64 id = 1;
    int32 like = 2;
    int32 dislike = 3;
}
message GetPostThumbByIdReq {
    uint64 postId = 1;
    uint64 pageNum = 2;
    uint64 pageSize = 3;
}
message GetPostThumbByIdResp {
    repeated PostThumbItem data = 1;
    uint64 total = 2;
}

service Operation {
    // group: CollectionGroup
    rpc AddCollectionGroup(AddCollectionGroupReq) returns(OkResp);
    // group: CollectionGroup
    rpc GetCollectionGroupList(GetCollectionGroupListReq) returns(GetCollectionGroupListResp);
    // group: CollectionGroup
    rpc GetCollectionGroupById(GetCollectionGroupByIdReq) returns(GetCollectionGroupByIdResp);
    // group: CollectionGroup
    rpc CheckExistByName(CheckExistByNameReq) returns(CheckExistByNameResp);
    // group: CollectionGroup
    rpc UpdateCollectionGroup(UpdateCollectionGroupReq) returns(OkResp);
    // group: CollectionGroup
    rpc DeleteCollectionGroup(DeleteCollectionGroupReq) returns(OkResp);

    // group: Collection
    rpc AddCollection(AddCollectionReq) returns(OkResp);
    // group: Collection
    rpc DeleteCollection(DeleteCollectionReq) returns(OkResp);
    // group: Collection
    rpc GetCollectionList(GetCollectionListReq) returns(GetCollectionListResp);
    // group: Collection
    rpc GetCollectionById(GetCollectionByIdReq) returns(GetCollectionByIdResp);

    // group: Share
    rpc AddPostShare(AddPostShareReq) returns(OkResp);

    // group: PostThumb
    rpc AddPostThumb(AddPostThumbReq) returns(OkResp);
    // group: PostThumb
    rpc UpdatePostThumb(UpdatePostThumbReq) returns(OkResp);
    // group: PostThumb
    rpc GetPostThumbById(GetPostThumbByIdReq) returns(GetPostThumbByIdResp);
}