syntax = "proto3";

package operation;
option go_package="./operation";

message OkResp {
    string pong = 1;
}

//==========================Collection==========================
message CollectionGroupItem {
    uint64 id = 1;
    uint64 creatorId = 2;
    string name = 3;
    int32 bizType = 4;
    int32 visibility = 5;
    uint64 createdAt = 6;
    uint64 updatedAt = 7;
}
message AddCollectionGroupReq {
    uint64 id = 1;
    uint64 creatorId = 2;
    string name = 3;
    int32 bizType = 4;
    int32 visibility = 5;
}
message GetCollectionGroupListReq{
    string name = 1;
    int32 bizType = 2;
    int32 visibility = 3;
    uint64 creatorId = 4;
    int32 pageNum  = 5;
    int32 pageSize = 6;
}
message GetCollectionGroupListResp{
    repeated CollectionGroupItem Data = 1;
    uint64 total = 2;
}
message GetCollectionGroupByIdReq {
    uint64 id = 1;
}
message GetCollectionGroupByIdResp {
    CollectionGroupItem collectionGroup = 1;
}
message CheckExistByNameReq{
    uint64 creatorId = 1;
    string name = 2;
    int32 bizType = 3;
}
message CheckExistByNameResp{
    repeated CollectionGroupItem Data = 1;
    uint64 total = 2;
}
message UpdateCollectionGroupReq{
    uint64 id = 1;
    uint64 creatorId = 2;
    string name = 3;
    int32 bizType = 4;
    int32 visibility = 5;
    uint64 createdAt = 6;
    uint64 updatedAt = 7;
}
message DeleteCollectionGroupReq {
    uint64 id = 1;
}
message CollectionItem {
    uint64 id = 1;
    uint64 groupId = 2;
    uint64 targetId = 3;
    uint64 creatorId = 4;
    uint64 createdAt = 5;
    uint64 updatedAt = 6;
}
message AddCollectionReq {
    uint64 id = 1;
    uint64 groupId = 2;
    uint64 targetId = 3;
    uint64 creatorId = 4;
}
message DeleteCollectionReq{
    uint64 id = 1;
}
message GetCollectionListReq{
    uint64 groupId = 1;
    uint64 CreatorId = 2;
    uint64 pageNum = 3;
    uint64 pageSize = 4;
}
message GetCollectionListResp{
    repeated CollectionItem data = 1;
    uint64 total = 2;
}
message GetCollectionByIdReq{
    uint64 id = 1;
}
message GetCollectionByIdResp{
    CollectionItem collection = 1;
}
service CollectionClass{
    // group: Collection
    rpc AddCollectionGroup(AddCollectionGroupReq) returns(OkResp);
    // group: Collection
    rpc GetCollectionGroupList(GetCollectionGroupListReq) returns(GetCollectionGroupListResp);
    // group: Collection
    rpc GetCollectionGroupById(GetCollectionGroupByIdReq) returns(GetCollectionGroupByIdResp);
    // group: Collection
    rpc CheckExistByName(CheckExistByNameReq) returns(CheckExistByNameResp);
    // group: Collection
    rpc UpdateCollectionGroup(UpdateCollectionGroupReq) returns(OkResp);
    // group: Collection
    rpc DeleteCollectionGroup(DeleteCollectionGroupReq) returns(OkResp);
    // group: Collection
    rpc AddCollection(AddCollectionReq) returns(OkResp);
    // group: Collection
    rpc DeleteCollection(DeleteCollectionReq) returns(OkResp);
    // group: Collection
    rpc GetCollectionList(GetCollectionListReq) returns(GetCollectionListResp);
    // group: Collection
    rpc GetCollectionById(GetCollectionByIdReq) returns(GetCollectionByIdResp);
}

//==========================Share==========================

message AddPostShareReq {
    uint64 id = 1;
    uint64 creatorId = 2;
    uint64 postId = 3;
    int32 type = 4;
}
service ShareClass{
    // group: Share
    rpc AddPostShare(AddPostShareReq) returns(OkResp);
}

//==========================Thumb==========================

message PostThumbItem {
    uint64 id = 1;
    uint64 creatorId = 2;
    uint64 postId = 3;
    int32 like = 4;
    int32 dislike = 5; 
    uint64 createdAt = 6;
    uint64 updatedAt = 7;
}
message ArticleThumbItem {
    uint64 id = 1;
    uint64 creatorId = 2;
    uint64 articleId = 3;
    int32 like = 4;
    int32 dislike = 5; 
    uint64 createdAt = 6;
    uint64 updatedAt = 7;
}
message AddThumbReq{
    uint64 id = 1;
    uint64 creatorId = 2;
    uint64 postId = 3;
    uint64 articleId = 4;
    uint64 videoId = 5;
    int32 like = 6;
    int32 dislike = 7;
    int32 type = 8; // 1帖子，2文章，3视频
}
message UpdateThumbReq{
    uint64 id = 1;
    int32 like = 2;
    int32 dislike = 3;
    int32 type = 4;
}
message GetThumbDetailReq {
    uint64 postId = 1;
    uint64 creatorId = 2;
    int32 type = 3;
}
message GetThumbDetailResp {
    repeated PostThumbItem post = 1;
    repeated ArticleThumbItem article = 2;
}


message PostCommentThumbItem {
    uint64 id = 1;
    uint64 creatorId = 2;
    uint64 postId = 3;
    uint64 commentId = 4;
    uint64 replyId = 5;
    int32 commentType = 6;
    int32 like = 7;
    int32 dislike = 8; 
    uint64 createdAt = 9;
    uint64 updatedAt = 10;
    string creatorName = 11;
}
message ArticleCommentThumbItem {
    uint64 id = 1;
    uint64 creatorId = 2;
    uint64 articleId = 3;
    uint64 commentId = 4;
    uint64 replyId = 5;
    int32 commentType = 6;
    int32 like = 7;
    int32 dislike = 8; 
    uint64 createdAt = 9;
    uint64 updatedAt = 10;
    string creatorName = 11;
}
message AddCommentThumbReq{
    uint64 id = 1;
    uint64 creatorId = 2;
    uint64 postId = 3;
    uint64 articleId = 4;
    uint64 commentId = 5;
    uint64 videoId = 6;
    uint64 replyId = 7;
    uint64 commentType = 8;
    int32 like = 9;
    int32 dislike = 10;
    int32 type = 11; // 1帖子，2文章，3视频
    string creatorName = 12;
}
message UpdateCommentThumbReq{
    uint64 id = 1;
    int32 like = 2;
    int32 dislike = 3;
    int32 type = 4;
}
message GetCommentThumbDetailReq {
    uint64 postId = 1;
    uint64 creatorId = 2;
    uint64 commentId = 3;
    uint64 replyId = 4;
    int32 commentType = 5;    
    int32 type = 6;
}
message GetCommentThumbDetailResp {
    repeated PostCommentThumbItem post = 1;
    repeated ArticleCommentThumbItem article = 2;
}

service ThumbClass {
    // group: Thumb
    rpc AddThumb(AddThumbReq) returns(OkResp);
    // group: PostThumb
    rpc UpdateThumb(UpdateThumbReq) returns(OkResp);
    // group: PostThumb
    rpc GetThumbDetail(GetThumbDetailReq) returns(GetThumbDetailResp);

    // group: CommentThumb
    rpc AddCommentThumb(AddCommentThumbReq) returns(OkResp);
    // group: PostCommentThumb
    rpc UpdateCommentThumb(UpdateCommentThumbReq) returns(OkResp);
    // group: PostCommentThumb
    rpc GetCommentThumbDetail(GetCommentThumbDetailReq) returns(GetCommentThumbDetailReq);
}

//==========================Comment==========================
message ArticleCommentItem {
    uint64 id = 1;
    uint64 creatorId = 2;
    uint64 article = 3;
    string content = 4;
    string location = 5;
    uint64 likeCount = 6;
    uint64 dislikeCount = 7;
    uint64 score = 8;
    uint64 createdAt = 9;
    uint64 updatedAt = 10;
    string creatorName = 11;
}
message PostCommentItem {
    uint64 id = 1;
    uint64 creatorId = 2;
    uint64 postId = 3;
    string content = 4;
    string location = 5;
    uint64 likeCount = 6;
    uint64 dislikeCount = 7;
    uint64 score = 8;
    uint64 createdAt = 9;
    uint64 updatedAt = 10;
    string creatorName = 11;
}
message AddCommentReq {
    uint64 id = 1;
    uint64 creatorId = 2;
    uint64 postId = 3;
    uint64 articleId = 4;
    uint64 videoId = 6;
    string content = 7;
    string location = 8;
    string creatorName = 9;
    int32 type = 10; // 1帖子，2文章，3视频
}
message DeleteCommentReq{
    uint64 id = 1;
    int32 type = 12; // 1帖子，2文章，3视频
}
message GetCommentListReq {
    uint64 postId = 1;
    uint64 articleId = 2;
    uint64 videoId = 3;
    uint64 creatorId = 4;
    uint64 pageNum = 5;
    uint64 pageSize = 6;
    string sort = 7;
    int32 type = 8; // 1帖子，2文章，3视频
}
message PostCommentResp {
    repeated PostCommentItem data = 1;
    uint64 total = 2;
}
message GetCommentByIdReq {
    uint64 id  = 1;
    int32 type = 2;
}
message GetCommentByIdResp {
    ArticleCommentItem articleComment = 1;
    PostCommentItem postComment = 2;
}
message GetCommentReplyByIdReq {
    uint64 id  = 1;
    int32 type = 2;
}
message GetCommentReplyByIdResp {
    ArticleCommentReplyItem articleCommentReply = 1;
    PostCommentReplyItem postCommentReply = 2;
}
message ArticleCommentResp {
    repeated ArticleCommentItem data = 1;
    uint64 total = 2;
}
message GetCommentListResp {
    PostCommentResp post = 1;
    ArticleCommentResp article = 2;

}

message ArticleCommentReplyItem {
    uint64 id = 1;
    uint64 creatorId = 2;
    uint64 article = 3;
    uint64 content = 4;
    string location = 5;
    uint64 likeCount = 6;
    uint64 dislikeCount = 7;
    uint64 score = 8;
    uint64 createdAt = 9;
    uint64 updatedAt = 10;
    string creatorName = 11;
    uint64 commentId = 12;
    uint64 atUserId = 13;
    string atUserNickname = 14;
}
message PostCommentReplyItem {
    uint64 id = 1;
    uint64 creatorId = 2;
    uint64 postId = 3;
    string content = 4;
    string location = 5;
    uint64 likeCount = 6;
    uint64 dislikeCount = 7;
    uint64 score = 8;
    uint64 createdAt = 9;
    uint64 updatedAt = 10;
    string creatorName = 11;
    uint64 commentId = 12;
    uint64 atUserId = 13;
    string atUserNickname = 14;
}
message AddCommentReplyReq {
    uint64 id = 1;
    uint64 creatorId = 2;
    uint64 postId = 3;
    uint64 articleId = 4;
    uint64 videoId = 5;
    string content = 6;
    string location = 7;
    string creatorName = 8;
    uint64 atUserId = 9;
    string atUserNickname = 10;
    uint64 commentId = 11;
    int32 type = 12; // 1帖子，2文章，3视频
}
message DeleteCommentReplyReq{
    uint64 id = 1;
    int32 type = 2; // 1帖子，2文章，3视频
}
message GetCommentReplyListReq {
    uint64 postId = 1;
    uint64 articleId = 2;
    uint64 videoId = 3;
    uint64 commentId = 4;
    uint64 creatorId = 5;
    uint64 pageNum = 6;
    uint64 pageSize = 7;
    string sort = 8;
    int32 type = 9; // 1帖子，2文章，3视频
}
message PostCommentReplyResp {
    repeated PostCommentReplyItem data = 1;
    uint64 total = 2;
}
message ArticleCommentReplyResp {
    repeated ArticleCommentReplyItem data = 1;
    uint64 total = 2;
}
message GetCommentReplyListResp {
    PostCommentReplyResp post = 1;
    ArticleCommentReplyResp article = 2;
}

service CommentClass {
    // group: Comment
    rpc AddComment(AddCommentReq) returns(OkResp);
    // group: Comment
    rpc DeleteComment(DeleteCommentReq) returns(OkResp);
    // group: Comment
    rpc GetCommentById(GetCommentByIdReq) returns(GetCommentByIdResp);
    // group: Comment
    rpc GetCommentList(GetCommentListReq) returns(GetCommentListResp);
    // group: Comment
    rpc AddCommentReply(AddCommentReplyReq) returns(OkResp);
    // group: Comment
    rpc DeleteCommentReply(DeleteCommentReplyReq) returns(OkResp);
    // group: Comment
    rpc GetCommentReplyById(GetCommentReplyByIdReq) returns(GetCommentReplyByIdResp);
    // group: Comment
    rpc GetCommentReplyList(GetCommentReplyListReq) returns(GetCommentReplyListResp);

}