// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"qinglv-backend/app/user/rpc/internal/logic/followingclass"
	"qinglv-backend/app/user/rpc/internal/svc"
	"qinglv-backend/app/user/rpc/user"
)

type FollowingClassServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedFollowingClassServer
}

func NewFollowingClassServer(svcCtx *svc.ServiceContext) *FollowingClassServer {
	return &FollowingClassServer{
		svcCtx: svcCtx,
	}
}

func (s *FollowingClassServer) AddFollowing(ctx context.Context, in *user.AddFollowingReq) (*user.AddFollowingResp, error) {
	l := followingclasslogic.NewAddFollowingLogic(ctx, s.svcCtx)
	return l.AddFollowing(in)
}

func (s *FollowingClassServer) DeleteFollowing(ctx context.Context, in *user.DeleteFollowingReq) (*user.DeleteFollowingResp, error) {
	l := followingclasslogic.NewDeleteFollowingLogic(ctx, s.svcCtx)
	return l.DeleteFollowing(in)
}

func (s *FollowingClassServer) GetFollowingList(ctx context.Context, in *user.GetFollowingListReq) (*user.GetFollowingListResp, error) {
	l := followingclasslogic.NewGetFollowingListLogic(ctx, s.svcCtx)
	return l.GetFollowingList(in)
}

func (s *FollowingClassServer) GetFollowingDetail(ctx context.Context, in *user.GetFollowingDetailReq) (*user.GetFollowingDetailResp, error) {
	l := followingclasslogic.NewGetFollowingDetailLogic(ctx, s.svcCtx)
	return l.GetFollowingDetail(in)
}

func (s *FollowingClassServer) CheckFollowing(ctx context.Context, in *user.CheckFollowingReq) (*user.CheckFollowingResp, error) {
	l := followingclasslogic.NewCheckFollowingLogic(ctx, s.svcCtx)
	return l.CheckFollowing(in)
}
