// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: pb/operation.proto

package operation

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CollectionClass_AddCollectionGroup_FullMethodName     = "/operation.CollectionClass/AddCollectionGroup"
	CollectionClass_GetCollectionGroupList_FullMethodName = "/operation.CollectionClass/GetCollectionGroupList"
	CollectionClass_GetCollectionGroupById_FullMethodName = "/operation.CollectionClass/GetCollectionGroupById"
	CollectionClass_CheckExistByName_FullMethodName       = "/operation.CollectionClass/CheckExistByName"
	CollectionClass_UpdateCollectionGroup_FullMethodName  = "/operation.CollectionClass/UpdateCollectionGroup"
	CollectionClass_DeleteCollectionGroup_FullMethodName  = "/operation.CollectionClass/DeleteCollectionGroup"
	CollectionClass_AddCollection_FullMethodName          = "/operation.CollectionClass/AddCollection"
	CollectionClass_DeleteCollection_FullMethodName       = "/operation.CollectionClass/DeleteCollection"
	CollectionClass_GetCollectionList_FullMethodName      = "/operation.CollectionClass/GetCollectionList"
	CollectionClass_GetCollectionAll_FullMethodName       = "/operation.CollectionClass/GetCollectionAll"
	CollectionClass_GetCollectionById_FullMethodName      = "/operation.CollectionClass/GetCollectionById"
)

// CollectionClassClient is the client API for CollectionClass service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CollectionClassClient interface {
	AddCollectionGroup(ctx context.Context, in *AddCollectionGroupReq, opts ...grpc.CallOption) (*OkResp, error)
	GetCollectionGroupList(ctx context.Context, in *GetCollectionGroupListReq, opts ...grpc.CallOption) (*GetCollectionGroupListResp, error)
	GetCollectionGroupById(ctx context.Context, in *GetCollectionGroupByIdReq, opts ...grpc.CallOption) (*GetCollectionGroupByIdResp, error)
	CheckExistByName(ctx context.Context, in *CheckExistByNameReq, opts ...grpc.CallOption) (*CheckExistByNameResp, error)
	UpdateCollectionGroup(ctx context.Context, in *UpdateCollectionGroupReq, opts ...grpc.CallOption) (*OkResp, error)
	DeleteCollectionGroup(ctx context.Context, in *DeleteCollectionGroupReq, opts ...grpc.CallOption) (*OkResp, error)
	AddCollection(ctx context.Context, in *AddCollectionReq, opts ...grpc.CallOption) (*OkResp, error)
	DeleteCollection(ctx context.Context, in *DeleteCollectionReq, opts ...grpc.CallOption) (*OkResp, error)
	GetCollectionList(ctx context.Context, in *GetCollectionListReq, opts ...grpc.CallOption) (*GetCollectionListResp, error)
	GetCollectionAll(ctx context.Context, in *GetCollectionAllReq, opts ...grpc.CallOption) (*GetCollectionAllResp, error)
	GetCollectionById(ctx context.Context, in *GetCollectionByIdReq, opts ...grpc.CallOption) (*GetCollectionByIdResp, error)
}

type collectionClassClient struct {
	cc grpc.ClientConnInterface
}

func NewCollectionClassClient(cc grpc.ClientConnInterface) CollectionClassClient {
	return &collectionClassClient{cc}
}

func (c *collectionClassClient) AddCollectionGroup(ctx context.Context, in *AddCollectionGroupReq, opts ...grpc.CallOption) (*OkResp, error) {
	out := new(OkResp)
	err := c.cc.Invoke(ctx, CollectionClass_AddCollectionGroup_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionClassClient) GetCollectionGroupList(ctx context.Context, in *GetCollectionGroupListReq, opts ...grpc.CallOption) (*GetCollectionGroupListResp, error) {
	out := new(GetCollectionGroupListResp)
	err := c.cc.Invoke(ctx, CollectionClass_GetCollectionGroupList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionClassClient) GetCollectionGroupById(ctx context.Context, in *GetCollectionGroupByIdReq, opts ...grpc.CallOption) (*GetCollectionGroupByIdResp, error) {
	out := new(GetCollectionGroupByIdResp)
	err := c.cc.Invoke(ctx, CollectionClass_GetCollectionGroupById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionClassClient) CheckExistByName(ctx context.Context, in *CheckExistByNameReq, opts ...grpc.CallOption) (*CheckExistByNameResp, error) {
	out := new(CheckExistByNameResp)
	err := c.cc.Invoke(ctx, CollectionClass_CheckExistByName_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionClassClient) UpdateCollectionGroup(ctx context.Context, in *UpdateCollectionGroupReq, opts ...grpc.CallOption) (*OkResp, error) {
	out := new(OkResp)
	err := c.cc.Invoke(ctx, CollectionClass_UpdateCollectionGroup_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionClassClient) DeleteCollectionGroup(ctx context.Context, in *DeleteCollectionGroupReq, opts ...grpc.CallOption) (*OkResp, error) {
	out := new(OkResp)
	err := c.cc.Invoke(ctx, CollectionClass_DeleteCollectionGroup_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionClassClient) AddCollection(ctx context.Context, in *AddCollectionReq, opts ...grpc.CallOption) (*OkResp, error) {
	out := new(OkResp)
	err := c.cc.Invoke(ctx, CollectionClass_AddCollection_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionClassClient) DeleteCollection(ctx context.Context, in *DeleteCollectionReq, opts ...grpc.CallOption) (*OkResp, error) {
	out := new(OkResp)
	err := c.cc.Invoke(ctx, CollectionClass_DeleteCollection_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionClassClient) GetCollectionList(ctx context.Context, in *GetCollectionListReq, opts ...grpc.CallOption) (*GetCollectionListResp, error) {
	out := new(GetCollectionListResp)
	err := c.cc.Invoke(ctx, CollectionClass_GetCollectionList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionClassClient) GetCollectionAll(ctx context.Context, in *GetCollectionAllReq, opts ...grpc.CallOption) (*GetCollectionAllResp, error) {
	out := new(GetCollectionAllResp)
	err := c.cc.Invoke(ctx, CollectionClass_GetCollectionAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionClassClient) GetCollectionById(ctx context.Context, in *GetCollectionByIdReq, opts ...grpc.CallOption) (*GetCollectionByIdResp, error) {
	out := new(GetCollectionByIdResp)
	err := c.cc.Invoke(ctx, CollectionClass_GetCollectionById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CollectionClassServer is the server API for CollectionClass service.
// All implementations must embed UnimplementedCollectionClassServer
// for forward compatibility
type CollectionClassServer interface {
	AddCollectionGroup(context.Context, *AddCollectionGroupReq) (*OkResp, error)
	GetCollectionGroupList(context.Context, *GetCollectionGroupListReq) (*GetCollectionGroupListResp, error)
	GetCollectionGroupById(context.Context, *GetCollectionGroupByIdReq) (*GetCollectionGroupByIdResp, error)
	CheckExistByName(context.Context, *CheckExistByNameReq) (*CheckExistByNameResp, error)
	UpdateCollectionGroup(context.Context, *UpdateCollectionGroupReq) (*OkResp, error)
	DeleteCollectionGroup(context.Context, *DeleteCollectionGroupReq) (*OkResp, error)
	AddCollection(context.Context, *AddCollectionReq) (*OkResp, error)
	DeleteCollection(context.Context, *DeleteCollectionReq) (*OkResp, error)
	GetCollectionList(context.Context, *GetCollectionListReq) (*GetCollectionListResp, error)
	GetCollectionAll(context.Context, *GetCollectionAllReq) (*GetCollectionAllResp, error)
	GetCollectionById(context.Context, *GetCollectionByIdReq) (*GetCollectionByIdResp, error)
	mustEmbedUnimplementedCollectionClassServer()
}

// UnimplementedCollectionClassServer must be embedded to have forward compatible implementations.
type UnimplementedCollectionClassServer struct {
}

func (UnimplementedCollectionClassServer) AddCollectionGroup(context.Context, *AddCollectionGroupReq) (*OkResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCollectionGroup not implemented")
}
func (UnimplementedCollectionClassServer) GetCollectionGroupList(context.Context, *GetCollectionGroupListReq) (*GetCollectionGroupListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCollectionGroupList not implemented")
}
func (UnimplementedCollectionClassServer) GetCollectionGroupById(context.Context, *GetCollectionGroupByIdReq) (*GetCollectionGroupByIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCollectionGroupById not implemented")
}
func (UnimplementedCollectionClassServer) CheckExistByName(context.Context, *CheckExistByNameReq) (*CheckExistByNameResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckExistByName not implemented")
}
func (UnimplementedCollectionClassServer) UpdateCollectionGroup(context.Context, *UpdateCollectionGroupReq) (*OkResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCollectionGroup not implemented")
}
func (UnimplementedCollectionClassServer) DeleteCollectionGroup(context.Context, *DeleteCollectionGroupReq) (*OkResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCollectionGroup not implemented")
}
func (UnimplementedCollectionClassServer) AddCollection(context.Context, *AddCollectionReq) (*OkResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCollection not implemented")
}
func (UnimplementedCollectionClassServer) DeleteCollection(context.Context, *DeleteCollectionReq) (*OkResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCollection not implemented")
}
func (UnimplementedCollectionClassServer) GetCollectionList(context.Context, *GetCollectionListReq) (*GetCollectionListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCollectionList not implemented")
}
func (UnimplementedCollectionClassServer) GetCollectionAll(context.Context, *GetCollectionAllReq) (*GetCollectionAllResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCollectionAll not implemented")
}
func (UnimplementedCollectionClassServer) GetCollectionById(context.Context, *GetCollectionByIdReq) (*GetCollectionByIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCollectionById not implemented")
}
func (UnimplementedCollectionClassServer) mustEmbedUnimplementedCollectionClassServer() {}

// UnsafeCollectionClassServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CollectionClassServer will
// result in compilation errors.
type UnsafeCollectionClassServer interface {
	mustEmbedUnimplementedCollectionClassServer()
}

func RegisterCollectionClassServer(s grpc.ServiceRegistrar, srv CollectionClassServer) {
	s.RegisterService(&CollectionClass_ServiceDesc, srv)
}

func _CollectionClass_AddCollectionGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCollectionGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionClassServer).AddCollectionGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectionClass_AddCollectionGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionClassServer).AddCollectionGroup(ctx, req.(*AddCollectionGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectionClass_GetCollectionGroupList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollectionGroupListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionClassServer).GetCollectionGroupList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectionClass_GetCollectionGroupList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionClassServer).GetCollectionGroupList(ctx, req.(*GetCollectionGroupListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectionClass_GetCollectionGroupById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollectionGroupByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionClassServer).GetCollectionGroupById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectionClass_GetCollectionGroupById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionClassServer).GetCollectionGroupById(ctx, req.(*GetCollectionGroupByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectionClass_CheckExistByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckExistByNameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionClassServer).CheckExistByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectionClass_CheckExistByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionClassServer).CheckExistByName(ctx, req.(*CheckExistByNameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectionClass_UpdateCollectionGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCollectionGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionClassServer).UpdateCollectionGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectionClass_UpdateCollectionGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionClassServer).UpdateCollectionGroup(ctx, req.(*UpdateCollectionGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectionClass_DeleteCollectionGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCollectionGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionClassServer).DeleteCollectionGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectionClass_DeleteCollectionGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionClassServer).DeleteCollectionGroup(ctx, req.(*DeleteCollectionGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectionClass_AddCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCollectionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionClassServer).AddCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectionClass_AddCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionClassServer).AddCollection(ctx, req.(*AddCollectionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectionClass_DeleteCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCollectionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionClassServer).DeleteCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectionClass_DeleteCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionClassServer).DeleteCollection(ctx, req.(*DeleteCollectionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectionClass_GetCollectionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollectionListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionClassServer).GetCollectionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectionClass_GetCollectionList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionClassServer).GetCollectionList(ctx, req.(*GetCollectionListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectionClass_GetCollectionAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollectionAllReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionClassServer).GetCollectionAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectionClass_GetCollectionAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionClassServer).GetCollectionAll(ctx, req.(*GetCollectionAllReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectionClass_GetCollectionById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollectionByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionClassServer).GetCollectionById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectionClass_GetCollectionById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionClassServer).GetCollectionById(ctx, req.(*GetCollectionByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CollectionClass_ServiceDesc is the grpc.ServiceDesc for CollectionClass service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CollectionClass_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "operation.CollectionClass",
	HandlerType: (*CollectionClassServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddCollectionGroup",
			Handler:    _CollectionClass_AddCollectionGroup_Handler,
		},
		{
			MethodName: "GetCollectionGroupList",
			Handler:    _CollectionClass_GetCollectionGroupList_Handler,
		},
		{
			MethodName: "GetCollectionGroupById",
			Handler:    _CollectionClass_GetCollectionGroupById_Handler,
		},
		{
			MethodName: "CheckExistByName",
			Handler:    _CollectionClass_CheckExistByName_Handler,
		},
		{
			MethodName: "UpdateCollectionGroup",
			Handler:    _CollectionClass_UpdateCollectionGroup_Handler,
		},
		{
			MethodName: "DeleteCollectionGroup",
			Handler:    _CollectionClass_DeleteCollectionGroup_Handler,
		},
		{
			MethodName: "AddCollection",
			Handler:    _CollectionClass_AddCollection_Handler,
		},
		{
			MethodName: "DeleteCollection",
			Handler:    _CollectionClass_DeleteCollection_Handler,
		},
		{
			MethodName: "GetCollectionList",
			Handler:    _CollectionClass_GetCollectionList_Handler,
		},
		{
			MethodName: "GetCollectionAll",
			Handler:    _CollectionClass_GetCollectionAll_Handler,
		},
		{
			MethodName: "GetCollectionById",
			Handler:    _CollectionClass_GetCollectionById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/operation.proto",
}

const (
	ShareClass_AddPostShare_FullMethodName       = "/operation.ShareClass/AddPostShare"
	ShareClass_AddArticleShare_FullMethodName    = "/operation.ShareClass/AddArticleShare"
	ShareClass_GetPostShareAll_FullMethodName    = "/operation.ShareClass/GetPostShareAll"
	ShareClass_GetArticleShareAll_FullMethodName = "/operation.ShareClass/GetArticleShareAll"
	ShareClass_DeletePostShare_FullMethodName    = "/operation.ShareClass/DeletePostShare"
	ShareClass_DeleteArticleShare_FullMethodName = "/operation.ShareClass/DeleteArticleShare"
)

// ShareClassClient is the client API for ShareClass service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShareClassClient interface {
	AddPostShare(ctx context.Context, in *AddPostShareReq, opts ...grpc.CallOption) (*OkResp, error)
	AddArticleShare(ctx context.Context, in *AddArticleShareReq, opts ...grpc.CallOption) (*OkResp, error)
	GetPostShareAll(ctx context.Context, in *GetPostShareAllReq, opts ...grpc.CallOption) (*GetPostShareAllResp, error)
	GetArticleShareAll(ctx context.Context, in *GetArticleShareAllReq, opts ...grpc.CallOption) (*GetArticleShareAllResp, error)
	DeletePostShare(ctx context.Context, in *DeletePostShareReq, opts ...grpc.CallOption) (*OkResp, error)
	DeleteArticleShare(ctx context.Context, in *DeleteArticleShareReq, opts ...grpc.CallOption) (*OkResp, error)
}

type shareClassClient struct {
	cc grpc.ClientConnInterface
}

func NewShareClassClient(cc grpc.ClientConnInterface) ShareClassClient {
	return &shareClassClient{cc}
}

func (c *shareClassClient) AddPostShare(ctx context.Context, in *AddPostShareReq, opts ...grpc.CallOption) (*OkResp, error) {
	out := new(OkResp)
	err := c.cc.Invoke(ctx, ShareClass_AddPostShare_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareClassClient) AddArticleShare(ctx context.Context, in *AddArticleShareReq, opts ...grpc.CallOption) (*OkResp, error) {
	out := new(OkResp)
	err := c.cc.Invoke(ctx, ShareClass_AddArticleShare_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareClassClient) GetPostShareAll(ctx context.Context, in *GetPostShareAllReq, opts ...grpc.CallOption) (*GetPostShareAllResp, error) {
	out := new(GetPostShareAllResp)
	err := c.cc.Invoke(ctx, ShareClass_GetPostShareAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareClassClient) GetArticleShareAll(ctx context.Context, in *GetArticleShareAllReq, opts ...grpc.CallOption) (*GetArticleShareAllResp, error) {
	out := new(GetArticleShareAllResp)
	err := c.cc.Invoke(ctx, ShareClass_GetArticleShareAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareClassClient) DeletePostShare(ctx context.Context, in *DeletePostShareReq, opts ...grpc.CallOption) (*OkResp, error) {
	out := new(OkResp)
	err := c.cc.Invoke(ctx, ShareClass_DeletePostShare_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareClassClient) DeleteArticleShare(ctx context.Context, in *DeleteArticleShareReq, opts ...grpc.CallOption) (*OkResp, error) {
	out := new(OkResp)
	err := c.cc.Invoke(ctx, ShareClass_DeleteArticleShare_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShareClassServer is the server API for ShareClass service.
// All implementations must embed UnimplementedShareClassServer
// for forward compatibility
type ShareClassServer interface {
	AddPostShare(context.Context, *AddPostShareReq) (*OkResp, error)
	AddArticleShare(context.Context, *AddArticleShareReq) (*OkResp, error)
	GetPostShareAll(context.Context, *GetPostShareAllReq) (*GetPostShareAllResp, error)
	GetArticleShareAll(context.Context, *GetArticleShareAllReq) (*GetArticleShareAllResp, error)
	DeletePostShare(context.Context, *DeletePostShareReq) (*OkResp, error)
	DeleteArticleShare(context.Context, *DeleteArticleShareReq) (*OkResp, error)
	mustEmbedUnimplementedShareClassServer()
}

// UnimplementedShareClassServer must be embedded to have forward compatible implementations.
type UnimplementedShareClassServer struct {
}

func (UnimplementedShareClassServer) AddPostShare(context.Context, *AddPostShareReq) (*OkResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPostShare not implemented")
}
func (UnimplementedShareClassServer) AddArticleShare(context.Context, *AddArticleShareReq) (*OkResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddArticleShare not implemented")
}
func (UnimplementedShareClassServer) GetPostShareAll(context.Context, *GetPostShareAllReq) (*GetPostShareAllResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostShareAll not implemented")
}
func (UnimplementedShareClassServer) GetArticleShareAll(context.Context, *GetArticleShareAllReq) (*GetArticleShareAllResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArticleShareAll not implemented")
}
func (UnimplementedShareClassServer) DeletePostShare(context.Context, *DeletePostShareReq) (*OkResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePostShare not implemented")
}
func (UnimplementedShareClassServer) DeleteArticleShare(context.Context, *DeleteArticleShareReq) (*OkResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteArticleShare not implemented")
}
func (UnimplementedShareClassServer) mustEmbedUnimplementedShareClassServer() {}

// UnsafeShareClassServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShareClassServer will
// result in compilation errors.
type UnsafeShareClassServer interface {
	mustEmbedUnimplementedShareClassServer()
}

func RegisterShareClassServer(s grpc.ServiceRegistrar, srv ShareClassServer) {
	s.RegisterService(&ShareClass_ServiceDesc, srv)
}

func _ShareClass_AddPostShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPostShareReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareClassServer).AddPostShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShareClass_AddPostShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareClassServer).AddPostShare(ctx, req.(*AddPostShareReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareClass_AddArticleShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddArticleShareReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareClassServer).AddArticleShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShareClass_AddArticleShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareClassServer).AddArticleShare(ctx, req.(*AddArticleShareReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareClass_GetPostShareAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostShareAllReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareClassServer).GetPostShareAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShareClass_GetPostShareAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareClassServer).GetPostShareAll(ctx, req.(*GetPostShareAllReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareClass_GetArticleShareAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArticleShareAllReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareClassServer).GetArticleShareAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShareClass_GetArticleShareAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareClassServer).GetArticleShareAll(ctx, req.(*GetArticleShareAllReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareClass_DeletePostShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePostShareReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareClassServer).DeletePostShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShareClass_DeletePostShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareClassServer).DeletePostShare(ctx, req.(*DeletePostShareReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareClass_DeleteArticleShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteArticleShareReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareClassServer).DeleteArticleShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShareClass_DeleteArticleShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareClassServer).DeleteArticleShare(ctx, req.(*DeleteArticleShareReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ShareClass_ServiceDesc is the grpc.ServiceDesc for ShareClass service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShareClass_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "operation.ShareClass",
	HandlerType: (*ShareClassServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPostShare",
			Handler:    _ShareClass_AddPostShare_Handler,
		},
		{
			MethodName: "AddArticleShare",
			Handler:    _ShareClass_AddArticleShare_Handler,
		},
		{
			MethodName: "GetPostShareAll",
			Handler:    _ShareClass_GetPostShareAll_Handler,
		},
		{
			MethodName: "GetArticleShareAll",
			Handler:    _ShareClass_GetArticleShareAll_Handler,
		},
		{
			MethodName: "DeletePostShare",
			Handler:    _ShareClass_DeletePostShare_Handler,
		},
		{
			MethodName: "DeleteArticleShare",
			Handler:    _ShareClass_DeleteArticleShare_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/operation.proto",
}

const (
	ThumbClass_AddThumb_FullMethodName              = "/operation.ThumbClass/AddThumb"
	ThumbClass_UpdateThumb_FullMethodName           = "/operation.ThumbClass/UpdateThumb"
	ThumbClass_GetThumbDetail_FullMethodName        = "/operation.ThumbClass/GetThumbDetail"
	ThumbClass_AddCommentThumb_FullMethodName       = "/operation.ThumbClass/AddCommentThumb"
	ThumbClass_UpdateCommentThumb_FullMethodName    = "/operation.ThumbClass/UpdateCommentThumb"
	ThumbClass_GetCommentThumbDetail_FullMethodName = "/operation.ThumbClass/GetCommentThumbDetail"
)

// ThumbClassClient is the client API for ThumbClass service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ThumbClassClient interface {
	// group: Thumb
	AddThumb(ctx context.Context, in *AddThumbReq, opts ...grpc.CallOption) (*OkResp, error)
	// group: PostThumb
	UpdateThumb(ctx context.Context, in *UpdateThumbReq, opts ...grpc.CallOption) (*OkResp, error)
	// group: PostThumb
	GetThumbDetail(ctx context.Context, in *GetThumbDetailReq, opts ...grpc.CallOption) (*GetThumbDetailResp, error)
	// group: CommentThumb
	AddCommentThumb(ctx context.Context, in *AddCommentThumbReq, opts ...grpc.CallOption) (*OkResp, error)
	// group: PostCommentThumb
	UpdateCommentThumb(ctx context.Context, in *UpdateCommentThumbReq, opts ...grpc.CallOption) (*OkResp, error)
	// group: PostCommentThumb
	GetCommentThumbDetail(ctx context.Context, in *GetCommentThumbDetailReq, opts ...grpc.CallOption) (*GetCommentThumbDetailResp, error)
}

type thumbClassClient struct {
	cc grpc.ClientConnInterface
}

func NewThumbClassClient(cc grpc.ClientConnInterface) ThumbClassClient {
	return &thumbClassClient{cc}
}

func (c *thumbClassClient) AddThumb(ctx context.Context, in *AddThumbReq, opts ...grpc.CallOption) (*OkResp, error) {
	out := new(OkResp)
	err := c.cc.Invoke(ctx, ThumbClass_AddThumb_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thumbClassClient) UpdateThumb(ctx context.Context, in *UpdateThumbReq, opts ...grpc.CallOption) (*OkResp, error) {
	out := new(OkResp)
	err := c.cc.Invoke(ctx, ThumbClass_UpdateThumb_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thumbClassClient) GetThumbDetail(ctx context.Context, in *GetThumbDetailReq, opts ...grpc.CallOption) (*GetThumbDetailResp, error) {
	out := new(GetThumbDetailResp)
	err := c.cc.Invoke(ctx, ThumbClass_GetThumbDetail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thumbClassClient) AddCommentThumb(ctx context.Context, in *AddCommentThumbReq, opts ...grpc.CallOption) (*OkResp, error) {
	out := new(OkResp)
	err := c.cc.Invoke(ctx, ThumbClass_AddCommentThumb_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thumbClassClient) UpdateCommentThumb(ctx context.Context, in *UpdateCommentThumbReq, opts ...grpc.CallOption) (*OkResp, error) {
	out := new(OkResp)
	err := c.cc.Invoke(ctx, ThumbClass_UpdateCommentThumb_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thumbClassClient) GetCommentThumbDetail(ctx context.Context, in *GetCommentThumbDetailReq, opts ...grpc.CallOption) (*GetCommentThumbDetailResp, error) {
	out := new(GetCommentThumbDetailResp)
	err := c.cc.Invoke(ctx, ThumbClass_GetCommentThumbDetail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ThumbClassServer is the server API for ThumbClass service.
// All implementations must embed UnimplementedThumbClassServer
// for forward compatibility
type ThumbClassServer interface {
	// group: Thumb
	AddThumb(context.Context, *AddThumbReq) (*OkResp, error)
	// group: PostThumb
	UpdateThumb(context.Context, *UpdateThumbReq) (*OkResp, error)
	// group: PostThumb
	GetThumbDetail(context.Context, *GetThumbDetailReq) (*GetThumbDetailResp, error)
	// group: CommentThumb
	AddCommentThumb(context.Context, *AddCommentThumbReq) (*OkResp, error)
	// group: PostCommentThumb
	UpdateCommentThumb(context.Context, *UpdateCommentThumbReq) (*OkResp, error)
	// group: PostCommentThumb
	GetCommentThumbDetail(context.Context, *GetCommentThumbDetailReq) (*GetCommentThumbDetailResp, error)
	mustEmbedUnimplementedThumbClassServer()
}

// UnimplementedThumbClassServer must be embedded to have forward compatible implementations.
type UnimplementedThumbClassServer struct {
}

func (UnimplementedThumbClassServer) AddThumb(context.Context, *AddThumbReq) (*OkResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddThumb not implemented")
}
func (UnimplementedThumbClassServer) UpdateThumb(context.Context, *UpdateThumbReq) (*OkResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateThumb not implemented")
}
func (UnimplementedThumbClassServer) GetThumbDetail(context.Context, *GetThumbDetailReq) (*GetThumbDetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetThumbDetail not implemented")
}
func (UnimplementedThumbClassServer) AddCommentThumb(context.Context, *AddCommentThumbReq) (*OkResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCommentThumb not implemented")
}
func (UnimplementedThumbClassServer) UpdateCommentThumb(context.Context, *UpdateCommentThumbReq) (*OkResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCommentThumb not implemented")
}
func (UnimplementedThumbClassServer) GetCommentThumbDetail(context.Context, *GetCommentThumbDetailReq) (*GetCommentThumbDetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommentThumbDetail not implemented")
}
func (UnimplementedThumbClassServer) mustEmbedUnimplementedThumbClassServer() {}

// UnsafeThumbClassServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ThumbClassServer will
// result in compilation errors.
type UnsafeThumbClassServer interface {
	mustEmbedUnimplementedThumbClassServer()
}

func RegisterThumbClassServer(s grpc.ServiceRegistrar, srv ThumbClassServer) {
	s.RegisterService(&ThumbClass_ServiceDesc, srv)
}

func _ThumbClass_AddThumb_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddThumbReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThumbClassServer).AddThumb(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThumbClass_AddThumb_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThumbClassServer).AddThumb(ctx, req.(*AddThumbReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThumbClass_UpdateThumb_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateThumbReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThumbClassServer).UpdateThumb(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThumbClass_UpdateThumb_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThumbClassServer).UpdateThumb(ctx, req.(*UpdateThumbReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThumbClass_GetThumbDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetThumbDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThumbClassServer).GetThumbDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThumbClass_GetThumbDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThumbClassServer).GetThumbDetail(ctx, req.(*GetThumbDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThumbClass_AddCommentThumb_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCommentThumbReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThumbClassServer).AddCommentThumb(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThumbClass_AddCommentThumb_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThumbClassServer).AddCommentThumb(ctx, req.(*AddCommentThumbReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThumbClass_UpdateCommentThumb_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCommentThumbReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThumbClassServer).UpdateCommentThumb(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThumbClass_UpdateCommentThumb_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThumbClassServer).UpdateCommentThumb(ctx, req.(*UpdateCommentThumbReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThumbClass_GetCommentThumbDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentThumbDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThumbClassServer).GetCommentThumbDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThumbClass_GetCommentThumbDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThumbClassServer).GetCommentThumbDetail(ctx, req.(*GetCommentThumbDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ThumbClass_ServiceDesc is the grpc.ServiceDesc for ThumbClass service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ThumbClass_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "operation.ThumbClass",
	HandlerType: (*ThumbClassServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddThumb",
			Handler:    _ThumbClass_AddThumb_Handler,
		},
		{
			MethodName: "UpdateThumb",
			Handler:    _ThumbClass_UpdateThumb_Handler,
		},
		{
			MethodName: "GetThumbDetail",
			Handler:    _ThumbClass_GetThumbDetail_Handler,
		},
		{
			MethodName: "AddCommentThumb",
			Handler:    _ThumbClass_AddCommentThumb_Handler,
		},
		{
			MethodName: "UpdateCommentThumb",
			Handler:    _ThumbClass_UpdateCommentThumb_Handler,
		},
		{
			MethodName: "GetCommentThumbDetail",
			Handler:    _ThumbClass_GetCommentThumbDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/operation.proto",
}

const (
	CommentClass_AddComment_FullMethodName          = "/operation.CommentClass/AddComment"
	CommentClass_DeleteComment_FullMethodName       = "/operation.CommentClass/DeleteComment"
	CommentClass_GetCommentById_FullMethodName      = "/operation.CommentClass/GetCommentById"
	CommentClass_GetCommentList_FullMethodName      = "/operation.CommentClass/GetCommentList"
	CommentClass_GetCommentAll_FullMethodName       = "/operation.CommentClass/GetCommentAll"
	CommentClass_UpdateComment_FullMethodName       = "/operation.CommentClass/UpdateComment"
	CommentClass_AddCommentReply_FullMethodName     = "/operation.CommentClass/AddCommentReply"
	CommentClass_DeleteCommentReply_FullMethodName  = "/operation.CommentClass/DeleteCommentReply"
	CommentClass_GetCommentReplyById_FullMethodName = "/operation.CommentClass/GetCommentReplyById"
	CommentClass_GetCommentReplyList_FullMethodName = "/operation.CommentClass/GetCommentReplyList"
	CommentClass_UpdateCommentReply_FullMethodName  = "/operation.CommentClass/UpdateCommentReply"
)

// CommentClassClient is the client API for CommentClass service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommentClassClient interface {
	AddComment(ctx context.Context, in *AddCommentReq, opts ...grpc.CallOption) (*OkResp, error)
	DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*OkResp, error)
	GetCommentById(ctx context.Context, in *GetCommentByIdReq, opts ...grpc.CallOption) (*GetCommentByIdResp, error)
	GetCommentList(ctx context.Context, in *GetCommentListReq, opts ...grpc.CallOption) (*GetCommentListResp, error)
	GetCommentAll(ctx context.Context, in *GetCommentAllReq, opts ...grpc.CallOption) (*GetCommentAllResp, error)
	UpdateComment(ctx context.Context, in *UpdateCommentReq, opts ...grpc.CallOption) (*OkResp, error)
	AddCommentReply(ctx context.Context, in *AddCommentReplyReq, opts ...grpc.CallOption) (*OkResp, error)
	DeleteCommentReply(ctx context.Context, in *DeleteCommentReplyReq, opts ...grpc.CallOption) (*OkResp, error)
	GetCommentReplyById(ctx context.Context, in *GetCommentReplyByIdReq, opts ...grpc.CallOption) (*GetCommentReplyByIdResp, error)
	GetCommentReplyList(ctx context.Context, in *GetCommentReplyListReq, opts ...grpc.CallOption) (*GetCommentReplyListResp, error)
	UpdateCommentReply(ctx context.Context, in *UpdateCommentReplyReq, opts ...grpc.CallOption) (*OkResp, error)
}

type commentClassClient struct {
	cc grpc.ClientConnInterface
}

func NewCommentClassClient(cc grpc.ClientConnInterface) CommentClassClient {
	return &commentClassClient{cc}
}

func (c *commentClassClient) AddComment(ctx context.Context, in *AddCommentReq, opts ...grpc.CallOption) (*OkResp, error) {
	out := new(OkResp)
	err := c.cc.Invoke(ctx, CommentClass_AddComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClassClient) DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*OkResp, error) {
	out := new(OkResp)
	err := c.cc.Invoke(ctx, CommentClass_DeleteComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClassClient) GetCommentById(ctx context.Context, in *GetCommentByIdReq, opts ...grpc.CallOption) (*GetCommentByIdResp, error) {
	out := new(GetCommentByIdResp)
	err := c.cc.Invoke(ctx, CommentClass_GetCommentById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClassClient) GetCommentList(ctx context.Context, in *GetCommentListReq, opts ...grpc.CallOption) (*GetCommentListResp, error) {
	out := new(GetCommentListResp)
	err := c.cc.Invoke(ctx, CommentClass_GetCommentList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClassClient) GetCommentAll(ctx context.Context, in *GetCommentAllReq, opts ...grpc.CallOption) (*GetCommentAllResp, error) {
	out := new(GetCommentAllResp)
	err := c.cc.Invoke(ctx, CommentClass_GetCommentAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClassClient) UpdateComment(ctx context.Context, in *UpdateCommentReq, opts ...grpc.CallOption) (*OkResp, error) {
	out := new(OkResp)
	err := c.cc.Invoke(ctx, CommentClass_UpdateComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClassClient) AddCommentReply(ctx context.Context, in *AddCommentReplyReq, opts ...grpc.CallOption) (*OkResp, error) {
	out := new(OkResp)
	err := c.cc.Invoke(ctx, CommentClass_AddCommentReply_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClassClient) DeleteCommentReply(ctx context.Context, in *DeleteCommentReplyReq, opts ...grpc.CallOption) (*OkResp, error) {
	out := new(OkResp)
	err := c.cc.Invoke(ctx, CommentClass_DeleteCommentReply_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClassClient) GetCommentReplyById(ctx context.Context, in *GetCommentReplyByIdReq, opts ...grpc.CallOption) (*GetCommentReplyByIdResp, error) {
	out := new(GetCommentReplyByIdResp)
	err := c.cc.Invoke(ctx, CommentClass_GetCommentReplyById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClassClient) GetCommentReplyList(ctx context.Context, in *GetCommentReplyListReq, opts ...grpc.CallOption) (*GetCommentReplyListResp, error) {
	out := new(GetCommentReplyListResp)
	err := c.cc.Invoke(ctx, CommentClass_GetCommentReplyList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClassClient) UpdateCommentReply(ctx context.Context, in *UpdateCommentReplyReq, opts ...grpc.CallOption) (*OkResp, error) {
	out := new(OkResp)
	err := c.cc.Invoke(ctx, CommentClass_UpdateCommentReply_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommentClassServer is the server API for CommentClass service.
// All implementations must embed UnimplementedCommentClassServer
// for forward compatibility
type CommentClassServer interface {
	AddComment(context.Context, *AddCommentReq) (*OkResp, error)
	DeleteComment(context.Context, *DeleteCommentReq) (*OkResp, error)
	GetCommentById(context.Context, *GetCommentByIdReq) (*GetCommentByIdResp, error)
	GetCommentList(context.Context, *GetCommentListReq) (*GetCommentListResp, error)
	GetCommentAll(context.Context, *GetCommentAllReq) (*GetCommentAllResp, error)
	UpdateComment(context.Context, *UpdateCommentReq) (*OkResp, error)
	AddCommentReply(context.Context, *AddCommentReplyReq) (*OkResp, error)
	DeleteCommentReply(context.Context, *DeleteCommentReplyReq) (*OkResp, error)
	GetCommentReplyById(context.Context, *GetCommentReplyByIdReq) (*GetCommentReplyByIdResp, error)
	GetCommentReplyList(context.Context, *GetCommentReplyListReq) (*GetCommentReplyListResp, error)
	UpdateCommentReply(context.Context, *UpdateCommentReplyReq) (*OkResp, error)
	mustEmbedUnimplementedCommentClassServer()
}

// UnimplementedCommentClassServer must be embedded to have forward compatible implementations.
type UnimplementedCommentClassServer struct {
}

func (UnimplementedCommentClassServer) AddComment(context.Context, *AddCommentReq) (*OkResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddComment not implemented")
}
func (UnimplementedCommentClassServer) DeleteComment(context.Context, *DeleteCommentReq) (*OkResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteComment not implemented")
}
func (UnimplementedCommentClassServer) GetCommentById(context.Context, *GetCommentByIdReq) (*GetCommentByIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommentById not implemented")
}
func (UnimplementedCommentClassServer) GetCommentList(context.Context, *GetCommentListReq) (*GetCommentListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommentList not implemented")
}
func (UnimplementedCommentClassServer) GetCommentAll(context.Context, *GetCommentAllReq) (*GetCommentAllResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommentAll not implemented")
}
func (UnimplementedCommentClassServer) UpdateComment(context.Context, *UpdateCommentReq) (*OkResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateComment not implemented")
}
func (UnimplementedCommentClassServer) AddCommentReply(context.Context, *AddCommentReplyReq) (*OkResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCommentReply not implemented")
}
func (UnimplementedCommentClassServer) DeleteCommentReply(context.Context, *DeleteCommentReplyReq) (*OkResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCommentReply not implemented")
}
func (UnimplementedCommentClassServer) GetCommentReplyById(context.Context, *GetCommentReplyByIdReq) (*GetCommentReplyByIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommentReplyById not implemented")
}
func (UnimplementedCommentClassServer) GetCommentReplyList(context.Context, *GetCommentReplyListReq) (*GetCommentReplyListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommentReplyList not implemented")
}
func (UnimplementedCommentClassServer) UpdateCommentReply(context.Context, *UpdateCommentReplyReq) (*OkResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCommentReply not implemented")
}
func (UnimplementedCommentClassServer) mustEmbedUnimplementedCommentClassServer() {}

// UnsafeCommentClassServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommentClassServer will
// result in compilation errors.
type UnsafeCommentClassServer interface {
	mustEmbedUnimplementedCommentClassServer()
}

func RegisterCommentClassServer(s grpc.ServiceRegistrar, srv CommentClassServer) {
	s.RegisterService(&CommentClass_ServiceDesc, srv)
}

func _CommentClass_AddComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentClassServer).AddComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentClass_AddComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentClassServer).AddComment(ctx, req.(*AddCommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentClass_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentClassServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentClass_DeleteComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentClassServer).DeleteComment(ctx, req.(*DeleteCommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentClass_GetCommentById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentClassServer).GetCommentById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentClass_GetCommentById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentClassServer).GetCommentById(ctx, req.(*GetCommentByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentClass_GetCommentList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentClassServer).GetCommentList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentClass_GetCommentList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentClassServer).GetCommentList(ctx, req.(*GetCommentListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentClass_GetCommentAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentAllReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentClassServer).GetCommentAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentClass_GetCommentAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentClassServer).GetCommentAll(ctx, req.(*GetCommentAllReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentClass_UpdateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentClassServer).UpdateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentClass_UpdateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentClassServer).UpdateComment(ctx, req.(*UpdateCommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentClass_AddCommentReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCommentReplyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentClassServer).AddCommentReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentClass_AddCommentReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentClassServer).AddCommentReply(ctx, req.(*AddCommentReplyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentClass_DeleteCommentReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommentReplyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentClassServer).DeleteCommentReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentClass_DeleteCommentReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentClassServer).DeleteCommentReply(ctx, req.(*DeleteCommentReplyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentClass_GetCommentReplyById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentReplyByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentClassServer).GetCommentReplyById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentClass_GetCommentReplyById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentClassServer).GetCommentReplyById(ctx, req.(*GetCommentReplyByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentClass_GetCommentReplyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentReplyListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentClassServer).GetCommentReplyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentClass_GetCommentReplyList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentClassServer).GetCommentReplyList(ctx, req.(*GetCommentReplyListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentClass_UpdateCommentReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCommentReplyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentClassServer).UpdateCommentReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentClass_UpdateCommentReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentClassServer).UpdateCommentReply(ctx, req.(*UpdateCommentReplyReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CommentClass_ServiceDesc is the grpc.ServiceDesc for CommentClass service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommentClass_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "operation.CommentClass",
	HandlerType: (*CommentClassServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddComment",
			Handler:    _CommentClass_AddComment_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _CommentClass_DeleteComment_Handler,
		},
		{
			MethodName: "GetCommentById",
			Handler:    _CommentClass_GetCommentById_Handler,
		},
		{
			MethodName: "GetCommentList",
			Handler:    _CommentClass_GetCommentList_Handler,
		},
		{
			MethodName: "GetCommentAll",
			Handler:    _CommentClass_GetCommentAll_Handler,
		},
		{
			MethodName: "UpdateComment",
			Handler:    _CommentClass_UpdateComment_Handler,
		},
		{
			MethodName: "AddCommentReply",
			Handler:    _CommentClass_AddCommentReply_Handler,
		},
		{
			MethodName: "DeleteCommentReply",
			Handler:    _CommentClass_DeleteCommentReply_Handler,
		},
		{
			MethodName: "GetCommentReplyById",
			Handler:    _CommentClass_GetCommentReplyById_Handler,
		},
		{
			MethodName: "GetCommentReplyList",
			Handler:    _CommentClass_GetCommentReplyList_Handler,
		},
		{
			MethodName: "UpdateCommentReply",
			Handler:    _CommentClass_UpdateCommentReply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/operation.proto",
}
